#!/usr/bin/env python3
"""fill-unit8.py — 填充 s6 第八单元 瘤、岩"""
TARGET = '/sessions/compassionate-hopeful-thompson/mnt/syllabus/subjects/s6-waike.js'

with open(TARGET, 'r', encoding='utf-8') as f:
    c = f.read()

idx8 = c.find('{unit:"第八单元')
idx9 = c.find('{unit:"第九单元')
print(f"Replace offset {idx8}-{idx9} (len={idx9-idx8})")

UNIT8 = r'''{unit:"第八单元 瘤、岩",subunits:[
  {name:"细目一：概述",points:[{id:"wk-8-1",name:"瘤、岩的病因病机、辨证论治和常用药物",type:"apply",
content:'<p><strong>瘤</strong>是瘀血痰滞浊气停留于体表的赘生物——"瘤者留也"。<strong>岩</strong>是肿块坚硬如石+表面凹凸不平——"岩者石也"。岩相当于恶性肿瘤（癌）。</p><div class=compare-table><div class=ct-left><h4>病因病机</h4><p><strong>气滞血瘀：</strong>气机不畅+血行瘀滞→结块<br><strong>痰凝湿聚：</strong>脾失健运+水湿内停+痰浊凝结<br><strong>热毒蕴结：</strong>火毒内生+热壅血瘀+腐肉为脓<br><strong>正气亏虚：</strong>脏腑功能减退+气血不足+邪气留居</p></div><div class=ct-right><h4>辨证论治与常用药</h4><p><strong>常用治法：</strong><br>理气散结→青皮陈皮枳壳木香香附<br>活血化瘀→桃仁红花川芎三棱莪术<br>化痰软坚→贝母半夏南星海藻昆布<br>清热解毒→银花连翘蒲公英半枝莲白花蛇舌草<br><strong>补益扶正：</strong>黄芪党参白术当归熟地</p></div></div><div class=classic-quote>《外科正宗》："瘤者，留也。或忧思郁怒，则气血凝滞；或风湿热毒，则经络壅阻，以致瘀血浊气停留，聚而成瘤。"<span class=src>——《外科正宗》</span></div><div class=plain>"瘤"和"岩"是良性和恶性的区别——瘤是良性的（肿块局限+边界清）+岩是恶性的（坚硬如石+扩散转移）。记住"瘤者留也"——气血堵在那里不走了+成了包。中医治瘤的核心思路是：初起攻邪（行气活血化痰）+久病扶正（补益气血）。这和西医"肿瘤"的理念有异曲同工之妙。</p><div class=mnem><strong>口诀：</strong>瘤留岩石良恶分，气滞痰凝血瘀因；理气活血化痰软，扶正祛邪治瘤岩。</div><div class=trap-box><strong>考点：</strong>1."瘤者留也"——气血凝滞停留而成。2."岩"即恶性肿瘤——质地坚硬如石+表面凹凸不平。3.瘤的四大病因：气滞+血瘀+痰凝+正虚。4.常用治法四类：理气+活血+化痰+解毒+扶正。5.注意：外科五瘤（气瘤+血瘤+肉瘤+筋瘤+骨瘤）与现代医学概念不同——中医"瘤"多为良性。</div></div>'}]
},
  {name:"细目二：血瘤",points:[{id:"wk-8-2",name:"血瘤的概念、诊断与治疗",type:"detail",
content:'<p><strong>血瘤</strong>是体表血管扩张形成的良性肿瘤（血管瘤）。特点：色红或暗紫+软如海绵+压之褪色+放手即复原。好发于面颈四肢+可出生即有。</p><div class=compare-table><div class=ct-left><h4>临床表现</h4><p><strong>颜色：</strong>鲜红/暗紫/紫蓝<br><strong>质地：</strong>柔软如海绵+可压缩<br><strong>边界：</strong>清楚+形状不规则<br><strong>特征：</strong>压之褪色+放手即复原+体位移动大小可变<br><strong>增长：</strong>随年龄缓慢增大<br><strong>并发症：</strong>破溃出血+感染</p></div><div class=ct-right><h4>辨证治疗</h4><p><strong>治法：</strong>凉血养血+滋阴降火+化瘀散结<br><strong>主方：</strong>芩连二母丸合凉血地黄汤<br>（黄芩黄连知母贝母+生地丹皮赤芍）<br><strong>外治：</strong>压迫法+注射硬化剂+激光/冷冻<br><strong>较大者：</strong>手术切除</p></div></div><div class=classic-quote>《外科正宗》："血瘤者，微紫微红，软硬间杂，皮色隐隐缠如红丝，若破血流不止。"<span class=src>——《外科正宗》</span></div><div class=plain>血瘤就是血管瘤——一团畸形血管团。特点是"压之褪色+放手回来"——像海绵一样。最常见的类型是婴幼儿血管瘤——出生就有或出生后几周出现。大多数血管瘤不需要治疗——会自行消退（1-5岁）。但如果长在眼鼻口等关键部位影响功能+或者生长迅速+需要治疗。记住：血瘤推之可缩小+压之褪色——这是和岩（癌）鉴别的重要特征。</p><div class=mnem><strong>口诀：</strong>血瘤海绵色紫红，压之褪色放手充；芩连二母凉血治，激光硬化可建功。</div><div class=trap-box><strong>考点：</strong>1.血瘤特征——"压之褪色+放手即复原"（毛细血管瘤海绵状血管瘤特征）。2.好发部位：面颈四肢+可出生即有。3.内治：芩连二母丸（黄芩黄连知母贝母+生地丹皮）合凉血地黄汤清热凉血养阴。4.鉴别：血瘤（海绵状+压之褪色）vs筋瘤（静脉曲张+青筋盘曲）。5.血瘤出血常不易止——需加压止血。6.婴幼儿血管瘤多数可自愈。</div><div class=clinical-case>一位3岁男童右面部紫红色肿块+柔软如海绵+压之褪色——先天性血管瘤观察随访+嘱避免抓破。一位25岁女性左前臂海绵状血管瘤+渐增大胀痛——血瘤用芩连二母丸合凉血地黄汤（黄芩9g黄连6g知母9g贝母9g生地15g丹皮12g赤芍12g玄参15g）加紫草12g二十剂后瘤体缩小。未消退部分行激光治疗。</div></div>',
cardQuiz:[{q:"血瘤的典型体征是？",opts:["压之褪色+放手复原","推之不移","坚硬如石","红肿热痛"],ans:0},{q:"血瘤的内治代表方是？",opts:["芩连二母丸","桃红四物汤","海藻玉壶汤","五味消毒饮"],ans:0}]}]
},
  {name:"细目三：肉瘤",points:[{id:"wk-8-3",name:"肉瘤的概念及临床表现特点",type:"detail",
content:'<p><strong>肉瘤</strong>是皮下脂肪组织的良性肿瘤（脂肪瘤）。特点：软如棉+肿如馒+皮色如常+无痛。可单发或多发+好发于躯干+四肢。</p><div class=compare-table><div class=ct-left><h4>肉瘤特点</h4><p><strong>性质：</strong>良性（脂肪瘤）<br><strong>质地：</strong>柔软如棉+推之可移<br><strong>表面：</strong>皮色如常+无红肿<br><strong>大小：</strong>大小不一+可巨大<br><strong>疼痛：</strong>无痛（少数有压痛）<br><strong>治疗：</strong>小者无需处理+大者手术摘除</p></div><div class=ct-right><h4>与肉瘤（恶性肿瘤）鉴别</h4><p><strong>中医肉瘤（脂肪瘤）：</strong>良性+软如棉+无痛+生长慢<br><strong>西医肉瘤（sarcoma）：</strong>恶性+硬+痛+生长快+转移<br><strong>注意：</strong>同名但性质完全不同！</p></div></div><div class=classic-quote>《外科正宗》："肉瘤者，软如棉，硬似馒，皮色不变，不寒不热，渐渐而大。"<span class=src>——《外科正宗》</span></div><div class=plain>肉瘤就是普通的"脂肪瘤"——摸上去软软的像棉花、鼓起来像馒头。中医叫"肉瘤"但其实是良性肿瘤+完全不用担心（除非影响外观或压迫神经）。但要注意一个坑：中医的"肉瘤"（脂肪瘤）和西医的"肉瘤"（sarcoma恶性肿瘤）名字一样+但一个良性一个恶性！考试最爱考这个。治疗上小的不用管+大的可以切掉。</p><div class=mnem><strong>口诀：</strong>肉瘤软绵形如馒，皮色如常无痛感；中医脂肪瘤良性，与西医肉瘤要分辨。</div><div class=trap-box><strong>高频考点：</strong>1."肉瘤"在中医是良性（脂肪瘤）+在西医是恶性（sarcoma）！这最容易混淆。2.肉瘤典型特征："软如棉+肿如馒"——外科正宗原话（常考原文！）。3.多发性肉瘤往往与遗传有关（家族性脂肪瘤病）。4.鉴别：肉瘤（软如棉无痛）vs血瘤（海绵状压之褪色）。5.治疗：小者不需处理+大者手术摘除+中药健脾化痰（二陈汤）。6.注意：肉瘤极少恶变——但巨大者需切除。</div><div class=clinical-case>一位45岁男性后背皮下多个大小不等软性肿块+如棉如馒+皮色正常+无痛——多发性脂肪瘤中医属"肉瘤"+痰湿凝聚型用二陈汤（半夏9g陈皮6g茯苓15g甘草6g）加白芥子9g海藻15g昆布15g三十剂后部分瘤体缩小。嘱无需特殊处理+定期观察即可。</div></div>',
cardQuiz:[{q:'中医"肉瘤"相当于现代医学的？',opts:["脂肪瘤（良性）","肉瘤（恶性）","纤维瘤","血管瘤"],ans:0},{q:'《外科正宗》描述肉瘤"软如棉"的下一句是？',opts:["硬似馒","坚如石","肿如馒","色如常"],ans:0}]}]
},
  {name:"细目四：失荣",points:[{id:"wk-8-4",name:"失荣的概念、病因病机、临床表现及辨证论治",type:"detail",
content:'<p><strong>失荣</strong>是颈部原发性或转移性恶性肿瘤。特点：颈部肿块坚硬如石+推之不移+身体消瘦+面容憔悴。"失荣"者——失去荣华的枯萎之象。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肝郁痰凝（早期）：</strong>颈部肿块质硬+情志抑郁+胸胁胀痛<br>→ <strong>开郁散</strong>疏肝解郁化痰散结</p><p><strong>痰瘀互结（中期）：</strong>肿块增大坚硬+刺痛固定+舌紫暗<br>→ <strong>桃红四物汤合海藻玉壶汤</strong></p><p><strong>气血两虚（晚期）：</strong>肿块溃破气血衰败+消瘦+面色无华<br>→ <strong>香贝养荣汤</strong>补益气血</p></div><div class=ct-right><h4>鉴别与预后</h4><p><strong>失荣vs瘰疬：</strong><br>失荣→质硬如石+推之不移+融合+消瘦<br>瘰疬→串珠状+推之可移+不痛+破溃清稀</p><p><strong>预后：</strong><br>失荣预后差（晚期癌）<br>早期手术+放化疗+中药调理</p></div></div><div class=classic-quote>《外科正宗》："失荣者，其证多生于肩项之间，初起状如痰核，日渐长大，坚硬如石，推之不移，按之不动，半载一年，乃成破溃，气血衰败，终不可治。"<span class=src>——《外科正宗》</span></div><div class=plain>失荣名字本身就描述了病情——"失去荣华"+病人憔悴消瘦像枯萎的树。就是颈部淋巴结转移癌（最常见鼻咽癌+甲状腺癌+肺癌淋巴转移）。最难和瘰疬（淋巴结核）鉴别——瘰疬也是脖子上起疙瘩。关键区别：瘰疬推得动+不痛+溃破流清稀脓+失荣推不动+坚硬如石+病人消瘦。失荣预后很差——晚期多不可治。</p><div class=mnem><strong>口诀：</strong>失荣颈块硬如石，推之不移面容枯；早期开郁疏肝郁，中期桃红海藻服；晚期香贝养荣汤，早诊早治不可误。</div><div class=trap-box><strong>高频考点：</strong>1.失荣vs瘰疬——这是必考鉴别！失荣（恶性）硬如石推不动+瘰疬（结核）串珠推可动。2.失荣三期辨治：肝郁痰凝→开郁散（柴胡当归白芍白芥子白术郁金香附茯苓天葵草）+痰瘀互结→桃红四物汤合海藻玉壶汤+气血两虚→香贝养荣汤（香附贝母人参茯苓白术当归白芍熟地陈皮桔梗甘草生姜大枣）。3.失荣病名含义——"失其荣华"形容晚期恶病质。4.好发部位：颈项肩部。5.总属恶候——早发现早治疗。</div><div class=clinical-case>一位58岁男性颈部左侧肿块质硬如石+推之不移+伴声音嘶哑+消瘦——确诊为鼻咽癌颈部淋巴结转移（失荣）。早期用开郁散（柴胡9g当归9g白芍12g白芥子9g白术12g郁金9g香附9g茯苓15g天葵草15g）合白花蛇舌草30g半枝莲30g配合放化疗。晚期出现恶病质用香贝养荣汤（香附9g贝母9g黄芪30g当归12g白术12g茯苓15g陈皮6g熟地15g白芍12g甘草6g）调理。</div></div><div class=mini-quiz><div class=mq-title>一分钟诊室</div><div class=mq-scene>患者颈部肿块坚硬如石推之不移面容消瘦伴声音嘶哑</div><div class=mq-opts><span class=mq-opt data-ans=right>A. 失荣（恶性）</span><span class=mq-opt data-ans=wrong>B. 瘰疬（结核）</span><span class=mq-opt data-ans=wrong>C. 气瘿（甲状腺肿）</span><span class=mq-opt data-ans=wrong>D. 颈痈（淋巴结炎）</span></div><div class=mq-feedback style=display:none><template class=fb-right>正确！失荣=颈部恶性肿块（质地坚硬+推之不移+恶病质）。和瘰疬鉴别：瘰疬串珠推可动。</template><template class=fb-wrong>颈部分辨：失荣推不动+瘰疬推得动+气瘿在正中+颈痈红肿痛。</template></div></div>',
cardQuiz:[{q:"失荣和瘰疬的关键鉴别点是？",opts:["推之是否可移","是否疼痛","是否红肿","大小"],ans:0},{q:"失荣晚期气血两虚的主方是？",opts:["香贝养荣汤","开郁散","桃红四物汤","八珍汤"],ans:0}]}]
},
  {name:"细目五：肾岩",points:[{id:"wk-8-5",name:"肾岩的含义、病因病机、诊断及治疗原则",type:"apply",
content:'<p><strong>肾岩</strong>是阴茎的恶性病变（阴茎癌）。特点：阴茎头肿物+破溃翻花+脓血渗出。好发于包茎包皮过长者。中医称"肾岩翻花"。</p><div class=compare-table><div class=ct-left><h4>辨治要点</h4><p><strong>病因：</strong>包茎包皮垢长期刺激+湿热下注+肝肾阴虚<br><strong>早期：</strong>阴茎头硬结+丘疹+溃疡<br>→肝郁痰凝+湿热下注→<strong>龙胆泻肝汤</strong></p><p><strong>中晚期：</strong>肿块翻花+脓血恶臭+腹股沟淋巴结肿大<br>→阴虚火旺→<strong>知柏地黄丸</strong><br>→气血两虚→<strong>当归补血汤</strong></p><p><strong>治疗原则：</strong>手术主导（阴茎部分切/全切）+腹股沟淋巴结清扫+中药调理</p></div><div class=ct-right><h4>鉴别与预后</h4><p><strong>鉴别：</strong><br>阴茎乳头状瘤+尖锐湿疣+阴茎硬结症</p><p><strong>预后：</strong><br>早期手术效果好+5年生存率高<br>晚期预后差+腹股沟转移</p><p><strong>预防：</strong><br>包茎尽早行包皮环切术<br>注意个人卫生+包皮过长者每天清洗</p></div></div><div class=classic-quote>《疡科心得集》："肾岩翻花，阴茎头生肿块，溃后翻花如石榴皮，此肝肾素虚，湿热下注所致。"<span class=src>——《疡科心得集》</span></div><div class=plain>肾岩就是阴茎癌——"肾"代表前阴属肾+"岩"代表癌。最著名的描述是"肾岩翻花"——肿起来像翻花石榴一样。好发于包茎或包皮过长的人——包皮垢长期刺激是最大元凶。预防非常简单：包茎者做包皮环切+每天清洗。这就是为什么犹太教（新生儿就割包皮）基本上没有阴茎癌。治疗上早期手术效果很好。</p><div class=mnem><strong>口诀：</strong>肾岩阴茎翻花名，包茎包皮垢积成；早期龙胆泻肝清，阴虚知柏气虚归；手术为主早切除，预防包皮环切行。</div><div class=trap-box><strong>考点：</strong>1."肾岩翻花"——阴茎恶性肿瘤翻花状（石榴状）。2.肾岩属"四大绝症"之一（失荣+肾岩+乳岩+瘰疬翻花）。3.最明确病因——包茎包皮垢长期刺激。4.预防：包皮环切术。5.早期手术为主（阴茎部分切除）+淋巴结转移需清扫。6.内治辅助：早期湿热下注龙胆泻肝汤+中期阴虚知柏地黄丸+晚期气血两虚当归补血汤。</div><div class=clinical-case>一位50岁男性包茎史+阴茎头部肿物溃后翻花如石榴+脓血渗出+轻痛——肾岩早期行阴茎部分切除术+术后病理鳞状细胞癌。术后用龙胆泻肝汤（龙胆草9g栀子9g黄芩9g柴胡9g生地15g车前草15g泽泻12g当归9g甘草6g）加半枝莲30g白花蛇舌草30g消炎清热+防复发。</div></div><div class=mini-quiz><div class=mq-title>一分钟诊室</div><div class=mq-scene>患者包茎史+阴茎头肿物破溃翻花如石榴+脓血渗出</div><div class=mq-opts><span class=mq-opt data-ans=right>A. 肾岩（阴茎癌）</span><span class=mq-opt data-ans=wrong>B. 尖锐湿疣</span><span class=mq-opt data-ans=wrong>C. 阴茎硬结症</span><span class=mq-opt data-ans=wrong>D. 下疳</span></div><div class=mq-feedback style=display:none><template class=fb-right>正确！肾岩翻花=阴茎癌（翻花如石榴+包茎史+鳞癌）。手术为主+预防包皮环切。</template><template class=fb-wrong>肾岩翻花破溃如石榴+尖锐湿疣菜花样+硬结症斑块不破+下疳是梅毒硬结。</template></div></div>',
cardQuiz:[{q:"肾岩最重要的预防措施是？",opts:["包皮环切","注意卫生","定期体检","中药调理"],ans:0},{q:'肾岩翻花的"翻花"描述的是？',opts:["肿块破溃如翻花石榴","肿瘤生长速度快","肿瘤颜色鲜红","疼痛剧烈"],ans:0}]}]
}
]}'''

after = c[:idx8] + UNIT8 + ',' + c[idx9:]

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(after)

print(f"Done. Size: {len(after)} bytes (was {len(c)} bytes)")
