#!/usr/bin/env python3
"""fill-unit3.py — 填充 s6 第三单元 中医外科疾病辨证"""
TARGET = '/sessions/compassionate-hopeful-thompson/mnt/syllabus/subjects/s6-waike.js'

with open(TARGET, 'r', encoding='utf-8') as f:
    c = f.read()

idx3 = c.find('{unit:"第三单元')
idx4 = c.find('{unit:"第四单元')

UNIT3 = r'''{unit:"第三单元 中医外科疾病辨证",subunits:[
  {name:"细目一：辨病",points:[{id:"wk-1b-1",name:"辨病的概念与方法",type:"concept",
content:'<p><strong>辨病</strong>就是辨识外科疾病的总称和病名。包括：采集病史（发病情况+诱因+既往史）+全面检查（局部+全身）+综合分析（病名+证型）。</p><div class=compare-table><div class=ct-left><h4>辨病要点</h4><p><strong>整体辨病：</strong>望全身+闻声音气味+问病史+切脉</p><p><strong>局部辨病：</strong>望局部形态+闻脓液气味+问疼痛肿胀+切肿物质地温度</p><p><strong>治疗总纲：</strong>先辨病+后辨证。病不同则基本法则不同。</p></div><div class=ct-right><h4>辨病与辨证的关系</h4><p><strong>辨病：</strong>确定是什么疾病（病名诊断）<br>例：这是"疖"还是"疔"？</p><p><strong>辨证：</strong>确定疾病当前阶段的证型（证候诊断）<br>例：湿热型还是气滞型？</p><p>先辨病（确定大方向）+再辨证（确定具体治法）。</p></div></div><div class=classic-quote>《外科证治全生集》："凭经治症，天下皆然；分别阴阳，唯外科为要。"<span class=src>——《外科证治全生集》</span></div><div class=plain>辨病就是先搞清楚病人得的是什么病（诊断病名），然后再判断这个病现在处于什么阶段（辨证型）。好比开车：先搞清楚你要去哪个城市（辨病），再看沿路天气路况选择怎么开（辨证）。外科有外科的特殊性——很多外科病看一眼就知道是什么病（望诊在辨病中很重要）。</p><div class=mnem><strong>口诀：</strong>先辨病来后辨证，望闻问切四诊明；确定病名再分型，整体局部要并重。</div></div>'}]
},
  {name:"细目二：阴阳辨证",points:[{id:"wk-2-1",name:"以局部症状辨别阴阳",type:"apply",
content:'<p><strong>阴阳辨证</strong>是外科辨证的总纲——"外科尤以辨阴阳为第一要义"。</p><div class=compare-table><div class=ct-left><h4>阳证</h4><p><strong>发病：</strong>急<br><strong>病位：</strong>浅（皮肉）<br><strong>皮色：</strong>红赤<br><strong>皮温：</strong>灼热<br><strong>肿形：</strong>高肿突起<br><strong>肿胀范围：</strong>局限<br><strong>硬度：</strong>软硬适度<br><strong>痛感：</strong>剧烈<br><strong>脓液：</strong>稠厚<br><strong>病程：</strong>短<br><strong>预后：</strong>易消易溃易敛</p></div><div class=ct-right><h4>阴证</h4><p><strong>发病：</strong>缓<br><strong>病位：</strong>深（筋骨）<br><strong>皮色：</strong>苍白/紫暗/不变<br><strong>皮温：</strong>不热/微热<br><strong>肿形：</strong>平塌漫肿<br><strong>肿胀范围：</strong>弥漫<br><strong>硬度：</strong>坚硬如石/柔软如棉<br><strong>痛感：</strong>不痛/隐痛/酸痛<br><strong>脓液：</strong>稀薄<br><strong>病程：</strong>长<br><strong>预后：</strong>难消难溃难敛</p></div></div><div class=classic-quote>《疡医大全》："凡诊视痈疽，施治必须先审阴阳，乃医道之纲领。阴阳无谬，治焉有差？"<span class=src>——《疡医大全》</span></div><div class=plain>阴阳辨证是外科最重要的辨证方法。通俗说就是看这个病是"热性的（阳）"还是"寒性的（阴）"。记住几个快速判断法：红+肿+热+痛=阳证；不红+不热+平塌漫肿=阴证。掌握阴阳就能选对治法和外用药。一定要注意：阴证和阳证可以互相转化（阳转阴是病情加重+阴转阳是好转）。</p><div class=mnem><strong>口诀：</strong>阳证红肿热痛急，局限高突脓稠黄；阴证漫肿不红热，酸痛稀脓病程长。</div><div class=trap-box><strong>高频考点：</strong>1."外科尤以辨阴阳为第一要义"——外科辨证总纲（必考原文！）。2.阳证：表浅+红热+高肿+痛剧+脓稠。3.阴证：深在+不红不热+漫肿+不痛/隐痛+脓稀。4.阳转阴=病情恶化；阴转阳=好转。5.阴阳转化是判断预后的关键。6.半阴半阳证——介于阴阳之间+按"和营"法治。</div></div>'}]
},
  {name:"细目三：部位辨证",points:[{id:"wk-2a-1",name:"发于上、中、下部疾病的病因与特点",type:"detail",
content:'<p><strong>部位辨证</strong>（上中下三部辨证）是根据疾病发生的部位判断病因和治法的重要方法。</p><div class=compare-table><div class=ct-left><h4>上部辨证</h4><p><strong>部位：</strong>头面+颈项+上肢<br><strong>病因：</strong>风温风热居多<br><strong>特点：</strong>肿痛在上+来势急<br><strong>治则：</strong>疏风清热<br><strong>代表方：</strong>牛蒡解肌汤</p><p>头部属阳+风性上行→上部多风火</p></div><div class=ct-right><h4>中部/下部辨证</h4><p><strong>中部（胸腹腰背）：</strong><br>病因：气郁火郁居多<br>特点：胀痛+攻窜不定+伴情志<br>治则：疏肝理气<br>代表方：柴胡疏肝散/逍遥散</p><p><strong>下部（臀腿胫足）：</strong><br>病因：湿热下注居多<br>特点：肿胀沉重+水疱糜烂<br>治则：清热利湿<br>代表方：五神汤/萆薢渗湿汤</p></div></div><div class=classic-quote>《疡科心得集》："大抵上部多风温风热+中部多气郁火郁+下部多湿热下注。"<span class=src>——《疡科心得集》</span></div><div class=plain>部位辨证就是"看位置猜病因"：长在头上脸上→风热（风往上吹）+长在中间胸腹→气郁（肝在中间）+长在腿上脚上→湿热（水往下流）。这是考试必考内容！记住口诀："上风+中郁+下湿热"。</p><div class=mnem><strong>口诀：</strong>上风热来中气郁，下部湿热要分清；头面牛蒡解肌汤，中部逍遥柴疏肝；下肢五神萆渗治，三焦辨证外科灵。</div><div class=trap-box><strong>高频考点：</strong>1."上风+中郁+下湿热"——部位辨证口诀（必考！）。2.上部病多风温风热→牛蒡解肌汤散风清热。3.中部病多气郁火郁→柴胡疏肝散/逍遥散疏肝理气。4.下部病多湿热下注→五神汤/萆薢渗湿汤清热利湿。5.出自《疡科心得集》余听鸿。6.此为上中下三焦辨证思想在外科的应用。</div></div>'}]
},
  {name:"细目四：经络辨证",points:[{id:"wk-2a-2",name:"十二经脉气血多少与外科疾病的关系及引经药",type:"apply",
content:'<p><strong>十二经气血多少</strong>是外科辨证的重要参考。手阳明大肠经+足阳明胃经——多气多血；手太阳小肠经+足太阳膀胱经+手厥阴心包经+足厥阴肝经——多血少气；手少阳三焦经+足少阳胆经+手少阴心经+足少阴肾经+手太阴肺经+足太阴脾经——多气少血。</p><div class=compare-table><div class=ct-left><h4>气血多少与外科</h4><p><strong>多气多血（阳明经）：</strong><br>易化热化脓+肿痛显著+正气抗邪有力<br>→治宜清热解毒+活血化瘀</p><p><strong>多血少气（太阳+厥阴+肝经）：</strong><br>血多易瘀滞+气少抗邪不足<br>→治宜行气活血+补托</p><p><strong>多气少血（三焦+胆+心肺肾脾经）：</strong><br>气有余化火+血少难化脓<br>→治宜清热+和营养血</p></div><div class=ct-right><h4>常用引经药</h4><p><strong>头颈部：</strong>川芎（头）+藁本（巅顶）+白芷（前额）+葛根（项）<br><strong>上肢：</strong>桂枝+桑枝+姜黄<br><strong>胁肋部：</strong>柴胡+青皮<br><strong>下肢：</strong>牛膝<br><strong>乳房：</strong>柴胡+青皮+橘叶<br><strong>肛门：</strong>升麻+柴胡+枳壳</p></div></div><div class=classic-quote>《外科大成》："引经之药，引经报使，直达病所，犹向导之兵也。"<span class=src>——《外科大成》</span></div><div class=plain>经络辨证就是用经络学说来认识外科疾病。每条经气血多少不一样——就像土地肥力不同。多气多血的（如胃经大肠经）：正气足抗病强+容易化脓（阳明经特点）。多血少气的（如肝经）：容易淤血（血多）+恢复慢（气少）。多气少血的（如肺经）：容易上火（气多）+不长肉（血少）。引经药像带路党——把药引导到病灶位置。</p><div class=mnem><strong>口诀：</strong>多气多血属阳明，多血少气厥阴肝；多气少血三焦胆，心肺肾脾在其中；引经川芎达头面，上肢桂枝下肢膝。</div><div class=trap-box><strong>高频考点：</strong>1.手足阳明经（大肠+胃）——多气多血。2.手足太阳（小肠+膀胱）+厥阴（心包+肝）——多血少气。3.手足少阳（三焦+胆）+少阴（心+肾）+太阴（肺+脾）——多气少血。4.引经药常考：川芎→头+桂枝→上肢+牛膝→下肢+柴胡→胁肋+乳房。5.在外科治疗中的应用：根据所属经脉选方加减。</div></div>'}]
},
  {name:"细目五：局部辨证",points:[
    {id:"wk-3-1",name:"辨肿",type:"apply",
content:'<p><strong>辨肿</strong>是根据肿的形态性质来判断病因证型。</p><div class=compare-table><div class=ct-left><h4>肿的性质（病因相关）</h4><p><strong>火肿：</strong>色红灼热+高肿突起<br><strong>寒肿：</strong>皮色苍白/青暗+木硬不热<br><strong>风肿：</strong>宣浮+游走无定+皮色不变<br><strong>湿肿：</strong>皮肉重坠深按凹陷+皮色不变/微黄<br><strong>痰肿：</strong>不红不热+软如棉/硬如核<br><strong>气肿：</strong>皮紧内软+随喜怒消长<br><strong>瘀血肿：</strong>皮色紫暗+固定不移<br><strong>郁结肿：</strong>坚硬如石+推之不移</p></div><div class=ct-right><h4>肿的形态（部位相关）</h4><p><strong>局限性：</strong>高肿突起+边界清→痈+阳证<br><strong>弥漫性：</strong>平塌漫肿+边界不清→疽+阴证</p><p><strong>辨肿临床意义：</strong><br>肿势局限高突→正气尚充+易治<br>肿势弥漫平塌→正气不足+难治</p></div></div><div class=classic-quote>《医宗金鉴》："人之气血，周流不息，稍有壅滞，即作肿矣。"<span class=src>——《医宗金鉴》</span></div><div class=plain>肿就是气血堵住了。怎么分辨是哪一种肿？关键看颜色和触感：红的灼热的是火肿+白的不热的是寒肿+游走的是风肿+按之凹陷的是湿肿+软绵绵的是痰肿+随情绪变化的是气肿+紫暗固定的是瘀血肿+硬如石的是郁结肿。</p><div class=mnem><strong>口诀：</strong>红肿火+白寒肿+宣浮风+凹陷湿+软绵痰+喜怒气+紫暗瘀+石硬郁。</div><div class=trap-box><strong>考点：</strong>1.火肿：色红灼热高肿——最常见。2.寒肿：皮色苍白木硬不热。3.风肿：宣浮游走+皮色不变。4.湿肿：深按凹陷+皮色不变/微黄+重坠感。5.痰肿：软绵/硬核+不红不热。6.气肿：随喜怒消长——皮紧内软。7.瘀血肿：紫暗固定。8.郁结肿：坚硬如石+推之不移。</div></div>'},
    {id:"wk-3-2",name:"辨肿块、结节",type:"apply",
content:'<p><strong>肿块</strong>是体表可触及的实质性/囊性肿物。<strong>结节</strong>是较小（<3cm）的局限性肿硬块。</p><div class=compare-table><div class=ct-left><h4>肿块辨证</h4><p><strong>大小形态：</strong>大小+形状+边界</p><p><strong>质地：</strong><br>坚硬如石→瘤岩（恶性）<br>韧实光滑→肉瘿、乳核（良性）<br>柔软如棉→肉瘤（脂肪瘤）<br>海绵状+压之褪色→血瘤</p><p><strong>活动度：</strong><br>活动好+推之可移→良性<br>固定不移+推之不动→恶性的可能</p></div><div class=ct-right><h4>结节辨证</h4><p><strong>大小：</strong>一般<3cm<br><strong>质地：</strong>中硬+边界清+可活动</p><p><strong>常见结节：</strong><br>瘰疬串珠状→颈侧淋巴结结核<br>乳房结节→乳癖（增生结节）<br>皮下结节→痰核/脂瘤</p><p><strong>鉴别：</strong><br>结节多良性+岩多恶性。</p></div></div><div class=classic-quote>《外科真诠》："肿块之辨，当分阴阳虚实，坚硬者多属阴，柔软者多属阳。"<span class=src>——《外科真诠》</span></div><div class=plain>肿块就是摸得到的"疙瘩"+结节是小的疙瘩。辨别良恶性主要看三点：边界（清还是不清）+质地（硬还是软）+活动度（动还是不动）。"边界清+质地软+推得动"=大概率良性。"边界不清+硬如石+推不动"=小心是恶性。但不绝对——需要结合B超等检查。</p><div class=mnem><strong>口诀：</strong>肿块结节辨良恶，边界质地活动看；光滑软绵多良性，石硬不动恶为多。</div></div>'},
    {id:"wk-3-3",name:"辨痛",type:"apply",
content:'<p><strong>辨痛</strong>是根据疼痛性质判断病因证型。</p><div class=compare-table><div class=ct-left><h4>按疼痛性质辨</h4><p><strong>刺痛：</strong>病变在皮肤——浅表<br><strong>灼痛：</strong>病变在肌肤——火热<br><strong>裂痛：</strong>病变在肌肉——肉裂<br><strong>钝痛：</strong>病变在骨节——深部<br><strong>酸痛：</strong>病变在关节——风湿</p><p><strong>胀痛：</strong>气滞+郁结<br><strong>绞痛：</strong>结石+血瘀<br><strong>啄痛：</strong>化脓（如鸡啄米）<br><strong>抽掣痛：</strong>经脉不通</p></div><div class=ct-right><h4>按病因辨痛</h4><p><strong>热痛：</strong>灼热剧痛→热证<br><strong>寒痛：</strong>酸痛不热→寒证<br><strong>风痛：</strong>游走性痛→风邪<br><strong>气痛：</strong>走窜胀痛→气滞<br><strong>瘀血痛：</strong>固定刺痛→血瘀<br><strong>化脓痛：</strong>持续跳痛如鸡啄→脓已成<br><strong>虚痛：</strong>隐痛绵绵→气血虚<br><strong>实痛：</strong>胀痛剧痛拒按→邪实</p></div></div><div class=classic-quote>《外科证治全书》："诸痛皆由气血瘀滞不通所致，通则不痛，痛则不通。"<span class=src>——《外科证治全书》</span></div><div class=plain>痛就是气血不通的信号——"不通则痛"。最重要的痛是"啄痛"（像鸡啄米一样一阵一阵跳痛）——这是化脓的表现！有啄痛说明脓已经形成了。考试最爱问：跳痛/啄痛提示什么？答：脓已成。另外持续性胀痛→气滞+固定刺痛→血瘀+酸痛不热→寒证。</p><div class=mnem><strong>口诀：</strong>刺痛皮+灼痛热+钝痛骨+酸痛风；胀痛气滞刺痛瘀，跳痛化脓要记牢。</div><div class=trap-box><strong>高频考点：</strong>1.啄痛/跳痛——提示成脓（必考！）。2.灼痛——火毒盛+刺痛——血瘀。3.酸痛——风湿+胀痛——气滞。4.按痛辨阴阳：剧痛拒按+阳证+隐痛喜按+阴证。5."通则不痛，痛则不通"——痛的总病机。</div></div>'},
    {id:"wk-3-4",name:"辨痒",type:"apply",
content:'<p><strong>辨痒</strong>是根据瘙痒的性质判断病因和病期。</p><div class=compare-table><div class=ct-left><h4>以原因辨痒</h4><p><strong>风胜：</strong>走窜无定+遍身瘙痒+抓痕血痂<br><strong>湿胜：</strong>浸淫四窜+水疱糜烂+滋水淋漓<br><strong>热胜：</strong>皮肤隐疹+焮红灼热+遇热加重<br><strong>虫淫：</strong>如虫行皮中+瘙痒剧烈+夜间加重<br><strong>血虚：</strong>皮肤干燥脱屑+瘙痒+血燥生风</p></div><div class=ct-right><h4>以病期辨痒</h4><p><strong>肿疡作痒（初期）：</strong><br>风热相搏+毒势未盛+痒感较轻<br>提示：毒邪渐散+趋向好转</p><p><strong>溃疡作痒（后期）：</strong><br>脓区不清+护理不当+过敏<br>或：气血渐复+新肉生长+"肉痒如虫行"</p><p><strong>新肉生长之痒——佳兆！</strong></p></div></div><div class=classic-quote>《外科证治全书》："痒虽属风，亦各有因。风胜者痒无定处+湿胜者痒必有水+热胜者痒必红肿+血虚者痒必干涩。"<span class=src>——《外科证治全书》</span></div><div class=plain>痒的原因很多。最常问的是"肿疡作痒"和"溃疡作痒"的不同：初期痒可能是在好转（毒散）+也可能是在加重（风热）。后期痒可能是好事情（新肉在长）——"肉痒如虫行"就是伤口在愈合。但也有可能是过敏或感染。临床上"新肉生长痒"是好现象+但要注意排除过敏。</p><div class=mnem><strong>口诀：</strong>风痒游走+湿痒流水+热痒红肿+虫痒夜重+血虚痒燥。</div><div class=trap-box><strong>高频考点：</strong>1.肿疡作痒——毒邪渐散（佳兆）或风热毒盛（恶化）。2.溃疡作痒——新肉生长（佳兆）或脓区过敏护理不当。3.风胜痒：走窜无定+遍身。4.湿胜痒：水疱糜烂+滋水。5.血虚痒：皮肤干燥脱屑。6."肉痒如虫行"——新肉生长之象。</div></div>'},
    {id:"wk-3-5",name:"辨脓",type:"apply",
content:'<p><strong>辨脓</strong>是判断脓液的形成和性质——外科切开引流的关键依据。</p><div class=compare-table><div class=ct-left><h4>成脓的判断</h4><p><strong>时间：</strong>阳证一般7天左右成脓+阴证病程长<br><strong>触诊：</strong>按之灼热+中软应指→脓已成<br><strong>痛感：</strong>跳痛啄痛→脓已成<br><strong>辨脓方法：</strong><br>·按压痛+中软者为脓成<br>·深部用穿刺抽脓确诊</p></div><div class=ct-right><h4>脓液性质</h4><p><strong>按色泽：</strong><br>·黄白稠厚→气血充盛+正能胜邪（佳）<br>·黄白稀薄→气血不足<br>·黄绿稠厚→绿脓杆菌<br>·脓中夹瘀血→血瘀<br>·脓色晦暗+腥臭→逆证（恶化）</p><p><strong>按质地：</strong><br>·稠厚→正气足<br>·稀薄→正气虚<br>·先稠后稀→正气渐复</p></div></div><div class=classic-quote>《外科精义》："凡疮疽，脓出而反痛者，此为虚也。"<span class=src>——《外科精义》</span></div><div class=plain>辨脓就是判断有没有化脓——有脓就要切开排脓+没脓就不要切。怎么判断有脓？三个方法：1.摸（按着热+中间软+有波动感）+2.看（跳痛/啄痛）+3.穿刺（深部抽脓）。记住"中软应指"就是脓已经形成了。脓的颜色和质地反映正气强弱——黄白稠厚是正气足+清稀是正气虚。</p><div class=mnem><strong>口诀：</strong>辨脓触诊应指验，按之中软脓已成；稠黄气血充盛好，稀薄色黯正气虚。</div><div class=trap-box><strong>高频考点：</strong>1.成脓的标志——"中软应指"（按之波动感）。2.啄痛/跳痛——脓已成。3.阳证7天左右成脓+阴证病程长。4.脓稠黄白→气血充盛（佳）+脓稀薄清→气血虚。5.脓绿→绿脓杆菌感染。6.脓出反痛→虚证（脓出痛减为正常+不减反增为虚）。7.脓已成即切开（脓熟开刀）+"刀法"讲究。</div></div>'},
    {id:"wk-3-6",name:"辨溃疡",type:"apply",
content:'<p><strong>辨溃疡</strong>是根据疮面形态判断预后和证型。</p><div class=compare-table><div class=ct-left><h4>阳证溃疡</h4><p><strong>形态：</strong>疮面红活+边缘高起+脓稠黄白<br><strong>肉芽：</strong>鲜红+颗粒均匀+触之易出血<br><strong>预后：</strong>易敛+愈合良好</p><p>代表：痈溃后（一般溃疡）</p><p><strong>原则：</strong><br>腐肉不去新肉不生→提脓祛腐<br>新肉已生→生肌敛疮</p></div><div class=ct-right><h4>阴证溃疡</h4><p><strong>形态：</strong>疮面暗淡+边缘平塌+脓液清稀<br><strong>肉芽：</strong>暗淡/水肿/苍白+触之不易出血<br><strong>预后：</strong>难敛+易反复</p><p>特殊溃疡形态：<br>·臁疮溃疡→经年不愈+凹陷<br>·瘰疬溃疡→破溃如败絮<br>·岩性溃疡→疮面翻花+如石榴</p></div></div><div class=classic-quote>《外科证治全生集》："溃后脓水渐少，新肉渐生，此为顺证。"<span class=src>——《外科证治全生集》</span></div><div class=plain>看溃疡就是看伤口长得怎么样。好的溃疡：颜色红红的+肉芽鲜亮+脓稠稠的→很快就能好。不好的溃疡：颜色暗的+肉芽苍白或水肿+脓清稀水水的→很难长。最特殊的是"翻花疮"——溃疡像翻开的石榴一样——这是岩（癌）的表现。记住"腐肉不去新肉不生"——有坏死组织要先去掉才能长新肉。</p><div class=mnem><strong>口诀：</strong>阳溃红活脓稠黄+阴溃暗淡脓清稀；翻花石榴岩性溃+臁疮凹陷久难医。</div><div class=trap-box><strong>考点：</strong>1.阳证溃疡：疮面红活+肉芽鲜红+脓稠→易愈。2.阴证溃疡：疮面暗淡+肉芽水肿/苍白+脓稀→难愈。3.岩性溃疡：翻花如石榴（癌性溃疡）。4.臁疮溃疡：凹陷经年不愈。5.瘰疬溃疡：破溃脓水清稀如败絮。6."腐肉不去新肉不生"——祛腐生肌原则。</div></div>'},
    {id:"wk-3-7",name:"辨出血",type:"apply",
content:'<p><strong>辨出血</strong>是根据出血的颜色、质地和伴随症状判断病因。</p><div class=compare-table><div class=ct-left><h4>按颜色辨</h4><p><strong>鲜红：</strong>血热妄行（实证）<br>→清热凉血止血</p><p><strong>淡红：</strong>气血不足/脾不统血（虚证）<br>→补气摄血</p><p><strong>紫暗：</strong>瘀血内停<br>→活血化瘀止血</p></div><div class=ct-right><h4>按性质辨</h4><p><strong>渗血：</strong>毛细血管出血+缓慢渗出<br><strong>涌血：</strong>小动脉出血+喷射状<br><strong>混合出血：</strong>血中夹脓→化脓性感染</p><p>外科出血处理原则：<br>急则治标→加压/结扎/止血药<br>缓则治本→辨证论治调内因</p></div></div><div class=classic-quote>《血证论》："止血为第一要法+消瘀为第二法+宁血为第三法+补血为收功之法。"<span class=src>——《血证论》</span></div><div class=plain>外科出血分两种：一是创面出血（外伤或手术后）+二是血证（内因导致）。总治则遵循唐容川《血证论》四步法：先止血→再活血消瘀→再宁血防复发→最后补血恢复。考试常考分辨颜色：鲜红=热（要凉血）+淡红=虚（要补气）+紫暗=瘀（要活血）。不要一出血就用止血药——要看清原因。</p><div class=mnem><strong>口诀：</strong>血热鲜红凉血止+气虚淡红补气摄；血瘀紫暗化瘀血+外科出血急则治。</div><div class=trap-box><strong>考点：</strong>1.血色鲜红→血热妄行+清热凉血。2.血色淡红→气血不足+补气摄血。3.血色紫暗→瘀血内停+活血化瘀。4.《血证论》止血四法：止血→消瘀→宁血→补血。5.外科出血先局部处理（加压包扎/结扎）+再辨证内治。6.注意：血中夹脓→化脓性感染。</div></div>'}
  ]}
]},

'''

after = c[:idx3] + UNIT3 + c[idx4:]

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(after)

print(f"Done. Size: {len(after)} bytes (was {len(c)} bytes)")
