#!/usr/bin/env python3
"""fill-fuke-unit3.py — 填充 s7 第三单元 月经病"""
TARGET = '/sessions/compassionate-hopeful-thompson/mnt/syllabus/subjects/s7-fuke.js'

with open(TARGET, 'r', encoding='utf-8') as f:
    c = f.read()

idx3 = c.find('{unit:"第三单元')
idx4 = c.find('{unit:"第四单元')

UNIT3 = r'''{unit:"第三单元 月经病",subunits:[
  {name:"细目一：概述",points:[{id:"fk-2-0",name:"月经病的定义、范围及治疗原则",type:"concept",
content:'<p><strong>月经病</strong>是月经周期+经期+经量+经色+经质的异常+伴随月经周期出现的症状。范围包括：周期异常（先后不定期）+经期异常（经期延长）+经量异常（过多过少）+伴随症状（痛经+经行诸证）+绝经前后诸证。</p><div class=compare-table><div class=ct-left><h4>治疗原则</h4><p><strong>总则：</strong>调经以治本</p><p><strong>具体原则：</strong><br>先病而后经不调→先治病<br>因病而致不调→先调经<br>急则治其标（暴崩→止血）<br>缓则治其本（平时→调经）</p></div><div class=ct-right><h4>调经大法</h4><p><strong>补肾：</strong>肾为月经之本<br>→肾虚者补之+重在补肾气</p><p><strong>扶脾：</strong>脾为气血之源<br>→健脾益气+升阳摄血</p><p><strong>疏肝：</strong>肝为藏血调气<br>→疏肝理气+肝郁解之</p><p><strong>调理气血：</strong><br>血虚补血+血瘀化瘀+气滞理气+气虚益气</p></div></div><div class=classic-quote>《景岳全书》："调经之要，贵在补脾胃以资血之源，养肾气以安血之室。"<span class=src>——《景岳全书》</span></div><div class=plain>月经病的治疗总原则很简单——"调经以治本"。什么叫治本？就是找出根本原因来治：肾虚了补+脾虚了健+肝郁了疏+血瘀了化。如果同时有其他病（比如先得了结核病导致月经不调）→先治那个病+病好了月经自然正常。急性大出血（崩漏）→先止血（治标）+血止了再调经（治本）。</p><div class=mnem><strong>口诀：</strong>调经治本肾脾肝，补肾扶脾疏肝兼；急则治标缓治本，先病后经次第安。</div><div class=trap-box><strong>高频考点：</strong>1.总则——"调经以治本"。2.本病与他病：先病致经不调→先治病+因病致经不调→先调经。3.急则治标（暴崩止血）+缓则治本（平时调经）。4.调经三法：补肾+扶脾+疏肝。5.补肾——调经之本（经本于肾）。6.《景岳全书》原文：调经在补脾胃+养肾气。</div></div>'}]
},
  {name:"细目二：月经先期",points:[{id:"fk-2-1",name:"月经先期的定义及辨证论治",type:"apply",
content:'<p><strong>月经先期</strong>是月经周期提前7天以上+连续2个周期以上。最多提前不超过2周。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>气虚证：</strong><br>经期提前+量多色淡质稀+神疲乏力+气短懒言<br>→ <strong>补中益气汤</strong>或<strong>举元煎</strong></p><p><strong>阳盛血热：</strong><br>经期提前+量多色紫红质稠+面红+口渴+尿黄<br>→ <strong>清经散</strong></p><p><strong>肝郁血热：</strong><br>经期提前+量或多或少+色紫有块+心烦+乳胀<br>→ <strong>丹栀逍遥散</strong></p><p><strong>阴虚血热：</strong><br>经期提前+量少色红质稠+五心烦热+颧赤<br>→ <strong>两地汤</strong></p></div><div class=ct-right><h4>关键方剂组成</h4><p><strong>清经散：</strong>丹皮地骨皮白芍熟地青蒿茯苓黄柏——清热凉血调经</p><p><strong>两地汤：</strong>生地地骨皮玄参麦冬阿胶白芍——滋阴清热调经</p><p><strong>丹栀逍遥散：</strong>逍遥散+丹皮栀子——疏肝清热</p><p><strong>举元煎：</strong>黄芪人参白术升麻甘草——益气升阳摄血</p></div></div><div class=classic-quote>《景岳全书》："先期而至者，有因脾经血燥，有因肝经郁滞，有因血热，有因虚火，各随经而治之。"<span class=src>——《景岳全书</span></div><div class=plain>月经先期就是"大姨妈老提前来"——提前7天以上且连续发生。最常见的原因是"热"（热迫血行）和"虚"（气虚不摄）。辨证的关键：量多色淡+乏力=气虚（补中益气/举元煎）+量多色紫红质稠+口渴=血热（清经散）+量少色红+五心烦热=虚热（两地汤）+伴乳胀+心烦=肝郁（丹栀逍遥散）。</p><div class=mnem><strong>口诀：</strong>先期气虚补中举+阳盛清经两地虚；肝郁丹栀逍遥散+血热与虚要分清。</div><div class=trap-box><strong>考点：</strong>1.月经先期=提前7天以上+连续2周期。2.气虚→补中益气汤/举元煎。3.阳盛血热→清经散（丹皮地骨皮白芍熟地青蒿茯苓黄柏）。4.阴虚血热→两地汤（生地地骨皮玄参麦冬阿胶白芍）。5.肝郁血热→丹栀逍遥散。6.清经散vs两地汤鉴别：清经治实热（量多质稠）+两地治虚热（量少色红）。</div></div>'},
    {id:"fk-2-1a",name:"丹栀逍遥散、清经散和两地汤的药物组成",type:"detail",
content:'<p><strong>三方药物组成对比：</strong></p><div class=compare-table><div class=ct-left><h4>丹栀逍遥散</h4><p>组成：逍遥散（柴胡当归白芍白术茯苓甘草煨姜薄荷）+丹皮+栀子</p><p>功用：疏肝清热+解郁调经<br>主治：肝郁化热之月经先期/月经过多</p></div><div class=ct-right><h4>清经散vs两地汤</h4><p><strong>清经散：</strong>丹皮地骨皮白芍熟地青蒿茯苓黄柏<br>清热凉血→阳盛血热型先期（量多质稠）</p><p><strong>两地汤：</strong>生地地骨皮玄参麦冬阿胶白芍<br>滋阴清热→阴虚血热型先期（量少色红）</p><p>两方共同点：都有地骨皮+白芍<br>区别：清经散有黄柏青蒿清热力强+两地汤有玄参麦冬阿胶滋阴力强</p></div></div><div class=classic-quote>《傅青主女科》："夫先期而来者，火气之冲，然有虚实之分。"<span class=src>——《傅青主女科》</span></div><div class=plain>这三个方是月经先期的主方。丹栀逍遥散=逍遥散(疏肝健脾)+丹皮栀子(清热凉血)——肝郁化热首选。清经散和两地汤都是傅青主女科方+区别在"虚火实火"——实热用清经散（有黄柏青蒿苦寒清热）+虚热用两地汤（有玄参麦冬阿胶滋阴清热）。</p><div class=mnem><strong>口诀：</strong>丹栀逍遥疏肝热，清经两地傅氏方；实热清经黄柏蒿，虚热两地地芍胶。</div><div class=trap-box><strong>考点：</strong>1.三方的共同病种——月经先期（血热型）。2.丹栀逍遥散——肝郁化热+丹皮栀子功在清热凉血。3.清经散vs两地汤：实热vs虚热+共有药地骨皮白芍。4.清经散独有：黄柏青蒿（清热燥湿透热）+两地汤独有：玄参麦冬阿胶（滋阴养液）。5.注意：清经散中的"熟地"并非补血主药+而是防苦寒伤阴。</div></div>'}
  ]},
  {name:"细目三：月经后期",points:[{id:"fk-2-2",name:"月经后期的定义及辨证论治",type:"apply",
content:'<p><strong>月经后期</strong>是月经周期延后7天以上+连续2个周期以上。最多延后不超过2周。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肾虚：</strong>经后延+量少色暗淡质清+腰膝酸软+头晕耳鸣<br>→ <strong>归肾丸</strong>补肾养血调经</p><p><strong>血虚：</strong>经后延+量少色淡质稀+面色苍白+头晕心悸<br>→ <strong>大补元煎</strong>补血养营调经</p><p><strong>虚寒：</strong>经后延+量少色淡质清+小腹冷痛喜按<br>→ <strong>温经汤</strong>（《金匮》）温经散寒</p><p><strong>实寒：</strong>经后延+量少色暗有块+小腹冷痛拒按<br>→ <strong>温经汤</strong>（《妇人》）温经散寒</p><p><strong>气滞：</strong>经后延+量或少+色暗有块+小腹胀痛+乳胀<br>→ <strong>乌药汤</strong>理气调经</p><p><strong>痰湿：</strong>经后延+量少+色淡质黏+体胖+胸闷呕恶<br>→ <strong>芎归二陈汤</strong>化痰燥湿调经</p></div><div class=ct-right><h4>温经汤——两个版本</h4><p><strong>《金匮要略》温经汤（虚寒）：</strong><br>吴茱萸当归川芎白芍人参桂枝阿胶丹皮生姜甘草半夏麦冬</p><p><strong>《妇人大全良方》温经汤（实寒）：</strong><br>当归川芎芍药肉桂牡丹皮莪术人参甘草牛膝</p><p>两者都可治月经后期寒证+前者偏补虚温经+后者偏化瘀散寒</p></div></div><div class=classic-quote>《景岳全书》："后期而至者，有因寒凝，有因血少，有因气郁，有因痰阻，不可概以寒论。"<span class=src>——《景岳全书》</span></div><div class=plain>月经后期就是大姨妈"迟到"了。最常见原因——"寒"（着凉了+血冻住了走不动）和"虚"（血不够+没东西来）。记住"后期六型"口诀：肾虚归+血虚大+实寒温经+虚寒温经+气滞乌药+痰湿芎归二陈。两个"温经汤"是考试必挖的坑——《金匮》的是虚寒（补虚温经）+《妇人》的是实寒（化瘀散寒）。</p><div class=mnem><strong>口诀：</strong>后期六型肾归血大补+寒分虚实两温经；气滞乌药痰二陈+六型分清调经平。</div><div class=trap-box><strong>高频考点：</strong>1.月经后期=延后7天以上+连续2周期。2.虚寒→金匮温经汤（偏补虚）vs实寒→妇人温经汤（偏化瘀）——区分必考！3.血虚→大补元煎（人参山药熟地杜仲当归山萸枸杞甘草）。4.肾虚→归肾丸（菟丝子杜仲枸杞山萸当归熟地山药茯苓）。5.气滞→乌药汤（乌药香附木香当归甘草）。6.痰湿→芎归二陈汤（川芎当归+二陈汤）。</div></div>'},
    {id:"fk-2-2a",name:"温经汤的药物组成",type:"detail",
content:'<p><strong>两个温经汤的完整组成：</strong></p><div class=compare-table><div class=ct-left><h4>《金匮要略》温经汤</h4><p><strong>组成：</strong>吴茱萸+当归+川芎+白芍+人参+桂枝+阿胶+丹皮+生姜+甘草+半夏+麦冬</p><p><strong>功用：</strong>温经散寒+养血祛瘀<br><strong>主治：</strong>冲任虚寒+瘀血阻滞之月经后期+痛经+崩漏</p><p>特点：温补并用+攻补兼施——既温经又补血又化瘀</p></div><div class=ct-right><h4>《妇人大全良方》温经汤</h4><p><strong>组成：</strong>当归+川芎+芍药+肉桂+牡丹皮+莪术+人参+甘草+牛膝</p><p><strong>功用：</strong>温经散寒+化瘀通经<br><strong>主治：</strong>寒凝血瘀之月经后期+痛经+月经过少</p><p>特点：偏于化瘀通经+肉桂温散寒邪力量强</p></div></div><div class=classic-quote>《金匮要略》温经汤条文："问曰：妇人年五十所，病下利数十日不止……曾经半产，瘀血在少腹不去。何以知之？其证唇口干燥，故知之。当以温经汤主之。"<span class=src>——《金匮要略》</span></div><div class=plain>温经汤有两个+但考试一般不写全名只写"温经汤"——要分清是哪个！金匮温经汤12味药：吴萸归芎芍+参桂阿丹+生姜草夏冬。妇人温经汤9味药：归芎芍+肉桂丹+莪术参草牛膝。金匮的方更全面（温补消三法俱全）+妇人的更偏攻（肉桂莪术化瘀力强）。如果题目说"虚寒"用温经汤=金匮+如果只说"寒凝"=妇人。</p><div class=mnem><strong>口诀：</strong>金匮温经吴萸桂，归芎芍参丹姜夏；妇人温经肉桂莪，归芎芍膝丹参草。</div></div>'}
  ]},
  {name:"细目四：月经先后无定期",points:[{id:"fk-2-3",name:"月经先后无定期的定义及辨证论治",type:"apply",
content:'<p><strong>月经先后无定期</strong>是月经周期不定+时提前时延后7天以上+连续3个周期。又称"经乱"。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肝郁：</strong>经来先后不定+量或多或少+色紫有块+经行不畅+胸胁乳房胀痛+精神抑郁+太息<br>→ <strong>逍遥散</strong>疏肝理气调经</p><p><strong>肾虚：</strong>经来先后不定+量少色淡质清+腰骶酸痛+头晕耳鸣<br>→ <strong>固阴煎</strong>补肾调经</p></div><div class=ct-right><h4>病机要点</h4><p><strong>肝郁：</strong>肝失疏泄→气机逆乱→血海不宁→经期错乱<br>偏于肝郁化火→先期+偏于气滞血瘀→后期</p><p><strong>肾虚：</strong>肾气不足→封藏失职→冲任失调→经期紊乱</p><p>注意：两型可互相转化转化为肝肾同病</p></div></div><div class=classic-quote>《景岳全书》："妇人经乱，或因于肝郁，或因于肾虚，总由冲任不调所致。"<span class=src>——《景岳全书》</span></div><div class=plain>月经先后无定期就是"大姨妈要么早来要么晚来没个准"。最常见原因两个：情绪（肝郁）和老了（肾虚）。肝郁的偏于"气"（乳胀+情绪）+肾虚的偏于"虚"（腰酸+头晕）。肝郁用逍遥散（疏肝）+肾虚用固阴煎（补肾）。如果既有肝郁又有肾虚→肝肾同治。</p><div class=mnem><strong>口诀：</strong>先后无定经乱名，肝郁逍遥肾固阴；肝气逆乱血海扰，肾虚封藏失职成。</div><div class=trap-box><strong>考点：</strong>1.月经先后无定期=提前+延后交替>3周期。2.肝郁→逍遥散疏肝理气。3.肾虚→固阴煎（人参熟地山药山萸远志菟丝子五味子炙甘草）补肾调经。4.肝郁与情绪变化密切相关+肾虚与腰酸头晕耳鸣相关。5.注意与崩漏的鉴别——经乱周期紊乱但经量正常+崩漏是经量异常（暴下不止或淋漓）。</div></div>'}
  ]},
  {name:"细目五：月经过多",points:[{id:"fk-2-4",name:"月经过多的定义及辨证论治",type:"apply",
content:'<p><strong>月经过多</strong>是月经量明显增多（>80ml）+周期+经期正常。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>气虚：</strong>量多色淡质稀+神疲气短+小腹空坠<br>→ <strong>举元煎</strong>益气升阳摄血</p><p><strong>血热：</strong>量多色鲜红质稠+口渴+尿黄+便结<br>→ <strong>保阴煎</strong>清热凉血止血</p><p><strong>血瘀：</strong>量多色紫暗有块+小腹刺痛+块下痛减<br>→ <strong>失笑散</strong>活血化瘀止血</p></div><div class=ct-right><h4>关键方剂</h4><p><strong>举元煎：</strong>黄芪人参白术升麻甘草——益气升阳+摄血调经</p><p><strong>保阴煎：</strong>生地熟地白芍山药续断黄芩黄柏甘草——清热凉血+止血调经</p><p><strong>失笑散：</strong>蒲黄五灵脂——化瘀止血+通中有止</p></div></div><div class=classic-quote>《医宗金鉴》："经水过多，清稀淡红，乃气虚也；若稠黏色深，乃血热血瘀也。"<span class=src>——《医宗金鉴》</span></div><div class=plain>月经过多就是"量太多"——正常50-80ml+超过80ml算过多。三型辨治：气虚（色淡质稀+气短）→举元煎固摄+血热（色鲜红质稠+口渴）→保阴煎清热+血瘀（色素暗有块+刺痛）→失笑散化瘀。注意月经过多和崩漏的区别：崩漏是"周期也乱+量也乱"+月经过多是"周期正常但量多"。</p><div class=mnem><strong>口诀：</strong>过多种类三型分，气虚举元热血保阴；血瘀失笑通且止，经量增多要调经。</div><div class=trap-box><strong>考点：</strong>1.月经过多vs崩漏——周期正常vs周期紊乱。2.气虚→举元煎（芪参术麻甘）——益气升阳摄血。3.血热→保阴煎（生地熟地白芍山药续断芩柏草）——清热凉血。4.血瘀→失笑散（蒲黄五灵脂）——化瘀止血。5.久量大可致贫血+注意补血。</div></div>'},
    {id:"fk-2-4a",name:"举元煎及保阴煎的药物组成",type:"detail",
content:'<p><strong>举元煎：</strong>黄芪+人参+白术+升麻+甘草。功用：益气升阳+摄血调经。主治：气虚型月经过多+崩漏。</p><p><strong>保阴煎：</strong>生地+熟地+白芍+山药+续断+黄芩+黄柏+甘草。功用：清热凉血+止血调经。主治：血热型月经过多+崩漏（张景岳方）。</p><div class=compare-table><div class=ct-left><h4>举元煎（补气升阳）</h4><p><strong>组方思路：</strong>补中益气汤去当归陈皮柴胡+保留芪参术甘+重用升麻升阳举陷</p><p>黄芪+人参+白术→益气摄血<br>升麻→升阳举陷</p></div><div class=ct-right><h4>保阴煎（清热凉血）</h4><p><strong>组方思路：</strong>生地熟地白芍养阴血+黄芩黄柏清热+山药续断固肾</p><p>生熟二地+白芍→滋阴养血<br>黄芩黄柏→清热止血</p></div></div><div class=classic-quote>《景岳全书》："举元煎治气虚下陷+血崩血脱+亡阳垂危等证。"<span class=src>——《景岳全书》</span></div><div class=plain>举元煎=补中益气汤"瘦身版"——去掉当归陈皮柴胡这些走窜之品+专门用黄芪人参白术补气固摄+升麻升提阳气。保阴煎=生地熟地白芍养阴+黄芩黄柏清热——适用于血热型的月经过多。</p></div>'}
  ]},
  {name:"细目六：月经过少",points:[{id:"fk-2-5",name:"月经过少的定义及辨证论治",type:"apply",
content:'<p><strong>月经过少</strong>是月经量明显减少（<20ml）或经期缩短<2天+周期正常。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肾虚：</strong>量少色暗淡质清+腰膝酸软+头晕耳鸣+夜尿多<br>→ <strong>归肾丸</strong>补肾养血调经</p><p><strong>血虚：</strong>量少色淡质稀+面色萎黄+头晕心悸+唇甲苍白<br>→ <strong>滋血汤</strong>补血调经</p><p><strong>痰湿：</strong>量少色淡质黏+体胖胸闷+呕恶痰多+带多<br>→ <strong>苍附导痰丸</strong>化痰燥湿调经</p><p><strong>血瘀：</strong>量少色紫暗有块+小腹刺痛+块下痛减<br>→ <strong>桃红四物汤</strong>活血化瘀调经</p></div><div class=ct-right><h4>关键方剂</h4><p><strong>归肾丸：</strong>菟丝子杜仲枸杞山萸当归熟地山药茯苓</p><p><strong>滋血汤：</strong>人参山药茯苓当归川芎白芍熟地</p><p><strong>苍附导痰丸：</strong>苍术香附陈皮茯苓半夏南星枳壳生姜甘草</p></div></div><div class=classic-quote>《医宗金鉴》："经水过少，色淡者虚也+色紫者热也+有块者瘀也+黏稠者痰也。"<span class=src>——《医宗金鉴》</span></div><div class=plain>月经过少就是"量太少"——<20ml（连卫生巾都用不上几片）。原因不外乎"虚"和"瘀"：虚的两个（肾虚归肾丸+血虚滋血汤）+实的两个（痰湿苍附导痰+血瘀桃红四物）。注意虚实错杂可以并见——比如肾虚夹瘀+要分清主次。</p><div class=mnem><strong>口诀：</strong>过少四型肾血痰瘀，归肾滋血苍附桃红。</div><div class=trap-box><strong>考点：</strong>1.月经过少vs经期缩短vs闭经——三者量逐渐减少可互相转化。2.肾虚→归肾丸（菟丝杜仲枸杞山萸归地药苓）。3.血虚→滋血汤（参苓归芎芍地+山药）。4.痰湿→苍附导痰丸（苍术香附陈皮苓夏南星枳壳草）。5.血瘀→桃红四物汤。6.注意排除"妊娠停经"和"暗产"（早早孕流产）。</div></div>'},
    {id:"fk-2-5a",name:"归肾丸和苍附导痰丸的药物组成",type:"detail",
content:'<p><strong>归肾丸：</strong>菟丝子+杜仲+枸杞子+山萸肉+当归+熟地+山药+茯苓。功用：补肾养血+调经。主治：肾虚月经过少+月经后期+闭经。</p><p><strong>苍附导痰丸：</strong>苍术+香附+陈皮+茯苓+半夏+南星+枳壳+生姜+甘草。功用：化痰燥湿+调经。主治：痰湿型月经过少+闭经+多囊卵巢综合征。</p><div class=classic-quote>《叶天士女科》："肥人经水来少者+责其痰碍经隧也。"<span class=src>——《叶天士女科》</span></div><div class=plain>归肾丸——"归"指当归+归入肾经+以补肾为主。八味药：四补（菟丝杜仲枸杞山萸）+四养（归地药苓）。苍附导痰丸——"苍"是苍术+"附"是香附+"导痰"就是化痰。肥胖+痰多+月经少+多囊卵巢的女性常用此方。</p></div>'}
  ]},
  {name:"细目七：经间期出血",points:[{id:"fk-2-6",name:"经间期出血的定义及辨证论治",type:"apply",
content:'<p><strong>经间期出血</strong>是两次月经中间（氤氲期/排卵期）出现周期性少量子宫出血。时间在月经周期第12-16天。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肾阴虚：</strong>经间期出血+量少色红无块+腰酸+头晕+五心烦热<br>→ <strong>加减一阴煎</strong>滋阴清热+止血</p><p><strong>湿热：</strong>经间期出血+色深红质稠+带下量多色黄+苔黄腻<br>→ <strong>清肝止淋汤</strong>去阿胶加茯苓炒栀子</p><p><strong>血瘀：</strong>经间期出血+色紫暗有块+小腹刺痛+舌紫<br>→ <strong>逐瘀止血汤</strong>活血化瘀+止血</p></div><div class=ct-right><h4>病机概要</h4><p>氤氲期（排卵期）—肾阴充实→阳气内动→阴精转化为阳气</p><p>若肾阴不足+湿热内蕴+瘀血内阻→阳气动时扰动血海→出血</p><p>注意：出血量一般不多+持续1-3天+可伴下腹微痛</p></div></div><div class=classic-quote>《女科准绳》："天地生物+必有氤氲之时+万物化生+必有乐育之候……此的候也。"<span class=src>——《女科准绳》</span></div><div class=plain>经间期出血就是排卵期出血——月经干净后一周左右又出点血。这是"氤氲期"（肾阴转阳的节律点）阳气内动太过+扰动血海所致。量少+持续1-3天+一般不需紧张。如果反复出现需治疗——"加减一阴煎"（生地白芍麦冬熟地知母地骨皮甘草）是常用方。</p><div class=mnem><strong>口诀：</strong>经间出血氤氲期，肾阴不足阳动急；加减一阴清虚热，湿热清肝逐瘀宜。</div><div class=trap-box><strong>考点：</strong>1.经间期=排卵期=月经周期第12-16天。2.病机：氤氲之时阳气内动+扰动血海。3.肾阴虚→加减一阴煎（生地白芍麦冬熟地知母地骨皮）。4.湿热→清肝止淋汤去阿胶加茯苓炒栀子。5.血瘀→逐瘀止血汤（大黄生地当归尾赤芍丹皮枳壳桃仁龟板）。</div></div>'}
  ]},
  {name:"细目八：崩漏",points:[{id:"fk-2-7",name:"崩漏的定义、治崩大法及辨证论治",type:"apply",
content:'<p><strong>崩漏</strong>是经血非时暴下不止（崩）或淋漓不尽（漏）。崩为漏之甚+漏为崩之渐+两者可互相转化。常见于无排卵性异常子宫出血。</p><div class=compare-table><div class=ct-left><h4>治崩三法</h4><p><strong>塞流：</strong>急则治标——止血<br>暴崩之际+先止血防脱<br>方如独参汤+生脉散</p><p><strong>澄源：</strong>缓则治本——求因<br>血止后辨证求因+针对病机治疗<br>热者清之+瘀者化之+虚者补之</p><p><strong>复旧：</strong>善后调理——固本<br>调理月经周期+恢复肾-天癸-冲任-胞宫轴<br>补肾+扶脾+疏肝</p></div><div class=ct-right><h4>辨证分型</h4><p><strong>血热：</strong>量多色深红质稠+烦热口渴<br>→清热固经汤</p><p><strong>肾虚：</strong>经乱无期+量多或少+腰膝酸软<br>→肾阳虚右归丸+肾阴虚左归丸合二至丸</p><p><strong>脾虚：</strong>量多色淡+神疲乏力+食少便溏<br>→固本止崩汤</p><p><strong>血瘀：</strong>量多色紫暗有块+腹痛块下痛减<br>→逐瘀止血汤/桃红四物汤</p></div></div><div class=classic-quote>《女科经纶》："暴崩下血+当用甘温之品补益气血+兼以收涩+以治其标；血止之后+当求其因而治之。"<span class=src>——《女科经纶》</span></div><div class=plain>崩漏就是大出血（崩）或淋漓不尽（漏）。治崩三法是妇科必考内容——"塞流"(止血治标)+"澄源"(求因治本)+"复旧"(调理善后)。紧急情况先塞流（止血救命）+血止后澄源（找出病因治疗）+最后复旧（调理周期防复发）。注意塞流不是单纯用止血药——要配合病机（热者凉血止血+瘀者化瘀止血+虚者补气摄血）。</p><div class=mnem><strong>口诀：</strong>崩漏非时经乱行，塞流澄源复旧名；血热清经肾归丸，脾虚固本瘀逐停。</div><div class=trap-box><strong>高频考点：</strong>1.治崩三法——塞流（止血）+澄源（求因）+复旧（善后）——必考！顺序不可颠倒。2.血热→清热固经汤（地骨皮生地龟板牡蛎阿胶栀子地榆黄芩藕节棕榈炭甘草）。3.脾虚→固本止崩汤（人参黄芪白术熟地当归黑姜）。4.肾阳虚→右归丸+肾阴虚→左归丸合二至丸（女贞子旱莲草）。5.血瘀→逐瘀止血汤。6.崩漏日久+急则独参汤/生脉散益气固脱。</div></div>'},
    {id:"fk-2-7a",name:"清热固经汤的药物组成",type:"detail",
content:'<p><strong>清热固经汤：</strong>地骨皮+生地+龟板+牡蛎+阿胶+栀子+地榆+黄芩+藕节+棕榈炭+甘草。</p><p>功用：清热凉血+固冲止血。主治：血热型崩漏（量多色深红+烦热口渴）。</p><div class=compare-table><div class=ct-left><h4>组方分析</h4><p>清热：地骨皮+黄芩+栀子<br>养阴：生地+龟板+阿胶<br>固涩：牡蛎+地榆+棕榈炭<br>化瘀止血：藕节</p></div><div class=ct-right><h4>考法提示</h4><p>清热固经汤=清热（地骨芩栀）+固经（龟牡胶）+止血（地榆棕榈藕节）+甘草调和</p><p>记法：地骨生地龟板牡，阿胶栀芩榆藕棕</p></div></div><div class=classic-quote>《简明中医妇科学》："清热固经汤治血热崩漏+色深红量多+烦热口渴。"<span class=src>——《简明中医妇科学》</span></div></div>'}
  ]},
  {name:"细目九：闭经",points:[{id:"fk-2-8",name:"闭经的定义及病因病机（虚实不同病机要点）",type:"concept",
content:'<p><strong>闭经</strong>分为原发性闭经（年满16岁月经尚未来潮）和继发性闭经（已有月经+停闭6个月以上或按月停闭3个周期以上）。</p><div class=compare-table><div class=ct-left><h4>虚性闭经</h4><p><strong>肾虚：</strong>肾精亏虚→天癸不足→无血可下<br>年幼发育迟缓+或房劳多产耗精</p><p><strong>血虚：</strong>气血不足→血海空虚→无血可下<br>大病久病+失血过多+营养不良</p><p><strong>阴虚血燥：</strong>阴虚生热+热灼血枯→无血可下<br>劳损阴虚+痨瘵（结核病）</p></div><div class=ct-right><h4>实性闭经</h4><p><strong>气滞血瘀：</strong>情志不遂+肝气郁结→血瘀不行<br>精神抑郁+或忿怒伤肝</p><p><strong>痰湿阻滞：</strong>肥胖多痰+脾虚湿盛→痰阻胞宫<br>体胖+痰多+多囊卵巢</p><p><strong>寒凝血瘀：</strong>感受寒邪+血为寒凝→经血不行<br>经期产后+贪凉饮冷</p></div></div><div class=classic-quote>《景岳全书》："血枯之与血隔+本自不同+盖枯者竭也+隔者阻也。"<span class=src>——《景岳全书》</span></div><div class=plain>闭经就是该来不来。关键是分清"虚"还是"实"——虚证是"没有东西可以来"（血枯）+实证是"有东西但下不来"（血隔）。"血枯"（虚）—补之通之+"血隔"（实）—行之通之。张景岳说"枯者竭也+隔者阻也"——一句话道出闭经的虚实本质。</p><div class=mnem><strong>口诀：</strong>闭经虚实要分清，血枯血隔张景岳；肾虚血枯滋阴血+实热血瘀寒痰行。</div><div class=trap-box><strong>考点：</strong>1.原发性闭经=16岁未初潮+继发性=停闭6月/3周期。2.虚性（血枯）——肾虚+血虚+阴虚血燥。3.实性（血隔）——气滞血瘀+痰湿阻滞+寒凝血瘀。4."枯者竭也+隔者阻也"——景岳全书——闭经虚实总纲。5.排除生理性闭经（妊娠+哺乳+绝经）。6.注意多囊卵巢综合征是闭经常见原因（痰湿型）。</div></div>'},
    {id:"fk-2-8a",name:"闭经的辨证论治",type:"apply",
content:'<p><strong>闭经六型辨治：</strong></p><div class=compare-table><div class=ct-left><h4>虚证三型（血枯）</h4><p><strong>肾虚：</strong>年逾16未行+或初潮迟+腰酸+头晕<br>→ <strong>归肾丸</strong>补肾养血</p><p><strong>血虚：</strong>经停数月+面色萎黄+头晕心悸+唇甲淡<br>→ <strong>人参养荣汤</strong>补气养血</p><p><strong>阴虚血燥：</strong>经闭+五心烦热+颧红+干咳+潮热<br>→ <strong>加减一阴煎</strong>养阴清热</p></div><div class=ct-right><h4>实证三型（血隔）</h4><p><strong>气滞血瘀：</strong>经闭+精神抑郁+胸胁胀满+少腹胀痛<br>→ <strong>血府逐瘀汤</strong>理气活血</p><p><strong>痰湿阻滞：</strong>经闭+肥胖+多痰+胸闷呕恶+带多<br>→ <strong>苍附导痰丸</strong>化痰除湿</p><p><strong>寒凝血瘀：</strong>经闭+小腹冷痛+形寒肢冷+带下清冷<br>→ <strong>温经汤</strong>（妇人）温经散寒</p></div></div><div class=classic-quote>《景岳全书》："欲以通之+无如补之+血既枯矣+而复通之+则枯者愈枯+"<span class=src>——《景岳全书》</span></div><div class=plain>闭经六型三条原则：虚证千万不能乱用破血通经药——"越通越枯"！就像河床没水了+你光挖河床（化瘀通经）是没用的+得先引水来（补气血养阴）。实证才能化瘀通经。张景岳这句话是经典："欲以通之+无如补之"——想要通经不如先补。</p><div class=mnem><strong>口诀：</strong>虚闭归肾养荣一阴煎，实闭血府逐瘀苍附温经汤。</div><div class=trap-box><strong>高频考点：</strong>1.虚闭（血枯）不可妄用攻破通经——"欲以通之+无如补之"。2.肾虚→归肾丸+血虚→人参养荣汤（人参白术茯苓甘草当归白芍熟地肉桂黄芪五味远志陈皮姜枣）。3.阴虚血燥→加减一阴煎（生地白芍麦冬熟地知母地骨皮）。4.气滞血瘀→血府逐瘀汤（桃红四物+四逆散+牛膝桔梗）。5.痰湿→苍附导痰丸。6.寒凝血瘀→妇人良方温经汤。</div></div>'}
  ]},
  {name:"细目十：痛经",points:[{id:"fk-2-9",name:"痛经的定义及辨证论治",type:"apply",
content:'<p><strong>痛经</strong>是经期或经行前后出现周期性小腹疼痛（可放射到腰骶部+可伴恶心呕吐+冷汗）。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>气滞血瘀：</strong>经前/经期小腹胀痛+行经不畅+血块下痛减+乳胀<br>→ <strong>膈下逐瘀汤</strong></p><p><strong>寒凝血瘀：</strong>经前/经期小腹冷痛+得热减轻+经色暗有块+畏寒<br>→ <strong>少腹逐瘀汤</strong></p><p><strong>湿热瘀阻：</strong>经前/经期小腹灼痛+经色暗红质稠+带下黄稠<br>→ <strong>清热调血汤</strong></p><p><strong>气血虚弱：</strong>经后/经期小腹隐痛喜按+月经量少色淡+神疲<br>→ <strong>圣愈汤</strong></p><p><strong>肾气亏损：</strong>经后小腹空坠作痛+腰骶酸痛+头晕<br>→ <strong>益肾调经汤</strong></p></div><div class=ct-right><h4>痛经的"通与不通"</h4><p><strong>不通则痛：</strong><br>气滞+血瘀+寒凝+湿热——实证<br>治法：通调气血——"通则不痛"</p><p><strong>不荣则痛：</strong><br>气血虚+肾虚——虚证<br>治法：补益气血——"荣则不痛"</p></div></div><div class=classic-quote>《景岳全书》："经行腹痛+证有虚实。实者或因寒滞+或因血滞+或因气滞+或因热滞；虚者有因血虚+有因气虚。"<span class=src>——《景岳全书》</span></div><div class=plain>痛经就是"来大姨妈时肚子痛"。中医讲"不通则痛"（实证：气滞血瘀寒凝湿热堵住了）+"不荣则痛"（虚证：气血肾虚不够营养了）。五种证型中考试最常考的是"寒凝血瘀→少腹逐瘀汤"（小腹冷痛得热减轻+用少腹逐瘀汤温经散寒化瘀止痛）。</p><div class=mnem><strong>口诀：</strong>痛经五型气滞膈下寒少腹+湿热清热调血汤+气血圣愈肾益调。</div><div class=trap-box><strong>高频考点：</strong>1.气滞血瘀→膈下逐瘀汤（桃红四物+枳壳香附乌药延胡丹皮甘草）。2.寒凝血瘀→少腹逐瘀汤（小茴香干姜延胡没药归芎赤芍蒲黄五灵脂）——小腹冷痛得热减。3.湿热瘀阻→清热调血汤（丹皮黄连生地当归白芍川芎桃仁红花延胡莪术香附）。4.气血虚弱→圣愈汤（四物+黄芪人参）。5.肾气亏损→益肾调经汤（巴戟杜仲续断乌药艾叶当归熟地白芍益母草）。6.经前/经期痛多实证+经后痛多虚证。</div></div>'}
  ]},
  {name:"细目十一：经行泄泻",points:[{id:"fk-2-10",name:"经行泄泻的定义及辨证论治",type:"apply",
content:'<p><strong>经行泄泻</strong>是月经前/经期出现大便泄泻+经后自止+呈周期性发作。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>脾虚：</strong>经行泄泻+食少+脘腹胀满+神疲+肢软<br>→ <strong>参苓白术散</strong>健脾益气+化湿止泻</p><p><strong>肾虚：</strong>经行泄泻+晨起即泻（五更泻）+腰膝酸软+畏寒肢冷+头晕<br>→ <strong>健固汤</strong>合<strong>四神丸</strong>温肾健脾+固涩止泻</p></div><div class=ct-right><h4>病机要点</h4><p>经期气血下注冲任→脾肾之气相对不足</p><p>脾虚→运化失司+水湿下注→泄泻</p><p>肾虚→命门火衰+不能暖土+脾失健运→泄泻</p><p>注意：经净后气血恢复→泄泻自止</p></div></div><div class=classic-quote>《妇人大全良方》："经行泄泻+属于脾虚湿盛+脾统血而主运化+经行之际+脾气益虚+湿气内动。"<span class=src>——《妇人大全良方》</span></div><div class=plain>经行泄泻就是"一来月经就拉肚子"。原因很简单：来月经的时候气血都往子宫跑了+脾胃的气血就少了（气血下注冲任）→脾胃变弱+消化不好+水湿多了→拉肚子。脾虚的用参苓白术散（健脾）+肾虚的用健固汤合四神丸（补肾固涩）。</p><div class=mnem><strong>口诀：</strong>经行泄泻脾肾虚，脾参苓白术肾健固四神。</div><div class=trap-box><strong>考点：</strong>1.脾虚→参苓白术散（参术苓草山药扁豆莲肉砂仁薏仁桔梗）。2.肾虚→健固汤合四神丸（健固=人参白术茯苓薏仁巴戟+四神=补骨脂吴萸肉豆蔻五味子）。3.经行泄泻与平常腹泻鉴别——仅在经期出现。4.脾虚泄泻与肾虚泄泻鉴别：脾虚→脘腹胀+食少乏力+肾虚→五更泻+腰膝酸冷。5.经行泄泻可伴随经行水肿（同一病机）。</div></div>'}
  ]},
  {name:"细目十二：经行浮肿",points:[{id:"fk-2-11",name:"经行浮肿的定义及辨证论治",type:"apply",
content:'<p><strong>经行浮肿</strong>是月经前/经期出现头面四肢浮肿+经后自消+周期性发作。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>脾肾阳虚：</strong>经行面浮肢肿+按之凹陷+腹胀+纳少+腰膝酸冷+大便溏<br>→ <strong>苓桂术甘汤</strong>合<strong>真武汤</strong></p><p><strong>气滞血瘀：</strong>经行肢体肿胀+皮色不变+按之随手而起+胸胁胀满+月经不畅<br>→ <strong>八物汤</strong></p></div><div class=ct-right><h4>病机要点</h4><p>脾肾阳虚—水湿运化不利→溢于肌肤—浮肿（按之凹陷不起）</p><p>气滞血瘀—经脉不通→气滞水停—肿胀（按之随手而起）</p><p>鉴别要点：凹陷性水肿vs非凹陷性肿胀</p></div></div><div class=classic-quote>《女科经纶》："经行浮肿+因于脾肾阳虚+不能制水+水气泛溢。"<span class=src>——《女科经纶》</span></div><div class=plain>一来月经就浮肿——原因两个：虚（脾肾阳虚+水排不出去→凹陷性水肿）或实（气滞血瘀+水走不动→非凹陷性肿胀）。两者区别：按下去一个坑的是虚（脾肾阳）+按下去弹起来的是实（气滞瘀）。</p><div class=mnem><strong>口诀：</strong>经行浮肿阳虚实气，阳虚苓桂真武+气滞八物可行。</div><div class=trap-box><strong>考点：</strong>1.脾肾阳虚→苓桂术甘汤合真武汤（苓桂术甘+附子白术白芍生姜）。2.气滞血瘀→八物汤（四物+四君子——即八珍汤去参+加延胡索川楝子？注意不同）。3.凹陷性水肿=阳虚+非凹陷性=气滞。4.与心肾疾病引起的水肿鉴别——仅限于经期发作+经后自消。</div></div>'}
  ]},
  {name:"细目十三：经行吐衄",points:[{id:"fk-2-12",name:"经行吐衄的定义及辨证论治",type:"apply",
content:'<p><strong>经行吐衄</strong>是月经前/经期出现有规律的吐血或衄血（鼻出血）+经后自止。俗称"倒经"或"逆经"。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肝经郁火：</strong>经前/经期吐血衄血+量多色鲜红+心烦易怒+两胁胀痛+口苦咽干+头晕耳鸣<br>→ <strong>清肝引经汤</strong>清肝泻火+降逆止血</p><p><strong>肺肾阴虚：</strong>经前/经期吐血衄血+量少色暗红+平素咳嗽痰少+手足心热+颧赤<br>→ <strong>顺经汤</strong>滋阴润肺+凉血止血</p></div><div class=ct-right><h4>关键方剂</h4><p><strong>清肝引经汤：</strong>当归白芍生地丹皮栀子黄芩川楝子茜草白茅根牛膝甘草</p><p><strong>顺经汤：</strong>当归熟地白芍丹皮茯苓沙参黑芥穗</p><p>两方共同：当归白芍丹皮+引血下行</p></div></div><div class=classic-quote>《医宗金鉴》："逆行上冲致吐衄+宜用顺经汤。"<span class=src>——《医宗金鉴》</span></div><div class=plain>经行吐衄就是"倒经"——来月经时月经不从下面出来+反而从上面（鼻子、嘴巴）出来。病机是"血热上逆+血随气火上冲"——肝经郁火（火热往上窜）或肺肾阴虚（虚火上炎）。治疗关键是"引血下行"——牛膝是引血下行的要药+两个方里都有。</p><div class=mnem><strong>口诀：</strong>倒经吐衄热上行，肝火清肝引经清；肺肾阴虚拟顺经汤，牛膝引下妙无穷。</div><div class=trap-box><strong>考点：</strong>1.肝经郁火→清肝引经汤（归芍地丹栀芩楝茜草茅膝草）。2.肺肾阴虚→顺经汤（归地芍丹苓沙芥穗）。3.两方均用牛膝引血下行+当归白芍养肝血。4.与鼻衄（鼻出血）鉴别——仅经期发作+经后自止。5.严重者需中西医结合治疗排除子宫内膜异位症（鼻部异位灶）。</div></div>'},
    {id:"fk-2-12a",name:"顺经汤的药物组成",type:"detail",
content:'<p><strong>顺经汤（傅青主女科）：</strong>当归+熟地+白芍+丹皮+茯苓+沙参+黑芥穗。</p><p>功用：滋肾润肺+凉血止血。主治：经行吐衄（肺肾阴虚型）。</p><div class=compare-table><div class=ct-left><h4>组方思路</h4><p>当归+熟地+白芍→养肝肾之阴<br>丹皮+黑芥穗→凉血止血<br>沙参→润肺清肺<br>茯苓→宁心安神</p></div><div class=ct-right><h4>考法提示</h4><p>组成七味药——归熟芍丹茯沙芥</p><p>记忆法：顺经汤"顺"着把血"引"下去——而不直接用苦寒降逆（不同清肝引经汤的苦寒直折）。</p></div></div><div class=classic-quote>《傅青主女科》："顺经汤治经逆吐血+此方顺气而不逆+平肝而不犯+补血而不滞。"<span class=src>——《傅青主女科》</span></div></div>'}
  ]},
  {name:"细目十四：绝经前后诸证",points:[{id:"fk-2-13",name:"绝经前后诸证的定义及辨证论治",type:"apply",
content:'<p><strong>绝经前后诸证</strong>（围绝经期综合征）是女性在绝经前后（45-55岁）出现的与绝经相关的症状：月经紊乱+烘热汗出+烦躁易怒+失眠+心悸+腰膝酸软等。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肾阴虚：</strong>烘热汗出+五心烦热+腰膝酸软+头晕耳鸣+失眠多梦+皮肤干燥<br>→ <strong>左归丸</strong>合<strong>二至丸</strong></p><p><strong>肾阳虚：</strong>腰膝冷痛+畏寒肢冷+精神萎靡+面色晦暗+夜尿多<br>→ <strong>右归丸</strong></p><p><strong>肾阴阳两虚：</strong>上热下寒+烘热汗出+腰膝冷痛+头晕耳鸣+畏寒怕冷<br>→ <strong>二仙汤</strong>合<strong>二至丸</strong></p></div><div class=ct-right><h4>病机与调护</h4><p><strong>根本病机：</strong>肾气渐衰+天癸将竭+阴阳平衡失调</p><p><strong>经典方——二仙汤：</strong><br>仙茅+仙灵脾+巴戟天+当归+知母+黄柏<br>特点：温肾阳+滋肾阴+泻虚火——阴阳双补</p><p><strong>调护：</strong>心理疏导+适当锻炼+植物雌激素</p></div></div><div class=classic-quote>《素问·上古天真论》："七七任脉虚+太冲脉衰少+天癸竭+地道不通+故形坏而无子也。"<span class=src>——《黄帝内经》</span></div><div class=plain>绝经前后诸证就是"更年期综合征"——女性45-55岁+肾气亏了+天癸没了+激素水平波动。核心原因是"肾虚"（阴损及阳+阴阳两虚）+治疗以补肾为主。左归丸补肾阴（六味减三泻+加龟牛枸菟鹿胶）+右归丸补肾阳（左归加肉桂附子杜仲）。二仙汤是更年期综合征的特效方（仙茅仙灵脾巴戟+知柏+当归）——温阳不燥+滋阴不腻。</p><div class=mnem><strong>口诀：</strong>绝经前后肾虚根，阴虚左归阳虚右；阴阳两虚二仙汤+知柏归仙巴戟仙。</div><div class=trap-box><strong>高频考点：</strong>1.肾阴虚→左归丸合二至丸（左归：熟地山药山萸枸杞菟丝鹿胶龟胶牛膝+二至：女贞旱莲）。2.肾阳虚→右归丸（左归+肉桂附子杜仲）。3.阴阳两虚→二仙汤（仙茅仙灵脾巴戟当归知母黄柏）。4.二仙汤是更年期综合征代表方+温肾阳+滋肾阴+泻相火。5.《素问》"七七"原文是论述绝经生理的经典必考。6.症状多样：烘热汗出最典型+伴随情志症状。</div></div>'}
  ]},
  {name:"细目十五：经断复来",points:[{id:"fk-2-14",name:"经断复来的定义及辨证论治",type:"apply",
content:'<p><strong>经断复来</strong>是绝经期妇女月经停止1年以上又出现阴道出血。又称"老妇血崩"。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>血热：</strong>经断复来+量多色鲜红+质稠+口干+烦热<br>→ <strong>益阴煎</strong>或<strong>知柏地黄丸</strong></p><p><strong>脾虚肝郁：</strong>经断复来+量少色淡+气短+食少+胁胀+心烦<br>→ <strong>安老汤</strong></p><p><strong>湿毒瘀结：</strong>经断复来+量少+色杂（红白相间）+气味臭秽+小腹作痛<br>→ <strong>萆薢渗湿汤</strong>合<strong>桂枝茯苓丸</strong></p></div><div class=ct-right><h4>重要警示</h4><p><strong>经断复来——需排除恶性肿瘤！</strong></p><p>绝经后出血首要排除：<br>·子宫内膜癌+宫颈癌+卵巢恶性肿瘤</p><p>必须做：<br>·妇科检查+B超+诊刮/宫腔镜+宫颈筛查</p><p>排除恶性后+方可按中医辨证论治</p></div></div><div class=classic-quote>《傅青主女科》："妇人有年五十外+或六七十岁+忽然行经者+或下紫血块+或如红血淋+人或谓是还少之象+谁知是血崩之渐乎！"<span class=src>——《傅青主女科》</span></div><div class=plain>经断复来就是"绝经后出血"——这是妇科一个危险的信号！绝经一年以上又出血+首先要排除妇科恶性肿瘤（宫颈癌+子宫内膜癌）。排除了恶性病变后+再按中医辨证治疗。血热的用益阴煎/知柏地黄丸+脾虚肝郁的用安老汤（傅青主方）——"安老"就是让老人安度晚年之意。记住先排查恶性再治疗！</p><div class=mnem><strong>口诀：</strong>经断复来绝经后+排除恶性第一要；血热益阴知柏丸+脾虚肝郁安老汤。</div><div class=trap-box><strong>高频考点：</strong>1.首要排除——恶性妇科肿瘤（子宫内膜癌+宫颈癌）！2.血热→益阴煎（生地知母黄柏龟板砂仁甘草）+知柏地黄丸。3.脾虚肝郁→安老汤（人参黄芪白术当归熟地山萸阿胶荆芥穗木耳炒炭甘草香附）。4.湿毒瘀结→萆薢渗湿汤合桂枝茯苓丸。5.注意："老妇血崩"在傅青主女科中有专论。</div></div>'}
  ]}
]},

'''

after = c[:idx3] + UNIT3 + c[idx4:]

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(after)

print(f"Done. Size: {len(after)} bytes (was {len(c)} bytes)")
