#!/usr/bin/env python3
"""fill-erke-unit24-32.py — 填充 s8 第二十四~三十二单元（常见病·下）"""
TARGET = '/sessions/compassionate-hopeful-thompson/mnt/syllabus/subjects/s8-erke.js'

with open(TARGET, 'r', encoding='utf-8') as f:
    c = f.read()

idx24 = c.find('{unit:"第二十四单元')
idxq = c.find('var Q8 = [')

UNITS = r'''{unit:"第二十四单元 麻疹",subunits:[{name:"麻疹",points:[
  {id:"ek-24-1",name:"麻疹的概念、好发季节、证候分类与预后",type:"concept",
content:'<p><strong>麻疹</strong>是麻疹病毒引起的急性出疹性传染病。好发冬春+多见于6个月-5岁小儿。以发热+咳嗽+鼻塞流涕+眼结膜充血+麻疹黏膜斑（Koplik斑）+全身红色斑丘疹为特征。顺证预后良好+逆证（并发症）可危及生命。</p><div class=compare-table><div class=ct-left><h4>好发特点</h4><p><strong>季节：</strong>冬春季<br><strong>人群：</strong>6个月至5岁未接种疫苗者<br><strong>传染源：</strong>患者+飞沫传播<br><strong>免疫力：</strong>病后可获终身免疫</p></div><div class=ct-right><h4>证候分类</h4><p><strong>顺证：</strong>按出疹顺序规律+疹色红活+疹出热退+预后好</p><p><strong>逆证：</strong>出疹不顺序+疹色紫暗+高热不退+并发肺炎喉炎脑炎+预后差</p><p>注意：我国已广泛接种麻疹疫苗+发病率大幅下降</p></div></div><div class=classic-quote>《幼科发挥》："麻疹初起，状如麻子，故名麻疹。乃肺胃热毒，外发于肌肤之表。"<span class=src>——《幼科发挥》</span></div><div class=plain>麻疹是"怕风怕光怕冷"的出疹病——"麻"就是"像芝麻一样"的小红疹。顺证出疹有规律（耳后→面→躯干→四肢→手足心）+"三齐三透"（出齐+出透+收齐）。现在有疫苗后麻疹少了+但没打疫苗的仍可能发病。注意早期诊断"Koplik斑"（口腔黏膜上的小白点+出疹前就出现）是麻疹特有的早期信号。</p><div class=mnem><strong>口诀：</strong>麻疹冬春发热起，Koplik斑早诊断；顺证耳后面躯干，出透热退自安康。</div></div>'},
  {id:"ek-24-2",name:"顺证各期及逆证的证候、治法、方药",type:"apply",
content:'<p><strong>麻疹顺证三期+逆证辨治：</strong></p><div class=compare-table><div class=ct-left><h4>顺证三期</h4><p><strong>初热期（前驱期）：</strong>发热+咳嗽+鼻塞+Koplik斑（口腔黏膜斑）<br>→ <strong>宣毒发表汤</strong></p><p><strong>出疹期：</strong>发热+出疹（耳后→面→躯干→四肢）+口渴+烦躁<br>→ <strong>清解透表汤</strong></p><p><strong>收没期（恢复期）：</strong>疹点渐退+脱屑+棕褐色色素沉着+身热渐退<br>→ <strong>沙参麦冬汤</strong></p></div><div class=ct-right><h4>逆证</h4><p><strong>麻毒闭肺（肺炎）：</strong>高热+咳嗽气喘+鼻煽<br>→ <strong>麻杏石甘汤</strong></p><p><strong>麻毒攻喉（喉炎）：</strong>声音嘶哑+犬吠样咳+喉鸣<br>→ <strong>清咽下痰汤</strong></p><p><strong>毒陷心肝（脑炎）：</strong>高热+神昏+抽搐<br>→ <strong>羚角钩藤汤</strong></p></div></div><div class=classic-quote>《医宗金鉴》："麻疹出疹，以透为顺，以不透为逆。"<span class=src>——《医宗金鉴》</span></div><div class=plain>麻疹顺证三期：初期（热+咳嗽+Koplik斑）→宣毒发表汤透疹+出疹期（全身红疹）→清解透表汤+恢复期（疹退色素沉着）→沙参麦冬汤养阴。逆证三种——麻毒闭肺（肺炎最多见！）→麻杏石甘汤+麻毒攻喉→清咽下痰汤+毒陷心肝→羚角钩藤汤。顺证关键是"透"——疹子出透+热就退了。</p><div class=mnem><strong>口诀：</strong>麻疹顺证三期分，初宣毒发+出疹清解透+收没沙参麦冬；逆证肺炎麻杏石甘+攻喉清咽+陷肝羚角钩藤。</div><div class=trap-box><strong>高频考点：</strong>1.出疹顺序：耳后发际→面部→躯干→四肢→手心足心——必考！2.顺证初热期→宣毒发表汤。3.出疹期→清解透表汤。4.收没期→沙参麦冬汤。5.逆证麻毒闭肺（最常见并发症）→麻杏石甘汤。6.Koplik斑（麻疹黏膜斑）是麻疹早期诊断依据。7.隔离期：出疹前后5天+并发肺炎者隔离10天。</div></div>'}
]}]},

{unit:"第二十五单元 风疹",subunits:[{name:"风疹",points:[{id:"ek-25-1",name:"风疹的概念及辨证论治",type:"detail",
content:'<p><strong>风疹</strong>是风疹病毒引起的急性出疹性传染病。特点：全身红色斑丘疹+耳后枕部淋巴结肿大。好发冬春+5岁以下小儿。症状较麻疹轻+预后好。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>邪犯肺卫（轻型）：</strong>发热恶风+咳嗽+流涕+疹出迅速+疹色淡红+耳后淋巴结肿大<br>→ <strong>银翘散</strong></p><p><strong>邪入气营（重型）：</strong>高热+疹色鲜红/紫暗+密集+口渴+烦躁+淋巴结肿大<br>→ <strong>透疹凉解汤</strong></p></div><div class=ct-right><h4>鉴别要点</h4><p>麻疹vs风疹：<br>·麻疹→发热重+有Koplik斑+疹退有色素沉着<br>·风疹→发热轻+耳后淋巴结大+疹退无色素沉着</p><p>注意：孕妇早期感染风疹→可致胎儿畸形（先天性风疹综合征）。</p></div></div><div class=classic-quote>《医宗金鉴》："风疹者，乃风热之邪，客于皮肤所致也。"<span class=src>——《医宗金鉴》</span></div><div class=plain>风疹就是"风疙瘩"——比麻疹轻得多（发热轻+疹子退得快+不留疤）。与麻疹鉴别要点：风疹有"耳后枕部淋巴结肿大"+疹退不留色素沉着。最需要注意的是"孕妇"——孕早期感染风疹会导致胎儿严重畸形（先天性心脏病+白内障+耳聋等）。</p><div class=mnem><strong>口诀：</strong>风疹热轻疹出快，淋巴结大耳后枕；轻银翘散重凉解，孕妇感染须谨慎。</div><div class=trap-box><strong>考点：</strong>1.特征性表现——耳后+枕部淋巴结肿大。2.邪犯肺卫→银翘散。3.邪入气营→透疹凉解汤（薄荷牛蒡蝉蜕连翘黄芩栀子生地丹皮紫草赤芍）。4.麻疹vs风疹：发热程度+Koplik斑+色素沉着。5.孕妇感染→先天性风疹综合征（重要考点）。6.风疹一般不需特殊治疗+可自愈。</div></div>'}]
}]},

{unit:"第二十六单元 猩红热",subunits:[{name:"猩红热",points:[{id:"ek-26-1",name:"猩红热的概念、病因病机及辨证论治",type:"apply",
content:'<p><strong>猩红热</strong>是A组溶血性链球菌引起的急性出疹性传染病。中医称"烂喉丹痧"。特点：发热+咽峡炎+全身弥漫性鲜红色皮疹+疹后脱皮。好发冬春+2-10岁儿童。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>邪侵肺卫（初起）：</strong>发热恶寒+咽红肿痛+皮疹隐现<br>→ <strong>解肌透痧汤</strong></p><p><strong>毒炽气营（出疹期）：</strong>高热+咽痛糜烂+全身猩红色皮疹+杨梅舌+环口苍白圈<br>→ <strong>凉营清气汤</strong></p><p><strong>疹后阴伤（恢复期）：</strong>疹退脱屑+低热+口干+舌红少苔<br>→ <strong>沙参麦冬汤</strong></p></div><div class=ct-right><h4>鉴别要点</h4><p>三大特征：<br>·杨梅舌（舌乳头红肿突出）<br>·环口苍白圈（口周苍白）<br>·帕氏线（皮肤皱褶处红线）</p><p>疹退后大片脱皮——区别于麻疹（糠状脱屑）</p><p>注意：可并发肾炎+风湿热</p></div></div><div class=classic-quote>《疫喉浅论》："烂喉丹痧，以畅汗为佳，透疹为要，凉营为主。"<span class=src>——《疫喉浅论》</span></div><div class=plain>猩红热就是"猩红色的热病"——红得像猩猩一样+全身红疹+烂喉咙（咽峡炎）。三大特征："杨梅舌"（舌像杨梅一样红点突起）+"环口苍白圈"（嘴周围一圈白）+"帕氏线"（皮肤皱褶处红得发紫）。和麻疹区别：猩红热疹退后大片脱皮（像蛇蜕皮）+麻疹是糠状脱屑。并发症要防肾炎和风湿热。</p><div class=mnem><strong>口诀：</strong>猩红热烂喉丹痧，杨梅舌苍白环口帕线；初解肌透+毒凉营+阴伤沙参麦冬。</div><div class=trap-box><strong>高频考点：</strong>1.三大特征——杨梅舌+环口苍白圈+帕氏线。2.邪侵肺卫→解肌透痧汤（荆芥蝉蜕豆豉浮萍葛根牛蒡连翘僵蚕射干马勃甘草）。3.毒炽气营→凉营清气汤（犀角生地丹皮赤芍栀子黄芩连翘石膏竹叶玄参）。4.疹后阴伤→沙参麦冬汤。5.并发肾炎+风湿热。6.与麻疹鉴别——脱皮方式不同。</div></div>'}]
}]},

{unit:"第二十七单元 水痘",subunits:[{name:"水痘",points:[{id:"ek-27-1",name:"水痘的概念及辨证论治",type:"detail",
content:'<p><strong>水痘</strong>是水痘带状疱疹病毒引起的急性出疹性传染病。特点：发热+皮肤分批出现丘疹+水疱+结痂。"四代同堂"（同一部位可见不同阶段的皮疹）。好发冬春+1-6岁儿童。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>邪伤肺卫（轻证）：</strong>发热轻微+疹色红润+疱浆清亮+精神好<br>→ <strong>银翘散</strong>合<strong>六一散</strong></p><p><strong>毒炽气营（重证）：</strong>壮热+疹色紫暗+疱浆混浊+稠密+精神差<br>→ <strong>清胃解毒汤</strong></p></div><div class=ct-right><h4>鉴别与调护</h4><p>水痘vs脓疱疮：<br>·水痘→分批出现+向心分布+疱壁薄<br>·脓疱疮→成批出现+离心分布+疱壁厚</p><p>调护：<br>·隔离至全部结痂（约1-2周）<br>·避免抓破感染+留疤痕<br>·禁用糖皮质激素（可致重症水痘！）</p></div></div><div class=classic-quote>《小儿药证直诀》："水痘，其色如水泡，故名水痘。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>水痘最典型的表现是"四代同堂"——同一个部位同时能看到丘疹（刚出来）+水疱（鼓起来）+脓疱（混浊）+结痂（快好了）。水痘轻证用银翘散+重证用清胃解毒汤。关键禁忌：水痘期间禁用激素（会诱发重症水痘+甚至死亡）。水痘疫苗已广泛接种+发病率明显下降。</p><div class=mnem><strong>口诀：</strong>水痘四代同堂见，轻银翘散重清胃；禁用激素第一要，隔离结痂防留瘢。</div><div class=trap-box><strong>高频考点：</strong>1.特征——"四代同堂"（丘疹+水疱+脓疱+结痂同时存在）。2.轻证邪伤肺卫→银翘散合六一散。3.重证毒炽气营→清胃解毒汤（升麻黄连丹皮生地石膏黄芩）。4.水痘禁用糖皮质激素（重要！）。5.隔离至全部结痂。6.与脓疱疮鉴别要点。</div></div>'}]
}]},

{unit:"第二十八单元 流行性腮腺炎",subunits:[{name:"痄腮",points:[{id:"ek-28-1",name:"流行性腮腺炎的概念、病机特点及辨证论治",type:"apply",
content:'<p><strong>流行性腮腺炎</strong>是腮腺炎病毒引起的急性传染病。中医称"痄腮"或"蛤蟆瘟"。特点：发热+腮部肿胀疼痛。好发冬春+学龄儿童。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>温毒在表（轻证）：</strong>轻微发热恶寒+一侧或两侧耳下腮部漫肿疼痛+咀嚼不便<br>→ <strong>柴胡葛根汤</strong></p><p><strong>热毒蕴结（重证）：</strong>高热+腮部肿痛明显+坚硬拒按+烦躁+口渴+便秘<br>→ <strong>普济消毒饮</strong></p></div><div class=ct-right><h4>并发症</h4><p><strong>邪陷心肝（脑炎）：</strong>高热+头痛+呕吐+嗜睡+抽搐<br>→ <strong>羚角钩藤汤</strong></p><p><strong>毒窜睾腹（睾丸炎）：</strong>睾丸肿痛+小腹疼痛<br>→ <strong>龙胆泻肝汤</strong></p><p>注意：腮腺炎本身预后好+但并发症严重。</p></div></div><div class=classic-quote>《外科正宗》："痄腮乃风热湿痰所生，颔下耳后肿痛，湿热交蒸所致。"<span class=src>——《外科正宗</span></div><div class=plain>痄腮就是"腮腺炎"——耳垂下面肿得像猪头一样。最经典的外治法是"金黄散醋调外敷"肿痛处。并发症很重要：睾丸炎（男孩）+脑炎。普济消毒饮（黄芩黄连玄参连翘板蓝根马勃牛蒡子僵蚕升麻柴胡陈皮桔梗薄荷甘草）是治疗痄腮重证的代表方。</p><div class=mnem><strong>口诀：</strong>痄腮肿痛耳下漫，轻柴胡葛根重普济消毒饮；金黄散外敷痛减，陷肝羚角+毒窜睾腹龙胆泻肝。</div><div class=trap-box><strong>考点：</strong>1.温毒在表→柴胡葛根汤（柴胡葛根黄芩牛蒡连翘石膏升麻桔梗甘草）。2.热毒蕴结→普济消毒饮。3.并发症：邪陷心肝（脑炎）→羚角钩藤汤+毒窜睾腹（睾丸炎）→龙胆泻肝汤。4.外治：金黄散醋调外敷。5.病后可获终身免疫。6.注意与颈部淋巴结炎鉴别——腮腺炎以耳垂为中心肿胀。</div></div>'}]
}]},

{unit:"第二十九单元 流行性乙型脑炎",subunits:[{name:"乙脑",points:[{id:"ek-29-1",name:"流行性乙型脑炎的概念、传变规律及辨证论治",type:"apply",
content:'<p><strong>流行性乙型脑炎</strong>是乙脑病毒引起的急性中枢神经系统传染病。中医称"暑温"或"小儿暑温"。好发夏秋（7-9月）+2-6岁儿童。以高热+意识障碍+抽搐+呼吸衰竭为特征。病死率高+后遗症重。</p><div class=compare-table><div class=ct-left><h4>传变规律（卫气营血）</h4><p>乙脑传变极快+按卫气营血传变+且往往卫气同病+气营同病。</p><p><strong>邪犯卫气（初期）：</strong>发热+头痛+嗜睡+口渴<br>→ <strong>新加香薷饮</strong>或<strong>白虎汤</strong></p><p><strong>气营两燔（极期）：</strong>高热+神昏+抽搐+颈项强直<br>→ <strong>清瘟败毒饮</strong></p><p><strong>热入营血（重症）：</strong>深度昏迷+反复抽搐+呼吸不整<br>→ <strong>犀角地黄汤</strong>合<strong>羚角钩藤汤</strong></p></div><div class=ct-right><h4>恢复期/后遗症</h4><p><strong>恢复期（余邪未清）：</strong>低热+神疲+纳差+口干<br>→ <strong>沙参麦冬汤</strong></p><p><strong>后遗症：</strong><br>·痰蒙清窍→痴呆+失语+失眠→苏合香丸/安宫牛黄丸<br>·痰阻经络→肢体瘫痪+抽搐→指迷茯苓丸合桃红四物汤</p></div></div><div class=classic-quote>《温病条辨》："暑温，上焦病者，太阴之表也；中焦病者，阳明之里也。"<span class=src>——《温病条辨》</span></div><div class=plain>乙脑是小儿最严重的传染病之一——"高热+抽筋+昏迷+呼吸衰竭"。传变按温病卫气营血走+但非常快（可能第一天就气营同病）。夏秋发病（蚊子传播）+2-6岁小孩高发。恢复期和后遗症是乙脑治疗的重点难点——很多孩子命救回来了但有后遗症（智力障碍+瘫痪等）。预防最关键：灭蚊+打疫苗。</p><div class=mnem><strong>口诀：</strong>乙脑暑温夏秋发，卫气新加白虎+气营清瘟败毒+营血犀角羚角钩藤汤。</div><div class=trap-box><strong>高频考点：</strong>1.好发季节——夏秋（7-9月）+蚊子传播。2.传变特点——按卫气营血+传变迅速+气营同病多见。3.邪犯卫气→新加香薷饮/白虎汤。4.气营两燔→清瘟败毒饮。5.热入营血→犀角地黄汤合羚角钩藤汤。6.恢复期→沙参麦冬汤。7.后遗症治疗：痰蒙清窍→苏合香丸/安宫牛黄丸+瘫痪→指迷茯苓丸合桃红四物汤。</div></div>'}
]}]},

{unit:"第三十单元 寄生虫病",subunits:[{name:"寄生虫病",points:[
  {id:"ek-30-1",name:"蛔虫病（肠虫证、蛔厥证）的证候治法方药",type:"detail",
content:'<p><strong>蛔虫病</strong>是最常见的小儿肠道寄生虫病。蛔虫寄生在小肠+吸取营养+影响发育。传染源：蛔虫卵经口入（手+食物+玩具）。</p><div class=compare-table><div class=ct-left><h4>肠虫证（普通型）</h4><p><strong>证候：</strong>脐周腹痛+时作时止+食欲异常（嗜异—喜吃泥土生米）+睡中磨牙+面部白斑+巩膜蓝斑+大便有蛔虫</p><p><strong>治法：</strong>驱蛔杀虫+调理脾胃</p><p><strong>主方：</strong>使君子散/化虫丸/驱虫汤</p><p>注意：驱虫后→异功散健脾</p></div><div class=ct-right><h4>蛔厥证（急症）</h4><p><strong>证候：</strong>突发右上腹阵发性剧烈绞痛+弯腰屈膝+呕吐蛔虫+四肢厥冷+冷汗</p><p><strong>治法：</strong>安蛔定痛+温脏驱蛔</p><p><strong>主方：</strong>乌梅丸</p><p>注意：痛止后驱虫</p></div></div><div class=classic-quote>《景岳全书》："蛔虫之动，因于脏腑寒热。脏寒则虫不安，避寒就温而扰动。"<span class=src>——《景岳全书》</span></div><div class=plain>蛔虫病是小孩"肚子里长虫"——最多见的症状是肚子痛（绕脐痛）+睡觉磨牙+脸上有白斑+爱吃奇怪东西（异嗜症）。蛔厥是最危险的——蛔虫钻到胆道里去了（胆道蛔虫症）+痛得打滚+用乌梅丸安蛔止痛。防治关键是"饭前便后洗手"。</p><div class=mnem><strong>口诀：</strong>蛔虫肠虫使君子散，蛔厥乌梅丸痛安；驱虫后调理脾胃，饭前洗手最关键。</div></div>'},
  {id:"ek-30-2",name:"蛲虫病的主要临床表现及预防护理",type:"detail",
content:'<p><strong>蛲虫病</strong>是蛲虫寄生于小肠末端+盲肠+结肠。特点：肛门瘙痒（夜间尤甚）+睡眠不安。好发于学龄前儿童+集体机构（幼儿园）易传播。</p><div class=compare-table><div class=ct-left><h4>临床表现</h4><p><strong>主要症状：</strong><br>·肛门周围及会阴部瘙痒（夜间更明显）<br>·睡眠不安+夜惊+烦躁<br>·女孩可有阴道炎+尿频尿急</p><p><strong>诊断：</strong><br>·夜间在肛周可见白色线头样小虫（0.5-1cm）<br>·肛周拭子法找到虫卵</p></div><div class=ct-right><h4>预防护理</h4><p><strong>治疗：</strong><br>·驱虫药（阿苯达唑/甲苯达唑）<br>·外用药：百部煎剂/蛲虫膏涂肛周<br>·局部：睡前温水洗肛+涂药</p><p><strong>预防：</strong><br>·勤剪指甲+饭前便后洗手<br>·内衣裤煮沸消毒+暴晒<br>·不穿开裆裤<br>·家庭集体治疗防交叉感染</p></div></div><div class=classic-quote>《医宗金鉴》："蛲虫者，细小如线，居于肠胃，发于肛周，夜间爬出。"<span class=src>——《医宗金鉴》</span></div><div class=plain>蛲虫病就是"屁股里长小虫"——小孩晚上肛门痒+用手抓+虫卵跑到指甲里→再吃进去（反复感染）。特征是"晚上在肛门能看到白色线头样小虫"。治疗不难（驱虫药）+但预防更重要（勤洗手+剪指甲+内裤消毒+全家一起治）。幼儿园集体生活的孩子特别容易互相传。</p><div class=mnem><strong>口诀：</strong>蛲虫肛痒夜更明，白线小虫肛周见；驱虫外涂百部膏，勤剪指甲防复感。</div></div>'}
]}]},

{unit:"第三十一单元 夏季热",subunits:[{name:"夏季热",points:[{id:"ek-31-1",name:"夏季热的概念及辨证论治",type:"detail",
content:'<p><strong>夏季热</strong>是婴幼儿在夏季长期发热+口渴+多饮+多尿+汗闭或少汗。中医称"疰夏"或"暑热症"。特点：夏季发病+体温随气温升降+秋凉自愈。多见于3岁以下+体质虚弱小儿。预后良好。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>暑伤肺胃（暑热伤津）：</strong>发热+口渴多饮+尿多+汗少+烦躁+舌尖红+苔薄黄<br>→ <strong>王氏清暑益气汤</strong></p><p><strong>上盛下虚（脾肾两虚）：</strong>发热+精神萎靡+面色苍白+下肢清冷+小便清长+大便稀溏+口渴多饮<br>→ <strong>温下清上汤</strong></p></div><div class=ct-right><h4>鉴别与调护</h4><p>与普通感冒发热鉴别：<br>·夏季热→夏季发热+与气温平行+秋凉自愈+精神可<br>·感冒发热→多伴卡他症状+病程短</p><p>调护：<br>·居室通风降温+空调可用<br>·温水擦浴+饮食清淡<br>·多饮水+西瓜汁+绿豆汤</p></div></div><div class=classic-quote>《小儿药证直诀》："夏月小儿伏暑，多因乳母冒暑，或小儿自身受暑。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>夏季热是"夏天的特殊病"——天一热就发烧+天凉就好。特点"三多一少"——发热多+喝水多+小便多+汗少。治疗分期：暑热伤津（王氏清暑益气汤——西洋参西瓜翠衣黄连知母竹叶荷梗等）——清暑热养气阴+脾肾两虚（温下清上汤）——温下清上。注意：这个病预后好+但需与感冒鉴别+不要乱用抗生素。</p><div class=mnem><strong>口诀：</strong>夏季热暑热伤津清暑益气，上盛下虚温下清上；三多一少汗闭为特征，秋凉自愈预后良。</div></div>'}]
}]},

{unit:"第三十二单元 紫癜",subunits:[{name:"紫癜",points:[{id:"ek-32-1",name:"紫癜的病机及风热伤络、血热妄行、气不摄血、阴虚火旺证的证候治法方药",type:"apply",
content:'<p><strong>紫癜</strong>是小儿皮肤出现瘀点瘀斑（皮下出血）。相当于过敏性紫癜+血小板减少性紫癜。病机：血不循经+溢于脉外。与心脾肾三脏关系密切。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>风热伤络（过敏性紫癜早期）：</strong>紫癜反复出现+多下肢+伴痒+发热+关节肿痛<br>→ <strong>连翘败毒散</strong></p><p><strong>血热妄行（血小板减少性）：</strong>起病急+紫癜密集+色鲜红+鼻衄+齿衄+发热+口渴<br>→ <strong>犀角地黄汤</strong></p><p><strong>气不摄血（慢性）：</strong>紫癜反复+色淡暗+散在+神疲+面色萎黄+食少便溏<br>→ <strong>归脾汤</strong></p><p><strong>阴虚火旺（慢性）：</strong>紫癜时发+色鲜红/暗红+低热+盗汗+手足心热+舌红少苔<br>→ <strong>大补阴丸</strong></p></div><div class=ct-right><h4>鉴别与调护</h4><p>过敏性紫癜vs血小板减少性紫癜：<br>·过敏性→多下肢+伴关节痛/腹痛/血尿+血小板正常<br>·血小板减少→全身散在+血小板减少</p><p>注意：<br>·过敏性紫癜可累及肾脏（紫癜性肾炎）<br>·卧床休息+避免感染+清淡饮食</p></div></div><div class=classic-quote>《医宗金鉴》："紫癜风，多发于小儿，皮肤起紫点，大小不一，亦有如豆如钱者。"<span class=src>——《医宗金鉴》</span></div><div class=plain>紫癜就是"小孩身上起紫血点"——血不往血管里走了+跑出来了。四型辨治：风热伤络（过敏性紫癜+下肢多+痒）→连翘败毒散+血热妄行（血小板减少性+起病急+色鲜红）→犀角地黄汤+气不摄血（慢性反复+色淡）→归脾汤+阴虚火旺（慢性+红色+手足心热）→大补阴丸。过敏性紫癜容易伤肾+需定期查尿常规。</p><div class=mnem><strong>口诀：</strong>紫癜风热连翘败毒+血热犀角地黄+气不摄血归脾+阴虚大补阴丸；过敏性紫癜多下肢+血小板减少性紫癜全身散。</div><div class=trap-box><strong>高频考点：</strong>1.风热伤络→连翘败毒散（连翘银花薄荷荆芥防风牛蒡桔梗竹叶甘草）。2.血热妄行→犀角地黄汤（犀角地黄赤芍丹皮）。3.气不摄血→归脾汤。4.阴虚火旺→大补阴丸（知母黄柏熟地龟板猪脊髓）。5.过敏性紫癜vs血小板减少性：血小板计数+伴随症状。6.过敏性紫癜需防肾脏损害。</div></div>'}
]}]},
'''

# Replace the unit block (from unit 24 to end of unit 32, before var Q8)
after = c[:idx24] + UNITS + c[idxq:]

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(after)

print(f"Done. Size: {len(after)} bytes (was {len(c)} bytes)")
