#!/usr/bin/env python3
"""fill-unit7.py — 填充 s6 第七单元 瘿"""
TARGET = '/sessions/compassionate-hopeful-thompson/mnt/syllabus/subjects/s6-waike.js'

with open(TARGET, 'r', encoding='utf-8') as f:
    c = f.read()

idx7 = c.find('{unit:"第七单元')
idx8 = c.find('{unit:"第八单元')
print(f"Replace offset {idx7}-{idx8} (len={idx8-idx7})")

UNIT7 = r'''{unit:"第七单元 瘿",subunits:[
  {name:"细目一：概述",points:[{id:"wk-7-1",name:"瘿病的病因病机",type:"concept",
content:'<p><strong>瘿病</strong>是颈前喉结两侧肿块性疾病总称。特点：颈前肿块+随吞咽上下移动。主要病因：<strong>气滞+痰凝+血瘀</strong>结于颈部。</p><div class=compare-table><div class=ct-left><h4>致病因素</h4><p><strong>水土因素：</strong>久居山区+水质缺碘→瘿病多发<br><strong>情志内伤：</strong>忧思郁怒+肝郁气滞+气滞痰凝<br><strong>外感六淫：</strong>山岚瘴气+邪毒入络<br><strong>饮食不节：</strong>碘摄入不足或过量</p></div><div class=ct-right><h4>病机概要</h4><p><strong>基本病机：</strong>气滞+痰凝+血瘀互结于颈前<br><strong>主要脏腑：</strong>肝（主疏泄）+脾（运化水湿）+肾（主水）<br><strong>演变：</strong>气滞→痰凝→血瘀→化热伤阴</p></div></div><div class=classic-quote>《外科正宗》："夫瘿病者，由五脏积热，搏于经络，或外感山岚之气，或内伤七情之郁，以致气血凝滞，结于颈项之间。"<span class=src>——《外科正宗》</span></div><div class=plain>"瘿"字从"疒"从"婴"——像婴儿脖子一样粗（婴儿脖子短而粗）。通俗说就是脖子"粗了"+或者长"疙瘩"了。中医说"无痰不成瘿"——瘿的核心病理是痰和气结在一起。气滞+痰凝+血瘀互结是总病机。记住"瘿病三因"：水土（缺碘）+情志（郁怒）+饮食。</p><div class=mnem><strong>口诀：</strong>瘿病颈前结块生，气滞痰凝血瘀成；水土情志饮食因，肝脾肾经病所承。</div><div class=trap-box><strong>考点：</strong>1.基本病机——气滞痰凝血瘀结于颈前。2.瘿病以"肝经"为主——足厥阴肝经循喉咙之后。3.三大瘿病鉴别：气瘿弥漫柔软+肉瘿肿块如核桃+石瘿坚硬如石。4.瘿病在古代分为五瘿（气瘿+血瘿+肉瘿+筋瘿+石瘿）+现代临床常见气肉石三类。5.瘿与瘰疬鉴别：瘿在颈前正中+瘰疬在颈侧（淋巴结）。</div></div>'}]
},
  {name:"细目二：气瘿",points:[{id:"wk-7-2",name:"气瘿的病因病机、临床表现及内治法",type:"detail",
content:'<p><strong>气瘿</strong>是颈前弥漫性肿大（单纯性甲状腺肿）。特点：弥漫对称+柔软光滑+随吞咽上下移动。好发于山区青年女性（青春期+妊娠期高发）。</p><div class=compare-table><div class=ct-left><h4>气瘿特点</h4><p><strong>病因：</strong>缺碘+肝郁气滞<br><strong>表现：</strong>颈前弥漫肿大+皮色如常+柔软无痛+随吞咽上下<br><strong>内治：</strong>疏肝解郁+理气散结<br><strong>主方：</strong>四海舒郁丸<br><strong>外治：</strong>一般不需外治<br><strong>预后：</strong>良好+可自行消退</p></div><div class=ct-right><h4>鉴别要点</h4><p><strong>气瘿vs肉瘿：</strong><br>气瘿→弥漫性肿大+对称+柔软<br>肉瘿→局限性肿块+如核桃+韧实</p><p><strong>气瘿vs石瘿：</strong><br>气瘿→柔软光滑+可缩小<br>石瘿→坚硬如石+推之不移</p></div></div><div class=classic-quote>《医宗金鉴》："瘿证多生于肩项两颐，或结块，或漫肿，或推之可移，皮色如常，多因七情抑郁。"<span class=src>——《医宗金鉴》</span></div><div class=plain>气瘿就是"大脖子病"——整个脖子前面都鼓起来了，但摸上去软软的。多见于山区缺碘地区——女性青年最多（青春期缺碘→甲状腺代偿性肿大）。怀孕和哺乳期更明显。用"四海舒郁丸"——名字里的"海"字提示用海藻昆布等海产品（含碘）。现在国家推行加碘盐后，新发的缺碘性气瘿已经很少了。</p><div class=mnem><strong>口诀：</strong>气瘿弥漫软如棉，青年女性山区见；疏肝解郁四海丸，海藻昆布含碘先。</div><div class=trap-box><strong>考点：</strong>1.气瘿主方——四海舒郁丸（海藻昆布海蛤壳海螵蛸+青木香陈皮柴胡等）。2.好发人群：青年女性+青春期+妊娠期。3.病因：缺碘+肝郁气滞。4.气瘿特点是弥漫对称+柔软光滑+随吞咽上下移动。5.鉴别：气瘿俗称"大脖子"+肉瘿是"脖子上长了个疙瘩"。6.外治可用：局部针灸+气瘿较大压迫症状需手术。7.预防：食用加碘盐。</div><div class=clinical-case>一位20岁女性山区居住史+颈前弥漫肿大半年+柔软光滑无痛+青春期——气瘿用四海舒郁丸（海藻15g昆布15g海蛤壳15g海螵蛸12g青木香6g陈皮6g柴胡9g郁金9g）加夏枯草15g二十剂后颈部明显缩小。嘱食用加碘盐。</div></div><div class=mini-quiz><div class=mq-title>一分钟诊室</div><div class=mq-scene>患者青年女性山区居住+颈前弥漫对称肿大柔软无痛随吞咽上下移动</div><div class=mq-opts><span class=mq-opt data-ans=right>A. 四海舒郁丸</span><span class=mq-opt data-ans=wrong>B. 海藻玉壶汤</span><span class=mq-opt data-ans=wrong>C. 逍遥散</span><span class=mq-opt data-ans=wrong>D. 柴胡疏肝散</span></div><div class=mq-feedback style=display:none><template class=fb-right>正确！气瘿（弥漫性甲状腺肿）用四海舒郁丸疏肝解郁理气散结+补碘。</template><template class=fb-wrong>气瘿弥漫柔软四海舒郁+肉瘿如核桃海藻玉壶+石瘿坚硬如石手术为主。</template></div></div>',
cardQuiz:[{q:"气瘿的好发人群是？",opts:["青年女性","老年男性","儿童","中年男性"],ans:0},{q:"气瘿的主方四海舒郁丸中主药属于？",opts:["海产品（含碘）","矿石类","动物类","植物类"],ans:0}]}]
},
  {name:"细目三：肉瘿",points:[{id:"wk-7-3",name:"肉瘿的概念、特点、病因病机及辨证论治",type:"apply",
content:'<p><strong>肉瘿</strong>是颈前喉结一侧或两侧的局限性肿块（甲状腺腺瘤/结节）。特点：肿块如核桃+韧实光滑+随吞咽上下+无痛。好发于青中年女性。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肝郁气滞（早期）：</strong>肿块较小+情志不畅+胸胁胀闷<br>→ <strong>逍遥散</strong>疏肝解郁</p><p><strong>气阴两虚（发展期）：</strong>肿块增大+心悸多汗+易饥消瘦+手抖<br>→ <strong>生脉散合海藻玉壶汤</strong></p><p><strong>气滞血瘀（后期）：</strong>肿块增大较硬+吞咽不适+舌紫暗<br>→ <strong>桃红四物汤合海藻玉壶汤</strong></p></div><div class=ct-right><h4>诊断与鉴别</h4><p><strong>诊断要点：</strong>颈前圆形/椭圆形肿块+边界清楚+表面光滑+质韧不痛+随吞咽上下<br><strong>B超：</strong>甲状腺实性或囊实性结节<br><strong>同位素扫描：</strong>温结节或热结节</p></div></div><div class=classic-quote>《外科正宗》："肉瘿者，皮色如常，肉随吞咽上下，柔软不痛，是谓肉瘿。"<span class=src>——《外科正宗》</span></div><div class=plain>肉瘿就是脖子上长了个"肉疙瘩"（甲状腺腺瘤）——摸上去像剥了壳的煮鸡蛋（圆润光滑韧实）。和气的区别：气瘿是整个脖子都粗+肉瘿是局部一个疙瘩。治疗首选"海藻玉壶汤"——"玉壶"就是玉做的壶（珍贵容器）+寓意把瘿病化掉。发现有甲状腺结节不要慌——绝大多数是良性的肉瘿。但：肉瘿有癌变可能（约10%可变为石瘿）！所以需要定期复查。</p><div class=mnem><strong>口诀：</strong>肉瘿如核随吞咽，逍遥气郁生脉虚；海藻玉壶通用方，软坚散结功效殊。</div><div class=trap-box><strong>高频考点：</strong>1.肉瘿代表方——海藻玉壶汤（海藻昆布贝母半夏陈皮青皮川芎当归连翘独活甘草）。2.注意：海藻玉壶汤中海藻与甘草同用——"藻戟遂芫俱战草"的反药配伍！但外科传统经验认为海藻反甘草在瘿病治疗中相激相成（需在医师指导下使用）。3.肉瘿vs气瘿：局限肿块vs弥漫肿大。4.肉瘿有癌变倾向（10%恶变率）——需定期复查。5.内治为主+较大可手术。6.注意继发甲亢（心悸多汗手抖）——按气阴两虚论治。</div><div class=clinical-case>一位32岁女性左颈部摸到核桃大肿块+韧实光滑+随吞咽上下+无痛——肉瘿肝郁气滞用海藻玉壶汤（海藻15g昆布15g贝母9g半夏9g陈皮6g青皮6g川芎9g当归9g连翘12g独活6g甘草6g）加夏枯草15g郁金9g十四剂后肿块明显缩小。</div></div><div class=mini-quiz><div class=mq-title>一分钟诊室</div><div class=mq-scene>患者左颈部核桃大小肿块韧实光滑随吞咽上下移动无痛</div><div class=mq-opts><span class=mq-opt data-ans=right>A. 海藻玉壶汤</span><span class=mq-opt data-ans=wrong>B. 四海舒郁丸</span><span class=mq-opt data-ans=wrong>C. 逍遥散</span><span class=mq-opt data-ans=wrong>D. 桃红四物汤</span></div><div class=mq-feedback style=display:none><template class=fb-right>正确！肉瘿（甲状腺腺瘤）用海藻玉壶汤化痰软坚散结。</template><template class=fb-wrong>肉瘿如核桃用海藻玉壶+气瘿弥漫用四海舒郁+石瘿坚硬手术为主。</template></div></div>',
cardQuiz:[{q:"肉瘿的代表方是？",opts:["海藻玉壶汤","四海舒郁丸","逍遥散","桃红四物汤"],ans:0},{q:"肉瘿主要需与什么疾病鉴别？",opts:["气瘿","石瘿","瘰疬","颈痈"],ans:0},{q:"肉瘿的潜在风险是？",opts:["癌变可能","甲亢危象","感染化脓","自行破溃"],ans:0}]}]
},
  {name:"细目四：石瘿",points:[{id:"wk-7-4",name:"石瘿的含义、特点、病因病机、诊断及治疗原则",type:"apply",
content:'<p><strong>石瘿</strong>是颈前肿块坚硬如石的恶性病变（甲状腺癌）。特点：肿块坚硬+推之不移+表面不平+增长迅速+可伴声音嘶哑。</p><div class=compare-table><div class=ct-left><h4>三大瘿病对比</h4><p><strong>气瘿：</strong>弥漫肿大+柔软+随吞咽上下+好发青年女性<br>→ 四海舒郁丸</p><p><strong>肉瘿：</strong>如核桃+韧实+随吞咽+好发青中年女性<br>→ 海藻玉壶汤</p><p><strong>石瘿：</strong>坚硬如石+推之不移+表面不平+好发中老年<br>→ 手术为主（早期）</p></div><div class=ct-right><h4>诊断与治疗</h4><p><strong>临床表现：</strong>甲状腺肿块短期内增大+质硬如石+表面凹凸不平+固定不移+可伴声音嘶哑+呼吸吞咽困难<br><strong>辅助检查：</strong>B超（低回声+边界不清+微小钙化）+核素扫描（冷结节）+穿刺活检<br><strong>治疗原则：</strong>手术切除为主+术后中药调理扶正</p></div></div><div class=classic-quote>《外科正宗》："石瘿者，坚硬如石，推之不移，皮色如常……此属阴证，最为难治。"<span class=src>——《外科正宗》</span></div><div class=plain>石瘿就是甲状腺癌——"石"字说明一切：像石头一样硬！和肉瘿的区别就像"鸡蛋"vs"石头"：肉瘿像煮鸡蛋（韧实光滑）+石瘿像石头（坚硬如石推不动）。治疗以手术为主。但是：甲状腺癌是预后最好的恶性肿瘤之一（号称"懒癌"）——早期手术切除效果非常好。记住三个"不"：不平（表面凹凸不平）+不动（推之不移）+不随（不随吞咽上下移动）。</p><div class=mnem><strong>口诀：</strong>石瘿坚硬如石盘，凹凸不平推不移；手术为主早切除，术后扶正防复起。</div><div class=trap-box><strong>高频考点：</strong>1.三大瘿病鉴别——气瘿弥漫软+肉瘿如核桃+石瘿坚硬如石（必考！）。2.石瘿特征：坚硬如石+推之不移+表面不平。3.辅助检查：B超（低回声边界不清微钙化）+核素冷结节+穿刺确诊。4.治疗：手术为主+早期效果好。5.声音嘶哑提示肿瘤侵犯喉返神经+呼吸吞咽困难提示压迫气管食管。6.甲状腺癌病理类型：乳头状癌最多（预后最好）+滤泡状癌+髓样癌+未分化癌（预后最差）。</div><div class=clinical-case>一位55岁女性颈前肿块3个月迅速增大+质地坚硬如石+表面不平+推之不移+声音嘶哑——石瘿行甲状腺癌根治术+术后病理示乳头状癌。术后用益气养阴方（黄芪30g太子参15g麦冬12g五味子9g玄参15g牡蛎30g白花蛇舌草30g）调理三月+配合优甲乐抑制治疗，恢复良好。</div></div><div class=mini-quiz><div class=mq-title>一分钟诊室</div><div class=mq-scene>患者中老年女性+颈前肿块坚硬如石+表面不平+推之不移+声音嘶哑</div><div class=mq-opts><span class=mq-opt data-ans=right>A. 石瘿（手术为主）</span><span class=mq-opt data-ans=wrong>B. 肉瘿（海藻玉壶汤）</span><span class=mq-opt data-ans=wrong>C. 气瘿（四海舒郁丸）</span><span class=mq-opt data-ans=wrong>D. 瘰疬（消瘰丸）</span></div><div class=mq-feedback style=display:none><template class=fb-right>正确！石瘿=甲状腺癌（质硬如石+推之不移+声音嘶哑）以手术为主。</template><template class=fb-wrong>三大瘿病鉴别：气瘿弥漫软（四海）+肉瘿如核桃（海藻玉壶）+石瘿坚硬如石（手术）。</template></div></div>',
cardQuiz:[{q:'三大瘿病的鉴别中"坚硬如石"的是？',opts:["石瘿","肉瘿","气瘿","血瘿"],ans:0},{q:"石瘿的治疗原则是？",opts:["手术为主","内服中药","外敷药物","针灸治疗"],ans:0},{q:"石瘿的声音嘶哑提示？",opts:["侵犯喉返神经","喉头水肿","声带麻痹","气管受压"],ans:0}]}]
}
]}'''

after = c[:idx7] + UNIT7 + ',' + c[idx8:]

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(after)

print(f"Done. Size: {len(after)} bytes (was {len(c)} bytes)")
