#!/usr/bin/env python3
"""fill-erke-unit6-14.py — 填充 s8 第六~十四单元（常见病·上）"""
TARGET = '/sessions/compassionate-hopeful-thompson/mnt/syllabus/subjects/s8-erke.js'

with open(TARGET, 'r', encoding='utf-8') as f:
    c = f.read()

idx6 = c.find('{unit:"第六单元')
idx15 = c.find('{unit:"第十五单元')

UNITS = r'''{unit:"第六单元 胎怯",subunits:[{name:"胎怯",points:[{id:"ek-6a-1",name:"胎怯的概念及辨证论治",type:"concept",
content:'<p><strong>胎怯</strong>是新生儿体重低下+身材矮小+脏腑功能不成熟。相当于西医学的"低出生体重儿"或"小于胎龄儿"。包括早产儿+小于胎龄儿。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肾精薄弱（肾虚）：</strong>形体瘦小+头大囟张+头发稀黄+耳壳软+哭声低弱+指甲软短+骨弱肢柔<br>→ <strong>补肾地黄丸</strong>补肾益精</p><p><strong>脾肾两虚：</strong>肌肉瘦削+手足如削+吮乳无力+腹胀+大便稀溏+面色萎黄<br>→ <strong>保元汤</strong>健脾补肾</p></div><div class=ct-right><h4>调护要点</h4><p>·保暖（体温调节能力差）<br>·喂养（尽早开奶+少量多次）<br>·预防感染（免疫力低下）<br>·补充维生素D+铁剂</p><p>注意：胎怯预后与出生体重和胎龄正相关</p></div></div><div class=classic-quote>《小儿药证直诀》："胎怯者，生下面无精光，肌肉薄，大便白水，身无血色。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>胎怯就是"先天不足"——生下来就瘦小虚弱。中医认为主要是"肾"和"脾"没发育好（肾主骨+脾主肌肉）。肾虚的用补肾地黄丸（补肾）+脾肾两虚的用保元汤（补脾肾）。护理上保暖第一（不能冷着）+喂养要特别小心（吃得慢+容易呛）。</p><div class=mnem><strong>口诀：</strong>胎怯先天不足生，肾精补肾地黄灵；脾肾两虚保元汤，保暖喂养第一行。</div></div>'}]
}]},

{unit:"第七单元 胎黄",subunits:[{name:"胎黄",points:[
  {id:"ek-7-1",name:"胎黄的概念及生理性与病理性的区别",type:"compare",
content:'<p><strong>胎黄</strong>是婴儿出生后皮肤面目出现黄色。分生理性和病理性两种。</p><div class=compare-table><div class=ct-left><h4>生理性胎黄</h4><p><strong>出现时间：</strong>出生后2-3天<br><strong>高峰：</strong>4-6天<br><strong>消退时间：</strong>7-14天（足月儿）+2-4周（早产儿）<br><strong>血清胆红素：</strong><221μmol/L（12.9mg/dL）<br><strong>一般情况：</strong>良好+无其他症状<br><strong>特点：</strong>不需特殊治疗+自行消退</p></div><div class=ct-right><h4>病理性胎黄</h4><p><strong>出现时间：</strong>出生后24小时内或>2周不退<br><strong>程度：</strong>黄色深重+血清胆红素>221μmol/L<br><strong>每日升高：</strong>>85μmol/L<br><strong>持续时间：</strong>>2周（足月）/>4周（早产）<br><strong>表现：</strong>可伴精神萎靡+拒乳+大便色白<br><strong>注意：</strong>严重可致胆红素脑病（核黄疸）</p></div></div><div class=classic-quote>《医宗金鉴》："胎黄者，儿生遍体面目皆黄，其色如金，或湿热，或寒湿，在胎时已蕴毒。"<span class=src>——《医宗金鉴》</span></div><div class=plain>胎黄就是"新生儿黄疸"——皮肤发黄。关键要学会区分生理性和病理性：生理性（2-3天出现+2周退+无其他症状）+病理性（24小时内出现或超过2周不退+黄得厉害+伴异常表现）。生理性的不用治+病理性的必须治（防核黄疸伤脑）。</p><div class=mnem><strong>口诀：</strong>胎黄生理病理分，24小时要警惕；2-3天现2周退，超过时限病理寻。</div><div class=trap-box><strong>高频考点：</strong>1.生理性：2-3天出现+4-6天高峰+2周内消退。2.病理性：24小时内出现或>2周不退+胆红素>221μmol/L。3.最严重并发症——核黄疸（胆红素脑病）。4.生理性与病理性核心鉴别：出现时间+持续时间+黄疸程度+一般情况。</div></div>'},
  {id:"ek-7-2",name:"湿热郁蒸证、寒湿阻滞证、气滞血瘀证的证候、治法、方药",type:"apply",
content:'<p><strong>病理性胎黄三型辨治：</strong></p><div class=compare-table><div class=ct-left><h4>湿热郁蒸（阳黄）</h4><p><strong>证候：</strong>黄色鲜明如橘皮+发热+烦躁+呕吐+大便干+尿黄<br><strong>治法：</strong>清热利湿<br><strong>主方：</strong>茵陈蒿汤</p><p>茵陈+栀子+大黄（后下）</p></div><div class=ct-right><h4>寒湿阻滞+气滞血瘀</h4><p><strong>寒湿阻滞（阴黄）：</strong>黄色晦暗+大便溏薄灰白+四肢不温<br>治法：温中化湿<br>主方：茵陈理中汤</p><p><strong>气滞血瘀：</strong>黄色晦暗+面色青紫+腹部胀满+胁下痞块（肝脾肿大）<br>治法：化瘀消积<br>主方：血府逐瘀汤</p></div></div><div class=classic-quote>《医宗金鉴》："阳黄者，其色鲜明如橘子；阴黄者，其色晦暗如烟熏。"<span class=src>——《医宗金鉴》</span></div><div class=plain>病理性胎黄辨治三型：阳黄（色鲜明如橘皮—湿热）→茵陈蒿汤清热利湿+阴黄（色晦暗—寒湿）→茵陈理中汤温中化湿+瘀黄（色晦暗+肝脾大）→血府逐瘀汤化瘀消积。关键在于"颜色辨阴阳"——黄的鲜艳像橘子的是阳黄+黄的暗像烟熏的是阴黄。</p><div class=mnem><strong>口诀：</strong>阳黄鲜明茵陈蒿，阴黄晦暗理中汤；血瘀逐瘀消积块，胎黄三型要记牢。</div><div class=trap-box><strong>考点：</strong>1.湿热郁蒸（阳黄）→茵陈蒿汤（茵陈栀子大黄）。2.寒湿阻滞（阴黄）→茵陈理中汤（茵陈+理中汤）。3.气滞血瘀→血府逐瘀汤。4.阳黄vs阴黄：鲜明vs晦暗+实热vs虚寒。5.注意：胎黄严重需配合蓝光照射+换血疗法。</div></div>'}
]}]},

{unit:"第八单元 感冒",subunits:[{name:"小儿感冒",points:[
  {id:"ek-8-1",name:"小儿感冒的特点及夹痰、夹滞、夹惊兼证的病机",type:"detail",
content:'<p><strong>小儿感冒</strong>特点：发病率高+症状较重+传变迅速+易出现夹痰夹滞夹惊三大兼证。</p><div class=compare-table><div class=ct-left><h4>三大兼证病机</h4><p><strong>夹痰（肺常不足）：</strong><br>感冒后+肺气失宣+水液输布失常+凝聚成痰→咳嗽+喉间痰鸣</p><p><strong>夹滞（脾常不足）：</strong><br>感冒后+脾失健运+饮食不化→脘腹胀满+呕吐+泄泻</p><p><strong>夹惊（肝常有余）：</strong><br>感冒后+热扰神明+引动肝风→惊惕啼叫+睡卧不宁+抽搐</p></div><div class=ct-right><h4>三大兼证的辨证用药</h4><p><strong>夹痰：</strong>加用肃肺化痰药（如苏子+杏仁+贝母）</p><p><strong>夹滞：</strong>加用消食导滞药（如神曲+山楂+麦芽）</p><p><strong>夹惊：</strong>加用安神镇惊药（如蝉蜕+钩藤+僵蚕）</p><p>注意：小儿感冒治疗需时刻顾及兼证（防传变）。</p></div></div><div class=classic-quote>《小儿药证直诀》："小儿易为虚实，肺虚多嗽，脾虚多泻，肝强多搐。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>小儿感冒和成人感冒最大的不同就是"三个夹"：夹痰（咳嗽有痰）+夹滞（拉肚子）+夹惊（抽筋）。这是因为小儿"肺脾不足+肝有余"的生理特点决定的。治小儿感冒不能只发汗解表+要同时处理并发症。</p><div class=mnem><strong>口诀：</strong>小儿感冒三夹多，夹痰宣肺夹滞消；夹惊安神加蝉蜕，三脏不足防传变。</div><div class=trap-box><strong>高频考点：</strong>1.小儿感冒三大兼证——夹痰（肺）+夹滞（脾）+夹惊（肝）。2.夹痰病机——肺常不足+津凝为痰。3.夹滞病机——脾常不足+运化失职。4.夹惊病机——肝常有余+热扰肝风。5.治疗注意：主方（银翘散/荆防败毒散等）+加味兼证药。</div></div>'},
  {id:"ek-8-2",name:"风寒、风热、暑邪感冒及兼证的证候、治法、方药",type:"apply",
content:'<p><strong>小儿感冒三型辨治：</strong></p><div class=compare-table><div class=ct-left><h4>风寒感冒</h4><p><strong>证候：</strong>恶寒发热无汗+鼻塞流清涕+咳嗽痰清稀+头痛+不渴<br><strong>治法：</strong>辛温解表<br><strong>主方：</strong>荆防败毒散</p><p><strong>风热感冒</strong><br><strong>证候：</strong>发热重恶寒轻+有汗+鼻塞流黄涕+咽红肿痛+口渴<br><strong>治法：</strong>辛凉解表<br><strong>主方：</strong>银翘散</p></div><div class=ct-right><h4>暑邪感冒</h4><p><strong>证候：</strong>高热无汗+头痛+身重困倦+胸闷泛恶+食少+呕吐+腹泻+苔腻<br><strong>治法：</strong>清暑解表<br><strong>主方：</strong>新加香薷饮</p><p>兼证加味：<br>夹痰→加苏子+杏仁<br>夹滞→加山楂+神曲<br>夹惊→加钩藤+蝉蜕</p></div></div><div class=classic-quote>《幼幼集成》："小儿伤风伤寒，但当解表，不可妄下。"<span class=src>——《幼幼集成》</span></div><div class=plain>小儿感冒辨治比成人简单——风寒（怕冷无汗清涕）→荆防败毒散+风热（发热重涕黄咽痛）→银翘散+暑湿（夏季高热闷吐泻）→新加香薷饮。注意小儿感冒传变快—一定要早治+防传变成肺炎咳嗽。</p><div class=mnem><strong>口诀：</strong>风寒荆防败毒散，风热银翘散解表；暑邪新加香薷饮，夹痰夹滞夹惊消。</div></div>'}
]}]},

{unit:"第九单元 咳嗽",subunits:[{name:"小儿咳嗽",points:[{id:"ek-9-1",name:"咳嗽的病因病机及风寒、风热、痰热、阴虚咳嗽的证候治法方药",type:"apply",
content:'<p><strong>小儿咳嗽</strong>是小儿肺系疾病最常见的症状。病因：外感（风+寒+热）或内伤（痰+食+虚）。病位在肺+涉及脾（小儿脾常不足+痰从脾生）。</p><div class=compare-table><div class=ct-left><h4>外感咳嗽</h4><p><strong>风寒咳嗽：</strong>咳嗽频作+声重+痰白清稀+鼻塞+恶寒<br>→ <strong>杏苏散</strong>疏风散寒+宣肺止咳</p><p><strong>风热咳嗽：</strong>咳嗽不爽+痰黄稠+咽红肿痛+口渴<br>→ <strong>桑菊饮</strong>疏风清热+宣肺止咳</p></div><div class=ct-right><h4>内伤咳嗽</h4><p><strong>痰热咳嗽：</strong>咳嗽痰多色黄+喉间痰鸣+发热+口渴+便干<br>→ <strong>清金化痰汤</strong>清肺化痰</p><p><strong>阴虚咳嗽：</strong>干咳无痰或少痰+午后潮热+手足心热+盗汗<br>→ <strong>沙参麦冬汤</strong>滋阴润肺+止咳</p></div></div><div class=classic-quote>《小儿药证直诀》："咳嗽者，肺感微寒，入于肺经而咳。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>小儿咳嗽四型——从"新咳"到"久咳"：风寒咳→杏苏散+风热咳→桑菊饮+痰热咳→清金化痰汤+阴虚咳→沙参麦冬汤。外感咳嗽要"宣"（散发）+内伤咳嗽要"清"或"润"。小儿咳嗽要特别注意"喉间痰鸣"—痰多难咯易堵气道。</p><div class=mnem><strong>口诀：</strong>咳嗽四型风寒杏苏+风热桑菊+痰热清金+阴虚沙参麦冬。</div><div class=trap-box><strong>考点：</strong>1.风寒咳嗽→杏苏散（苏叶杏仁前胡桔梗枳壳橘红半夏茯苓甘草）。2.风热咳嗽→桑菊饮（桑叶菊花杏仁连翘薄荷桔梗芦根甘草）。3.痰热咳嗽→清金化痰汤（栀子黄芩知母贝母瓜蒌桔梗桑皮麦冬橘红茯苓甘草）。4.阴虚咳嗽→沙参麦冬汤（沙参麦冬玉竹天花粉扁豆桑叶甘草）。</div></div>'}]
}]},

{unit:"第十单元 肺炎喘嗽",subunits:[{name:"肺炎喘嗽",points:[{id:"ek-10-1",name:"肺炎喘嗽的临床主症、病因病机及辨证论治",type:"apply",
content:'<p><strong>肺炎喘嗽</strong>是小儿常见肺系疾病。主症：发热+咳嗽+气促+鼻煽（鼻翼煽动）。相当于小儿肺炎（支气管肺炎+支原体肺炎等）。</p><div class=compare-table><div class=ct-left><h4>辨证分型（常证）</h4><p><strong>风寒闭肺：</strong>恶寒发热无汗+咳嗽气急+痰白清稀<br>→ <strong>华盖散</strong></p><p><strong>风热闭肺：</strong>发热恶风+咳嗽痰黄+咽红+口渴<br>→ <strong>银翘散</strong>合<strong>麻杏石甘汤</strong></p><p><strong>痰热闭肺：</strong>发热+咳嗽痰鸣+气急鼻煽+便秘<br>→ <strong>五虎汤</strong>合<strong>葶苈大枣泻肺汤</strong></p><p><strong>毒热闭肺：</strong>高热持续+剧烈咳嗽+喘憋+烦躁<br>→ <strong>黄连解毒汤</strong>合<strong>麻杏石甘汤</strong></p></div><div class=ct-right><h4>变证+恢复期</h4><p><strong>阴虚肺热（恢复期）：</strong>低热+干咳少痰+面色潮红+手足心热<br>→ <strong>沙参麦冬汤</strong></p><p><strong>肺脾气虚（恢复期）：</strong>低热+咳嗽无力+神疲+食少+易汗<br>→ <strong>人参五味子汤</strong></p><p><strong>变证：</strong><br>心阳虚衰→面色苍白+肢冷+脉疾→参附龙牡救逆汤<br>内陷厥阴→神昏+抽搐→羚角钩藤汤</p></div></div><div class=classic-quote>《幼科发挥》："肺主喘嗽，痰塞胸膈，肺胀满，胸高气急，鼻翼煽动，此肺闭也。"<span class=src>——《幼科发挥》</span></div><div class=plain>肺炎喘嗽是小儿最常见的急症之一——"肺炎"是西医名+"喘嗽"是中医名。四大主症"发热+咳嗽+气促+鼻煽"缺一不可。治疗总则是"宣肺开闭+化痰平喘"。注意变证——心阳虚衰（合并心衰）和内陷厥阴（合并脑病）——这两种情况需要中西医结合抢救！</p><div class=mnem><strong>口诀：</strong>肺炎喘嗽热咳喘煽，风寒华盖风热银翘麻杏；痰热五虎葶苈泻，毒热黄连解毒合麻杏。</div><div class=trap-box><strong>高频考点：</strong>1.肺炎喘嗽四大主症——发热+咳嗽+气促+鼻煽。2.风寒闭肺→华盖散（麻黄杏仁苏子橘红赤苓桑皮甘草）。3.风热闭肺→银翘散合麻杏石甘汤。4.痰热闭肺→五虎汤（麻黄杏仁石膏甘草细茶）合葶苈大枣泻肺汤。5.变证：心阳虚衰→参附龙牡救逆汤+内陷厥阴→羚角钩藤汤。6.注意：重症需中西医结合治疗（吸氧+抗感染+强心）。</div></div>'}]
}]},

{unit:"第十一单元 哮喘",subunits:[{name:"小儿哮喘",points:[{id:"ek-11-1",name:"哮喘的病因病机、诊断标准及发作期与缓解期的辨证论治",type:"apply",
content:'<p><strong>哮喘</strong>是反复发作的哮鸣咳嗽气喘。病机：内因（痰饮留伏）+外因（外感+接触过敏原+饮食+情志）。"宿痰伏肺+遇感触发"。</p><div class=compare-table><div class=ct-left><h4>发作期辨治</h4><p><strong>寒性哮喘：</strong>咳喘哮鸣+痰白清稀+形寒无汗+舌淡苔白<br>→ <strong>小青龙汤</strong>合<strong>射干麻黄汤</strong></p><p><strong>热性哮喘：</strong>咳喘哮鸣+痰黄稠+面红+口渴+便秘<br>→ <strong>麻杏石甘汤</strong>合<strong>五虎汤</strong></p><p><strong>外寒内热：</strong>恶寒+痰黄+发热+烦躁<br>→ <strong>大青龙汤</strong></p></div><div class=ct-right><h4>缓解期辨治</h4><p><strong>肺脾气虚：</strong>气短+易汗+食少+神疲+易感冒<br>→ <strong>玉屏风散</strong>合<strong>人参五味子汤</strong></p><p><strong>脾肾阳虚：</strong>气短+形寒肢冷+腰膝酸软+夜尿多<br>→ <strong>金匮肾气丸</strong></p><p><strong>肺肾阴虚：</strong>干咳少痰+手足心热+盗汗+潮热<br>→ <strong>麦味地黄丸</strong></p></div></div><div class=classic-quote>《幼科发挥》："发则哮吼喘急，坐卧不得。有因外感，有因痰饮，有因寒包热。"<span class=src>——《幼科发挥》</span></div><div class=plain>小儿哮喘核心病机——"宿痰伏肺"（痰留在肺里像定时炸弹）+遇到外邪就发作。发作期治"标"（化痰平喘）→缓解期治"本"（补肺脾肾）。发作期分寒热：小青龙汤（寒）+麻杏石甘汤（热）。缓解期调体质：肺脾虚用玉屏风+肾虚用肾气丸。注意：儿童哮喘早期治疗+很多可以治愈（不像成人哮喘难断根）。</p><div class=mnem><strong>口诀：</strong>哮喘宿痰伏肺根，发作小青龙麻杏石；缓解玉屏肾气丸，儿童早治可断根。</div><div class=trap-box><strong>考点：</strong>1.病机关键词——"宿痰伏肺+遇感触发"。2.发作期寒哮→小青龙汤合射干麻黄汤。3.发作期热哮→麻杏石甘汤合五虎汤。4.缓解期肺脾气虚→玉屏风散合人参五味子汤。5.缓解期肾虚→金匮肾气丸/麦味地黄丸。6.诊断：反复发作+哮鸣气促+用药可缓解。7.冬病夏治（三伏贴）是小儿哮喘的特色疗法。</div></div>'}]
}]},

{unit:"第十二单元 鹅口疮",subunits:[{name:"鹅口疮",points:[{id:"ek-12-1",name:"鹅口疮的概念及心脾积热证、虚火上浮证的证候治法方药",type:"detail",
content:'<p><strong>鹅口疮</strong>是口腔舌面布满白屑+状如鹅口。多见于新生儿+久病体弱者+长期使用抗生素者。白色念珠菌感染。</p><div class=compare-table><div class=ct-left><h4>心脾积热</h4><p><strong>证候：</strong>口腔白屑堆积+周围鲜红+面赤+烦躁+吮乳时啼哭+大便干+尿黄<br><strong>治法：</strong>清心泄脾<br><strong>主方：</strong>清热泻脾散</p></div><div class=ct-right><h4>虚火上浮</h4><p><strong>证候：</strong>口腔白屑散在+周围不红+形瘦+颧红+手足心热+口干不渴<br><strong>治法：</strong>滋阴降火<br><strong>主方：</strong>知柏地黄丸</p></div></div><div class=classic-quote>《外科正宗》："鹅口疮，满口皆白斑雪片，甚则咽间叠叠肿起。"<span class=src>——《外科正宗》</span></div><div class=plain>鹅口疮就是"嘴巴里长白色豆腐渣样的东西"——真菌（白色念珠菌）感染。最常见于新生儿（产道感染）和长期用抗生素或激素的患儿。中医分两型：红肿明显（心脾积热）→清热泻脾散+白屑散在不红（虚火上浮）→知柏地黄丸。外治可以用冰硼散涂口。</p><div class=mnem><strong>口诀：</strong>鹅口白屑满口霜，心脾积热泻脾散；虚火知柏地黄丸，冰硼外涂疗效良。</div></div>'}]
}]},

{unit:"第十三单元 口疮",subunits:[{name:"口疮",points:[{id:"ek-13-1",name:"口疮的概念及风热乘脾证、心火上炎证、虚火上浮证的证候治法方药",type:"detail",
content:'<p><strong>口疮</strong>是口颊+舌部+齿龈等处黄白色溃疡。相当于复发性口腔溃疡（阿弗他溃疡）。与鹅口疮鉴别：鹅口疮是一片白屑+口疮是单个溃疡点。</p><div class=compare-table><div class=ct-left><h4>风热乘脾（脾胃积热）</h4><p><strong>证候：</strong>口疮周围红肿+数目多+发热+口臭+便秘+苔黄<br><strong>治法：</strong>疏风清热+通便泄火<br><strong>主方：</strong>凉膈散</p><p><strong>心火上炎</strong><br><strong>证候：</strong>舌上溃疡+色红疼痛+心烦+夜啼+尿黄<br><strong>治法：</strong>清心泻火<br><strong>主方：</strong>泻心导赤汤</p></div><div class=ct-right><h4>虚火上浮</h4><p><strong>证候：</strong>口疮反复发作+周围不红+疼痛不重+口干不渴+手足心热<br><strong>治法：</strong>滋阴降火<br><strong>主方：</strong>知柏地黄丸</p><p>注意：<br>鹅口疮→白屑成片+似乳块<br>口疮→单个溃疡+黄白点+疼痛明显</p></div></div><div class=classic-quote>《小儿药证直诀》："口疮者，心脾积热也。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>口疮就是"嘴巴里长溃疡"——鹅口疮是"一片白"+口疮是"几个疮口"。小儿口疮最常见的原因是"上火"（心脾积热）。三个证型：风热乘脾（发热便秘+凉膈散）+心火上炎（舌上溃疡+泻心导赤汤）+虚火（反复发作+知柏地黄丸）。外治可用冰硼散+锡类散涂患处。</p><div class=mnem><strong>口诀：</strong>口疮溃疡痛难忍，风热凉膈心导赤；虚火知柏地黄丸，外涂冰硼锡类散。</div><div class=trap-box><strong>考点：</strong>1.风热乘脾→凉膈散（大黄芒硝栀子黄芩连翘薄荷竹叶甘草）。2.心火上炎→泻心导赤汤（黄连生地木通甘草竹叶）。3.虚火上浮→知柏地黄丸。4.鹅口疮vs口疮鉴别：白屑成片（鹅口）vs单个溃疡（口疮）。5.外用药：冰硼散+锡类散。</div></div>'}
]}]},

{unit:"第十四单元 泄泻",subunits:[{name:"小儿泄泻",points:[
  {id:"ek-14-1",name:"泄泻的病因病机",type:"detail",
content:'<p><strong>泄泻</strong>是小儿最常见的脾胃病。病因：外感（风寒暑湿）+内伤（乳食不节）+脾胃虚弱。病机：脾失健运+水湿不化+清浊不分+下注大肠。病位在脾胃+与大小肠有关。小儿"脾常不足"→易泄泻→泄泻过多→伤阴损阳→变证。</p><div class=compare-table><div class=ct-left><h4>病因病机要点</h4><p><strong>外感：</strong>风寒暑湿+脾失运化+水湿下注</p><p><strong>乳食：</strong>喂养不当+伤食积滞+脾伤不运</p><p><strong>脾虚：</strong>脾胃虚弱+运化失职+清浊不分</p><p><strong>变证：</strong><br>伤阴→眼眶凹陷+皮肤干燥+尿少<br>伤阳→四肢厥冷+面色苍白+脉微</p></div><div class=ct-right><h4>治疗原则</h4><p>总则：运脾化湿</p><p>·伤食→消食导滞<br>·风寒→疏风散寒<br>·湿热→清热利湿<br>·脾虚→健脾益气<br>·脾肾阳虚→温补脾肾</p><p>变证：<br>气阴两伤→益气养阴<br>阴竭阳脱→回阳救逆</p><p>注意：小儿泄泻最怕脱水+需防电解质紊乱</p></div></div><div class=classic-quote>《幼科发挥》："泄泻之本，无不由于脾胃。"<span class=src>——《幼科发挥》</span></div><div class=plain>小儿泄泻就是"拉肚子"—是6个月~2岁婴幼儿最常见的病。小儿"脾常不足"+消化能力弱+稍微吃不对或着凉就拉肚子。拉多了最怕"脱水"（伤阴）和"休克"（伤阳）——这是泄泻变证（最危险的情况）。治疗原则"运脾化湿"。</p><div class=mnem><strong>口诀：</strong>泄泻脾虚湿盛因，伤食风寒湿热分；脾虚脾肾阳虚证，变证阴竭阳脱循。</div></div>'},
  {id:"ek-14-2",name:"伤食泻、风寒泻、湿热泻、脾虚泻、脾肾阳虚泻的证候、治法、方药",type:"apply",
content:'<p><strong>小儿泄泻五型辨治：</strong></p><div class=compare-table><div class=ct-left><h4>伤食泻</h4><p>大便稀溏夹乳块/食物残渣+气味酸腐+脘腹胀满+呕吐+夜卧不宁<br>→ <strong>保和丸</strong>消食化积</p><p><strong>风寒泻</strong><br>大便清稀夹泡沫+色淡+臭气轻+肠鸣腹痛+恶寒<br>→ <strong>藿香正气散</strong></p><p><strong>湿热泻</strong><br>大便水样/蛋花汤样+色黄褐+气味秽臭+肛门灼热+口渴<br>→ <strong>葛根黄芩黄连汤</strong></p></div><div class=ct-right><h4>脾虚泻</h4><p>大便稀溏+色淡不臭+食后即泻+面色萎黄+神疲+食少<br>→ <strong>参苓白术散</strong></p><p><strong>脾肾阳虚泻</strong><br>久泻不止+五更泄泻+大便清冷+完谷不化+面色苍白+畏寒肢冷<br>→ <strong>附子理中汤</strong>合<strong>四神丸</strong></p></div></div><div class=classic-quote>《医宗金鉴》："小儿泄泻须分型，伤食保和风寒藿香，湿热葛根芩连用，脾虚参苓白术，脾肾阳虚附理四神。"<span class=src>——《医宗金鉴》</span></div><div class=plain>小儿泄泻五型鉴别从"气味"和"性状"入手：酸腐臭→伤食（保和丸）+泡沫清稀→风寒（藿香正气）+蛋花汤样臭→湿热（葛根芩连汤）+不臭食后泻→脾虚（参苓白术散）+五更冷泻→脾肾阳虚（附子理中+四神）。记住一个规律：伤食最臭+湿热最急+脾虚最缠绵。</p><div class=mnem><strong>口诀：</strong>伤食保和风寒藿香，湿热葛根芩连汤；脾虚参苓白术散，阳虚附理四神方。</div><div class=trap-box><strong>高频考点：</strong>1.伤食泻→保和丸（山楂神曲半夏茯苓陈皮连翘莱菔子）。2.风寒泻→藿香正气散（藿香苏叶白芷大腹皮茯苓白术半夏曲陈皮厚朴桔梗甘草）。3.湿热泻→葛根黄芩黄连汤（葛根黄芩黄连甘草）。4.脾虚泻→参苓白术散。5.脾肾阳虚→附子理中汤合四神丸。6.补水——世界卫生组织推荐口服补液盐(ORS)预防脱水。</div></div>'},
  {id:"ek-14-3",name:"气阴两伤、阴竭阳脱变证的证候、治法、方药",type:"apply",
content:'<p><strong>泄泻变证</strong>——急重症！小儿泄泻不止+水电解质紊乱。</p><div class=compare-table><div class=ct-left><h4>气阴两伤（轻-中度脱水）</h4><p><strong>证候：</strong>泻下无度+精神萎靡+眼眶囟门凹陷+皮肤干燥弹性差+尿少+口干+唇红+手足心热</p><p><strong>治法：</strong>益气养阴<br><strong>主方：</strong>人参乌梅汤</p></div><div class=ct-right><h4>阴竭阳脱（重度脱水+休克）</h4><p><strong>证候：</strong>泻下不止+精神萎靡+表情淡漠+面色青灰/苍白+四肢厥冷+冷汗出+脉微细欲绝</p><p><strong>治法：</strong>回阳救逆固脱<br><strong>主方：</strong>生脉散合参附龙牡救逆汤</p><p>注意：需配合补液+纠正电解质紊乱！</p></div></div><div class=classic-quote>《小儿药证直诀》："吐泻久不止，津液亡失，精神困顿，乃虚极之候。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>泄泻变证是"拉肚子拉到脱水休克"——这是儿科急症！轻到中度脱水（气阴两伤）→人参乌梅汤+重度脱水休克（阴竭阳脱）→生脉散合参附龙牡救逆汤。但这些变证光靠中药不够+必须配合西医补液+纠正电解质紊乱！</p><div class=mnem><strong>口诀：</strong>变证气阴人参乌梅汤，阴竭阳脱生脉参附龙牡；泻甚脱水急补液，中西医结合救命忙。</div><div class=trap-box><strong>考点：</strong>1.气阴两伤→人参乌梅汤（人参乌梅木瓜山药莲子甘草）。2.阴竭阳脱→生脉散合参附龙牡救逆汤（人参麦冬五味子+附子龙骨牡蛎）。3.最重要的是配合补液+预防脱水。4.泄泻变证是儿科危重症+需住院治疗。5.ORS口服补液盐的配制和使用。</div></div>'}
]}]},
'''

after = c[:idx6] + UNITS + c[idx15:]

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(after)

print(f"Done. Size: {len(after)} bytes (was {len(c)} bytes)")
