#!/usr/bin/env python3
"""fill-erke-unit15-23.py — 填充 s8 第十五~二十三单元"""
TARGET = '/sessions/compassionate-hopeful-thompson/mnt/syllabus/subjects/s8-erke.js'

with open(TARGET, 'r', encoding='utf-8') as f:
    c = f.read()

idx15 = c.find('{unit:"第十五单元')
idx24 = c.find('{unit:"第二十四单元')

UNITS = r'''{unit:"第十五单元 厌食",subunits:[{name:"厌食",points:[{id:"ek-15-1",name:"厌食的概念及辨证论治",type:"apply",
content:'<p><strong>厌食</strong>是小儿较长时期食欲不振+食量减少+厌恶进食。可伴面色萎黄+形体偏瘦+但精神尚可。与疳证区别：厌食精神好+疳证消瘦明显。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>脾失健运：</strong>食欲不振+食量少+面色少华+形体偏瘦+舌苔薄白<br>→ <strong>不换金正气散</strong>运脾开胃</p><p><strong>脾胃气虚：</strong>不思进食+食少便溏+面色萎黄+神疲+易出汗+舌淡苔白<br>→ <strong>异功散</strong>益气健脾</p><p><strong>脾胃阴虚：</strong>不思进食+食少饮多+皮肤干燥+手足心热+大便干+舌红少苔<br>→ <strong>养胃增液汤</strong>滋阴养胃</p></div><div class=ct-right><h4>鉴别要点</h4><p>厌食→不思食但精神可+病程长+预后好</p><p>积滞→伤食史+腹胀满+呕吐酸腐+病程短</p><p>疳证→形体明显消瘦+面色萎黄+精神差+影响发育</p></div></div><div class=classic-quote>《幼科发挥》："厌食者，胃气不和，不能纳谷也。"<span class=src>——《幼科发挥》</span></div><div class=plain>厌食就是"不爱吃饭"——三个证：脾失健运（最常见+舌苔厚腻）→不换金正气散开胃+脾胃气虚（乏力便溏）→异功散健脾+脾胃阴虚（干瘦大便干）→养胃增液汤滋阴。厌食调理很重要：定时吃饭+少吃零食+不强迫进食。</p><div class=mnem><strong>口诀：</strong>厌食不换金正气，脾虚异功散妙，阴虚养胃增液汤，三型分清胃口调。</div></div>'}]
}]},

{unit:"第十六单元 积滞",subunits:[{name:"积滞",points:[{id:"ek-16-1",name:"积滞的概念及辨证论治",type:"apply",
content:'<p><strong>积滞</strong>是小儿内伤乳食+食积不化+停聚中脘。特征：不思乳食+脘腹胀满+呕吐酸腐+大便酸臭。相当于"消化不良"或"急性胃肠炎"。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>乳食内积（实证）：</strong>不思乳食+脘腹胀满+呕吐酸腐+夜卧不宁+大便酸臭+苔厚腻<br>→ <strong>消乳丸</strong>（乳积）或<strong>保和丸</strong>（食积）</p><p><strong>脾虚夹积（虚中夹实）：</strong>不思乳食+食则饱胀+腹满喜按+面色萎黄+神疲+大便稀溏酸臭<br>→ <strong>健脾丸</strong></p></div><div class=ct-right><h4>积滞与厌食、疳证</h4><p>三者的关系：积滞→厌食→疳证（一个比一个重）</p><p>·积滞：伤食后+腹胀腹痛+呕吐酸腐<br>·厌食：长期食少+但无腹胀+精神可<br>·疳证：积滞日久+消瘦明显+影响发育</p></div></div><div class=classic-quote>《幼科发挥》："小儿积滞，由乳食不节，停滞中脘，传化失常。"<span class=src>——《幼科发挥》</span></div><div class=plain>积滞就是"吃多了积食"——肚子胀+吐酸水+拉酸臭大便。实证用消法（保和丸/消乳丸）+虚中夹实用消补兼施（健脾丸）。积滞是小儿脾胃病的"桥梁"——厌食（轻）→积滞（中）→疳证（重）依次发展。治积滞的关键是"消食导滞"+还要控制饮食（饿一两顿比吃药还管用）。</p><div class=mnem><strong>口诀：</strong>积滞乳食内停，保和消乳实证行；脾虚夹积健脾丸，消补兼施积滞平。</div><div class=trap-box><strong>考点：</strong>1.乳食内积（实）→消乳丸/保和丸。2.脾虚夹积（虚实夹杂）→健脾丸（参术苓草+山楂麦芽神曲陈皮砂仁）。3.厌食→积滞→疳证是逐步加重的"脾胃病三部曲"。4.积滞有伤食史+伴腹胀吐酸。</div></div>'}]
}]},

{unit:"第十七单元 疳证",subunits:[{name:"疳证",points:[
  {id:"ek-17-1",name:'疳证的概念及"疳"的含义',type:"concept",
content:'<p><strong>疳证</strong>是小儿脾胃受损+气血耗伤+形体羸瘦。疳有两种含义：一"疳者甘也"（过食甘腻+伤脾生疳）二"疳者干也"（气血干涸+形体干瘦）。<br>特点：形体消瘦+面色萎黄+头发稀疏+精神萎靡+饮食异常+影响生长发育。</p><div class=compare-table><div class=ct-left><h4>"疳"的两层含义</h4><p><strong>疳者甘也——病因说</strong><br>过食肥甘厚味+损伤脾胃+运化失常→成疳</p><p><strong>疳者干也——病机说</strong><br>津液干涸+气血亏耗+形体干瘦→成疳</p></div><div class=ct-right><h4>疳证特点</h4><p>·病程长+难治愈<br>·严重影响生长发育<br>·古代儿科四大要证之一（疹+痘+惊+疳）<br>·相当于现代：蛋白质-能量营养不良</p></div></div><div class=classic-quote>《小儿药证直诀》："疳皆脾胃病，亡津液之所作也。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>"疳"字有两层意思：病因上"疳者甘也"——吃太多甜腻的东西伤了脾胃+结果上"疳者干也"——瘦得干巴巴。钱乙说"疳皆脾胃病+亡津液之所作也"——核心是脾胃坏了+身体干枯了。古代儿科四大证"疹痘惊疳"+疳证是营养不良+与贫穷有关+现在发病率降低但仍有。</p><div class=mnem><strong>口诀：</strong>疳者甘也过食伤，疳者干也瘦干黄；脾胃受损津液耗，古代四大要证当。</div></div>'},
  {id:"ek-17-2",name:"厌食、积滞、疳证的鉴别",type:"compare",
content:'<p><strong>厌食vs积滞vs疳证</strong>——脾胃病"三步曲"轻重不同。</p><div class=compare-table><div class=ct-left><h4>三证鉴别</h4><p><strong>厌食（轻）：</strong><br>·长期不思食+食量少<br>·无腹胀腹痛+无呕吐<br>·形体偏瘦+精神可+活动如常</p><p><strong>积滞（中）：</strong><br>·有伤食史<br>·脘腹胀满+呕吐酸腐+大便酸臭<br>·形体无明显消瘦</p></div><div class=ct-right><h4>疳证（重）</h4><p>·积滞日久+或喂养不当<br>·明显消瘦+皮下脂肪薄<br>·面色萎黄+头发稀疏<br>·精神萎靡+爱哭闹<br>·可伴各兼证（眼疳+口疳+疳肿胀）<br>·影响生长发育</p></div></div><div class=plain>记住"三步曲"：厌食（不爱吃但精神好）→积滞（吃多了胀吐酸臭）→疳证（瘦得皮包骨+精神萎靡）。疳证是最严重的+相当于营养不良+需要长期调理。三个病的治疗都在"脾胃"——从调脾（厌食）→消积（积滞）→补养（疳证）逐步加深。</p></div>'},
  {id:"ek-17-3",name:"疳气证、干疳证、疳积证及各兼证的证候、治法、方药",type:"apply",
content:'<p><strong>疳证三期辨治（疳气→疳积→干疳）：</strong></p><div class=compare-table><div class=ct-left><h4>疳气证（轻）</h4><p>形体略瘦+面色萎黄+食欲不振+大便不调+精神较差<br>→ <strong>资生健脾丸</strong>健脾和胃</p><p><strong>疳积证（中）</strong><br>形体明显消瘦+肚腹膨胀+面色萎黄+毛发稀疏+烦躁+揉眉挖鼻+食欲异常<br>→ <strong>肥儿丸</strong>消积理脾</p></div><div class=ct-right><h4>干疳证（重）</h4><p>极度消瘦+皮肤干瘪+大肉已脱+精神萎靡+啼哭无力+腹凹如舟<br>→ <strong>八珍汤</strong>补益气血</p><p><strong>兼证：</strong><br>·眼疳（夜盲）→石斛夜光丸<br>·口疳（口疮）→泻心导赤散<br>·疳肿胀（水肿）→五苓散+五皮饮</p></div></div><div class=classic-quote>《医宗金鉴》："疳证有五：心肝脾肺肾也。总属脾胃病+五脏皆可及。"<span class=src>——《医宗金鉴》</span></div><div class=plain>疳证分三期：疳气（轻度营养不良）+疳积（中度+肚子大四肢细）→干疳（重度+皮包骨头）。治疗逐步加重：疳气健脾胃（资生健脾丸）+疳积消积理脾（肥儿丸）+干疳补益（八珍汤）。注意兼证：眼疳（缺维生素A夜盲）+口疳（口腔溃疡）+疳肿胀（水肿）。</p><div class=mnem><strong>口诀：</strong>疳气资生健脾丸，疳积肥儿丸消积；干疳八珍补气血，兼证眼口肿胀四。</div><div class=trap-box><strong>高频考点：</strong>1.疳气→资生健脾丸（参术苓草山药莲子薏仁扁豆砂仁麦芽山楂等）。2.疳积→肥儿丸（人参白术茯苓黄连胡黄连神曲麦芽山楂芦荟甘草）。3.干疳→八珍汤。4.兼证：眼疳→石斛夜光丸+口疳→泻心导赤散+疳肿胀→五苓散合五皮饮。5.疳证三期是逐渐加重的过程+治疗也逐步加强。</div></div>'}
]}]},

{unit:"第十八单元 汗证",subunits:[{name:"汗证",points:[{id:"ek-18-1",name:"汗证的概念及辨证论治",type:"detail",
content:'<p><strong>小儿汗证</strong>是小儿在安静状态下（如入睡+静坐）全身或局部出汗过多。自汗（清醒时汗出）+盗汗（入睡后汗出+醒后汗止）。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肺卫不固：</strong>自汗为主+恶风+易感冒+神疲+面色少华+舌淡<br>→ <strong>玉屏风散</strong>合<strong>牡蛎散</strong></p><p><strong>营卫失调：</strong>自汗+汗出遍身+恶风+不发热+舌淡红苔白<br>→ <strong>黄芪桂枝五物汤</strong></p><p><strong>气阴亏虚：</strong>盗汗为主+神疲+口干+手足心热+舌红少苔<br>→ <strong>生脉散</strong>合<strong>当归六黄汤</strong></p><p><strong>湿热迫蒸：</strong>自汗+汗出肤热+汗渍色黄+口臭+便秘+苔黄腻<br>→ <strong>泻黄散</strong></p></div><div class=ct-right><h4>鉴别要点</h4><p>生理性出汗→小儿代谢旺盛+入睡后头额微汗+无其他不适（正常）</p><p>病理性出汗→安静状态下仍多汗+伴其他症状</p><p>注意：盗汗不一定就是"虚证"+湿热也可盗汗</p></div></div><div class=classic-quote>《小儿药证直诀》："小儿睡中汗出，如盗贼之窃，故名盗汗。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>小儿汗证就是"不正常出汗"——分了四种证型。最常见的是肺卫不固（爱感冒出虚汗）→玉屏风散。注意生理性和病理性的区别：小儿新陈代谢旺+入睡时头部微汗是正常的+不需要治疗。</p><div class=mnem><strong>口诀：</strong>汗证肺卫玉屏风，营卫黄芪桂枝通；气阴生脉归六黄，湿热泻黄疗效宏。</div></div>'}]
}]},

{unit:"第十九单元 惊风",subunits:[{name:"惊风",points:[
  {id:"ek-19-1",name:"惊风的概念、四证八候及急慢惊风的区别",type:"compare",
content:'<p><strong>惊风</strong>是小儿抽搐+神昏的危重病证。分急惊风和慢惊风两类。古代儿科四大证之一（疹痘惊疳）。</p><div class=compare-table><div class=ct-left><h4>四证八候</h4><p><strong>四证：</strong>痰+热+惊+风（急惊风的四大病理因素）<br>·痰→痰壅<br>·热→热盛<br>·惊→惊惕<br>·风→抽搐</p><p><strong>八候：</strong>搐+搦+掣+颤+反+引+窜+视<br>·搐—肘臂伸缩<br>·搦—十指开合<br>·掣—肩头相扑<br>·颤—手足动摇<br>·反—角弓反张<br>·引—手足牵引<br>·窜—目上视<br>·视—目斜视</p></div><div class=ct-right><h4>急惊风vs慢惊风</h4><p><strong>急惊风（实热）：</strong><br>·发病急+来势猛<br>·抽搐有力+频率高<br>·高热+神昏+面赤<br>·牙关紧闭+痰鸣<br>·多见于3岁以下</p><p><strong>慢惊风（虚寒）：</strong><br>·发病缓+病程长<br>·抽搐无力+幅度小<br>·低热或无热+神疲<br>·面色苍白+露睛<br>·多见于大龄儿或久病后</p></div></div><div class=classic-quote>《小儿药证直诀》："急惊风，阳热盛也；慢惊风，阴寒盛也。"<span class=src>——《小儿药证直诀》</span></div><div class=plain>惊风就是"小孩抽风"。急惊风病情急+高热抽筋+像火烧（阳热）+慢惊风病程长+低热无力+像冰冻（虚寒）。"四证"（痰热惊风）和"八候"（搐搦掣颤反引窜视）是必考内容。八候口诀："搐搦掣颤反引窜视+肘指肩手弓牵眼斜"。</p><div class=mnem><strong>口诀：</strong>惊风四证痰热惊风，八候搐搦掣颤反引窜视；急惊暴热实+慢惊虚寒缓。</div><div class=trap-box><strong>高频考点：</strong>1.四证——痰+热+惊+风。2.八候——搐+搦+掣+颤+反+引+窜+视。3.急惊风→实热阳证（发病急+高热+抽搐有力）。4.慢惊风→虚寒阴证（发病缓+低热+抽搐无力）。5.治疗原则：急惊风清热豁痰镇惊熄风+慢惊风温补脾肾回阳救逆。</div></div>'},
  {id:"ek-19-2",name:"急惊风四证及治疗原则",type:"apply",
content:'<p><strong>急惊风治疗原则：</strong>清热+豁痰+镇惊+熄风——针对"四证"。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>风热动风（外感）：</strong>发热+头痛+咳嗽+烦躁+突然抽搐<br>→ <strong>银翘散</strong>疏风清热+熄风</p><p><strong>气营两燔（热极）：</strong>高热+神昏+抽搐+烦躁+口渴<br>→ <strong>清瘟败毒饮</strong>清气凉营+熄风</p><p><strong>邪陷心肝（惊厥）：</strong>高热+神昏+反复抽搐+头痛呕吐<br>→ <strong>羚角钩藤汤</strong>清肝熄风+镇惊</p><p><strong>湿热疫毒（痢疾）：</strong>高热+抽搐+神昏+腹痛+大便脓血<br>→ <strong>黄连解毒汤</strong>合<strong>白头翁汤</strong></p></div><div class=ct-right><h4>急救与调护</h4><p>急惊风发作时：<br>1.保持安静+减少刺激<br>2.侧卧+解开衣领+防窒息<br>3.牙关紧闭时用压舌板垫入+防咬舌<br>4.立即指掐人中+合谷+涌泉</p><p>配合西医：<br>·退热（布洛芬/对乙酰氨基酚）<br>·止痉（地西泮/苯巴比妥）<br>·吸氧</p></div></div><div class=classic-quote>《幼科发挥》："急惊风，大惊卒恐，宜以搐药止之，以凉药下之。"<span class=src>——《幼科发挥》</span></div><div class=plain>急惊风治疗四法（对应四证）：清热+豁痰+镇惊+熄风。外感风热抽→银翘散+高热抽→清瘟败毒饮+反复抽昏迷→羚角钩藤汤（这是最经典的方）+痢疾抽→黄连解毒汤。注意惊风发作时的急救处理：侧卧防窒息+掐人中+保持安静。高热惊厥一般5分钟内自行缓解+超过15分钟需紧急处理。</p><div class=mnem><strong>口诀：</strong>急惊四证痰热惊风，清热豁痰镇惊熄风；风热银翘气营清瘟，陷肝羚角湿热连翁。</div></div>'}
]}]},

{unit:"第二十单元 水肿",subunits:[{name:"小儿水肿",points:[{id:"ek-20-1",name:"水肿的概念及风水相搏、湿热内侵证的证候治法方药",type:"apply",
content:'<p><strong>小儿水肿</strong>是体内水液潴留+泛溢肌肤。相当于急性肾小球肾炎+肾病综合征。多与感染（链球菌）有关。</p><div class=compare-table><div class=ct-left><h4>风水相搏（急性期）</h4><p><strong>证候：</strong>眼睑浮肿→全身浮肿+皮肤光亮+按之凹陷+小便短少+发热+恶风+咳嗽+咽红肿痛<br><strong>治法：</strong>疏风利水<br><strong>主方：</strong>麻黄连翘赤小豆汤</p></div><div class=ct-right><h4>湿热内侵</h4><p><strong>证候：</strong>浮肿+小便短赤+血尿+发热+皮肤疮毒（脓疱疮）+苔黄腻<br><strong>治法：</strong>清热利湿<br><strong>主方：</strong>五味消毒饮合五皮饮</p><p>注意：<br>·急性期卧床休息+低盐饮食<br>·监测血压+防高血压脑病<br>·防心力衰竭+水电解质紊乱</p></div></div><div class=classic-quote>《金匮要略》："腰以上肿当发汗+腰以下肿当利小便。"<span class=src>——《金匮要略》</span></div><div class=plain>小儿水肿最常见于急性肾小球肾炎——"眼睑先肿+从头面到全身+来得快"。风水相搏型（有感冒症状）→麻黄连翘赤小豆汤宣肺利水+湿热内侵型（有皮肤疮毒+血尿）→五味消毒饮合五皮饮清热利湿。注意：小儿急性肾炎要卧床休息+低盐+监测血压+防心衰和高血压脑病。</p><div class=mnem><strong>口诀：</strong>水肿风水麻黄连翘赤豆汤，湿热五味消毒五皮防；急性肾炎卧床盐控，血压心衰常提防。</div></div>'}]
}]},

{unit:"第二十一单元 尿频",subunits:[{name:"尿频",points:[{id:"ek-21-1",name:"脾肾气虚证的证候、治法、方药",type:"detail",
content:'<p><strong>尿频</strong>是小儿小便频数。慢性尿频以脾肾气虚型最常见+伴面白神疲+纳少+便溏+自汗。</p><div class=compare-table><div class=ct-left><h4>脾肾气虚证</h4><p><strong>证候：</strong>小便频数+淋漓不尽+神疲乏力+面色萎黄+食欲不振+大便稀溏+自汗+舌淡苔白</p><p><strong>治法：</strong>温补脾肾+升提固摄</p><p><strong>主方：</strong>缩泉丸</p></div><div class=ct-right><h4>鉴别与调护</h4><p>注意与以下鉴别：<br>·急性尿路感染→尿频+尿急+尿痛+尿常规异常<br>·遗尿→小便自遗+无尿意</p><p>调护：<br>·白天适当多喝水（排空膀胱）<br>·睡前少饮水<br>·不责骂+减少精神紧张</p></div></div><div class=classic-quote>《幼科集成》："小儿小便频数，脾气不足也。"<span class=src>——《幼科集成》</span></div><div class=plain>尿频就是"老想去尿尿"——脾肾气虚用缩泉丸（乌药+益智仁+山药）。缩泉丸"缩泉"就是"缩住小便"的意思。治疗同时要注意生活习惯调整：不要因为尿频就限制喝水+反而要多喝水排空膀胱。不要责骂孩子+精神紧张会加重尿频。</p><div class=mnem><strong>口诀：</strong>尿频脾肾气虚多，缩泉乌药益智仁山药；温补升提固下元，谨防尿路感染错。</div></div>'}]
}]},

{unit:"第二十二单元 遗尿",subunits:[{name:"遗尿",points:[{id:"ek-22-1",name:"遗尿的概念及辨证论治",type:"apply",
content:'<p><strong>遗尿</strong>是3岁以上小儿睡眠中小便自遗+醒后方知。每周≥2次+持续3个月以上。3岁以下为生理性遗尿（正常+神经系统未发育完善）。</p><div class=compare-table><div class=ct-left><h4>辨证分型</h4><p><strong>肺脾气虚：</strong>睡中遗尿+尿频+量少+面色无华+神疲+食少+自汗<br>→ <strong>补中益气汤</strong>合<strong>缩泉丸</strong></p><p><strong>肾气不足：</strong>睡中遗尿+尿清长+量多次数少+腰膝酸软+畏寒<br>→ <strong>菟丝子散</strong></p><p><strong>心肾不交：</strong>梦中遗尿+寐不安宁+烦躁+五心烦热<br>→ <strong>交泰丸</strong>合<strong>导赤散</strong></p><p><strong>肝经湿热：</strong>睡中遗尿+尿黄量少+性情急躁+面赤+苔黄<br>→ <strong>龙胆泻肝汤</strong></p></div><div class=ct-right><h4>调护要点</h4><p>·睡前2小时不喝水和牛奶<br>·睡前排空膀胱<br>·不责骂+多鼓励<br>·夜间定时叫醒排尿<br>·培养孩子自主排尿习惯</p><p>效果不好的原因：<br>·诊断年龄错误（<3岁）<br>·未配合生活调理<br>·合并其他疾病</p></div></div><div class=classic-quote>《幼科集成》："遗尿者，此由膀胱虚冷，不能约于水故也。"<span class=src>——《幼科集成》</span></div><div class=plain>遗尿就是"尿床"。3岁以内不叫遗尿（正常）。四个证型：肺脾气虚（补中益气+缩泉）最常用+肾气不足（菟丝子散）+心肾不交（交泰导赤）+肝经湿热（龙胆泻肝）。实际上临床最多见的是"虚证"（肺脾肾虚）→温补固涩。注意：不要打骂孩子+越紧张越尿床。</p><div class=mnem><strong>口诀：</strong>遗尿四型肺脾补中缩泉+肾虚菟丝子散+心肾交泰导赤+肝热龙胆泻肝。</div><div class=trap-box><strong>考点：</strong>1.诊断年龄>3岁+每周≥2次+≥3个月。2.肺脾气虚→补中益气汤合缩泉丸。3.肾气不足→菟丝子散（菟丝子牡蛎肉苁蓉附子五味子鸡内金）。4.心肾不交→交泰丸合导赤散。5.肝经湿热→龙胆泻肝汤。6.生活调理比药物更重要。</div></div>'}]
}]},

{unit:"第二十三单元 五迟、五软",subunits:[{name:"五迟五软",points:[{id:"ek-23-1",name:"五迟、五软的概念、区别及辨证论治",type:"compare",
content:'<p><strong>五迟：</strong>立迟+行迟+发迟+齿迟+语迟——生长发育迟缓的五个方面。<br><strong>五软：</strong>头项软+口软+手软+足软+肌肉软——肌肉筋脉痿软无力的五个表现。<br>五迟以"发育迟缓"为主+五软以"痿软无力"为主。常同时存在。</p><div class=compare-table><div class=ct-left><h4>五迟</h4><p><strong>立迟：</strong>站立迟<br><strong>行迟：</strong>行走迟<br><strong>发迟：</strong>头发稀疏枯黄+生长迟<br><strong>齿迟：</strong>牙齿萌出迟<br><strong>语迟：</strong>语言发育迟</p></div><div class=ct-right><h4>五软</h4><p><strong>头项软：</strong>头项无力+东倒西歪<br><strong>口软：</strong>唇薄无力+咀嚼无力+流涎<br><strong>手软：</strong>手不能握+下垂<br><strong>足软：</strong>站立不稳+足不能行<br><strong>肌肉软：</strong>肌肉松软+无力</p></div></div><div class=compare-table><div class=ct-left><h4>五迟辨治</h4><p><strong>肝肾不足：</strong>立迟行迟+齿迟+发迟<br>→ <strong>加味六味地黄丸</strong></p><p><strong>心血不足：</strong>语迟+智力低下+发迟<br>→ <strong>菖蒲丸</strong></p></div><div class=ct-right><h4>五软辨治</h4><p><strong>脾肾两虚：</strong>头项软+手足软+口软+肌肉软<br>→ <strong>补肾地黄丸</strong>合<strong>补中益气汤</strong></p><p><strong>气虚血瘀：</strong>五软+面色晦暗+唇紫+舌紫<br>→ <strong>通窍活血汤</strong></p></div></div><div class=classic-quote>《医宗金鉴》："五迟者，立迟行迟发迟齿迟语迟也；五软者，头项软口软手软足软肌肉软也。"<span class=src>——《医宗金鉴》</span></div><div class=plain>五迟就是"五方面发育落后"+五软就是"五方面肌肉没力气"。五迟和五软常同时存在（孩子又落后又没劲）。中医认为五迟是"肝肾不足"（肾主骨生髓+肝主筋）+五软是"脾肾两虚"（脾主肌肉+肾主骨）。五迟肝肾不足→加味六味地黄丸+心血不足（语迟）→菖蒲丸+五软脾肾两虚→补肾地黄丸合补中益气汤。</p><div class=mnem><strong>口诀：</strong>五迟立行发齿语，肝肾不足六味加；心血菖蒲丸语言，五软脾肾补中加。</div><div class=trap-box><strong>考点：</strong>1.五迟——立+行+发+齿+语（发育迟缓）。2.五软——头项+口+手+足+肌肉（无力软瘫）。3.五迟肝肾不足→加味六味地黄丸（六味+鹿茸五加皮）。4.语迟心血不足→菖蒲丸（石菖蒲人参麦冬远志川芎当归乳香朱砂）。5.五软脾肾两虚→补肾地黄丸合补中益气汤。6.五迟vs五软鉴别：迟（晚）vs软（无力）。</div></div>'}
]}]},
'''

after = c[:idx15] + UNITS + c[idx24:]

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(after)

print(f"Done. Size: {len(after)} bytes (was {len(c)} bytes)")
