#!/usr/bin/env python3
"""fill-unit4.py — 填充 s6 第四单元 中医外科疾病治法"""
TARGET = '/sessions/compassionate-hopeful-thompson/mnt/syllabus/subjects/s6-waike.js'

with open(TARGET, 'r', encoding='utf-8') as f:
    c = f.read()

idx4 = c.find('{unit:"第四单元')
idx5 = c.find('{unit:"第五单元')

UNIT4 = r'''{unit:"第四单元 中医外科疾病治法",subunits:[
  {name:"细目一：内治法",points:[
    {id:"wk-4-1",name:"消、托、补三大法则的应用与内涵",type:"apply",
content:'<p><strong>消托补</strong>是外科内治三大法则。按病程分期依次使用。</p><div class=compare-table><div class=ct-left><h4>三大法则</h4><p><strong>消法（初期）：</strong><br>使肿疡消散在未成脓之前。<br>以解表+通里+清热+温通+祛痰+理气+活血等法消散。<br>代表方：仙方活命饮（疮疡之圣药）<br><strong>禁忌：</strong>肿疡已成不可用+脓已成必用托法。</p><p><strong>托法（中期）：</strong><br>促脓早熟+防毒内陷（透托）或补气血+托毒外出（补托）。<br>代表方：透脓散（透托）+托里消毒散（补托）</p><p><strong>补法（后期）：</strong><br>补益气血+促进愈合。<br>代表方：八珍汤+十全大补汤</p></div><div class=ct-right><h4>消托补与病程对应</h4><p><strong>初期（邪盛+正不虚）→消法</strong><br>肿疡初起→促其消散<br>清热解毒+活血化瘀等</p><p><strong>中期（邪盛+正虚）→托法</strong><br>成脓期→托毒外出<br>防毒内陷+促脓早溃</p><p><strong>后期（正虚+邪衰）→补法</strong><br>溃疡后期→促愈合<br>补益气血+生肌敛疮</p><p class=trap><strong>重要！</strong>消托补不可乱用：初期用补法→闭门留寇+中期用消法→毒散不去+后期用消法→伤正气。</p></div></div><div class=classic-quote>《外科精义》："消者，散其结也；托者，托其毒也；补者，补其虚也。"<span class=src>——《外科精义》</span></div><div class=plain>消托补就是中医外科的三步走：第一步（初期）"消"——让肿块消下去别化脓+第二步（中期）"托"——已经化脓了帮它快点排出来+第三步（后期）"补"——脓排出来了补补身体让伤口长好。注意时机先后不能搞错：初起用补法（还没化脓就补）→毒邪被"关"在里面了（闭门留寇）！</p><div class=mnem><strong>口诀：</strong>初期消法散肿结+仙方活命第一方；中期托法透脓早+透脓托里消毒散；后期补法八珍汤+三期序贯不能乱。</div><div class=trap-box><strong>高频考点（必考！）：</strong>1.消托补三期对应初中后：消法（初期未成脓）+托法（中期成脓）+补法（后期溃后）。2.消法代表方——仙方活命饮（疮疡之圣药+外科之首方）。3.托法分两种：透托（透脓散）用于正气尚充+补托（托里消毒散）用于正虚毒盛。4.关键禁忌：脓成之后不可用消法+毒盛之时不可用补法（闭门留寇）。5.消托补不可乱序——"朝用补法暮已溃"（用错了反而坏事）。</div></div>'},
    {id:"wk-4-1a",name:"清热法、和营法、内托法的代表方剂及应用",type:"apply",
content:'<p><strong>清热法</strong>+<strong>和营法</strong>+<strong>内托法</strong>是外科内治中最常用的具体治法。</p><div class=compare-table><div class=ct-left><h4>清热法</h4><p><strong>适用：</strong>热毒蕴结之阳证疮疡</p><p><strong>代表方：</strong><br>·黄连解毒汤（三焦火毒）<br>·五味消毒饮（疔疮热毒）<br>·四妙勇安汤（脱疽热毒）<br>·龙胆泻肝汤（肝经湿热）</p></div><div class=ct-right><h4>和营法与内托法</h4><p><strong>和营法：</strong><br>适用：瘀血凝滞+肿痛固定<br>代表方：桃红四物汤/活血散瘀汤<br>注意：和营而不破血+适度即可</p><p><strong>内托法：</strong><br>适用：疮疡中期+毒盛正虚<br>代表方：<br>·透脓散（透托）—黄芪+穿山甲+川芎+当归+皂角刺<br>·托里消毒散（补托）—八珍+黄芪+银花+白芷+皂角刺</p></div></div><div class=classic-quote>《外科正宗》："清热解毒+活血和营+托毒外出，外科三大治法也。"<span class=src>——《外科正宗》</span></div><div class=plain>这三个是消托补下面的具体治法。清热法用最多（外科疾病大多有热）+和营法（活血但不猛破）+内托法（帮助排脓）。注意清热法不可过用久用——寒凉伤胃+伤气血。和营法也不能过度破血。内托法关键是分清"虚"和"实"：正虚明显用补托（托里消毒散）+毒盛正不虚用透托（透脓散）。</p><div class=mnem><strong>口诀：</strong>清热五味连解毒+和营桃红四物汤；透托透脓散最妙+补托托里消毒良。</div><div class=trap-box><strong>考点：</strong>1.清热法代表方：黄连解毒汤（三焦火毒）+五味消毒饮（疔）+四妙勇安汤（脱疽）+龙胆泻肝汤（肝经湿热）。2.和营法用桃红四物汤——活血但不破血。3.内托法：透脓散（透托）vs托里消毒散（补托）——区别在于有无补益气血药。4.清热不可太过——苦寒伤胃+影响气血。5.和营不可过用破血药——防耗伤正气。</div></div>'}
  ]},
  {name:"细目二：外治法",points:[
    {id:"wk-4-2",name:"膏药、油膏的临床应用",type:"apply",
content:'<p><strong>膏药</strong>（硬膏）和<strong>油膏</strong>（软膏）是外科外治最常用的剂型。</p><div class=compare-table><div class=ct-left><h4>膏药（硬膏）</h4><p><strong>特点：</strong>以油+药熬炼而成+摊纸上/布上+贴患处</p><p><strong>适应证：</strong><br>·阳证—太乙膏+千捶膏<br>·阴证—阳和解凝膏<br>·半阴半阳—冲和膏</p><p><strong>用法：</strong>贴前烘热+使膏药软化+贴患处+定时更换</p><p><strong>注意：</strong>膏药摊涂大小适中+厚薄得当；过敏者停用；溃疡脓水多者不宜。</p></div><div class=ct-right><h4>油膏（软膏）</h4><p><strong>特点：</strong>以油类+药粉调匀而成</p><p><strong>适应证：</strong><br>·红肿灼痛—金黄膏/玉露膏<br>·溃后不敛—生肌玉红膏<br>·湿疹糜烂—青黛膏<br>·阴证—回阳玉龙膏</p><p><strong>用法：</strong>直接涂纱布上+敷患处+绷带固定</p><p><strong>注意：</strong>油膏厚薄适宜+肉芽水肿不宜过厚。</p></div></div><div class=classic-quote>《外科正宗》："膏药乃外科之首用，无论大小疮疖，初起贴之即消，已成贴之即溃。"<span class=src>——《外科正宗》</span></div><div class=plain>膏药（硬膏）像狗皮膏药那样+贴在身上+需要加热软化。油膏（软膏）像药膏直接涂抹在纱布上敷伤口。记住分类：红热痛（阳证）→金黄膏/玉露膏+不红不热（阴证）→回阳玉龙膏+介于阴阳之间→冲和膏。</p><div class=mnem><strong>口诀：</strong>阳证金黄玉露膏+阴证回阳玉龙好；半阴半阳冲和膏+溃后生肌玉红宝。</div><div class=trap-box><strong>考点：</strong>1.阳证：金黄膏（金黄散调制）/玉露膏（芙蓉叶）。2.阴证：回阳玉龙膏（温阳散寒）。3.半阴半阳：冲和膏（行气活血）。4.溃后生肌：生肌玉红膏。5.湿疹：青黛膏。6.膏药贴前要烘热+脓肿处不宜厚贴。</div></div>'},
    {id:"wk-4-3",name:"箍围药的适应证、用法及注意点",type:"apply",
content:'<p><strong>箍围药</strong>（敷贴药）是将药物研粉+用水/醋/酒/油/蜜等调敷患处的外用剂型。古称"敷贴"。</p><div class=compare-table><div class=ct-left><h4>适应证与分类</h4><p><strong>阳证：</strong>红热肿痛<br>·金黄散（水/蜜调）+玉露散<br>·功用：清热消肿+散瘀止痛</p><p><strong>阴证：</strong>不红不热+漫肿<br>·回阳玉龙膏+温经散寒</p><p><strong>半阴半阳：</strong><br>·冲和膏+行气活血+散瘀消肿</p></div><div class=ct-right><h4>用法与注意点</h4><p><strong>调制方法：</strong><br>阳证→水/蜜调（清凉）<br>阴证→酒/醋调（辛散）<br>半阴半阳→葱姜汁调</p><p><strong>注意：</strong><br>1.敷药范围大于肿势<br>2.干后更换+保持湿润<br>3.脓成不可用（妨碍排脓）<br>4.过敏者停用</p></div></div><div class=classic-quote>《医宗金鉴》："箍围药，取其束疮毒，使不散漫也。"<span class=src>——《医宗金鉴》</span></div><div class=plain>箍围药就是调了敷在伤口周围的药膏+目的是"箍住"毒邪不让它扩散。记住三个"箍围"的调制方法：阳证（热）用水或蜜调+阴证（寒）用酒或醋调+半阴半阳用葱姜汁调。还有一个要点：箍围范围要大过肿势——这样才能箍住毒邪。注意脓已成的不能用！</p><div class=mnem><strong>口诀：</strong>箍围敷贴箍毒邪+阳水阴酒半葱姜；金黄阳证玉露凉+回阳冲和阴半良。</div><div class=trap-box><strong>考点：</strong>1.适应证：阳证→金黄散/玉露散（水蜜调）+阴证→回阳玉龙膏（酒醋调）+半阴半阳→冲和膏。2.敷药范围应当大于肿势。3.干后即换+保持湿润。4.禁忌：脓已成不可再箍围（需切开引流）。5.调制"阳水阴酒"——阳证用水/蜜+阴证用酒/醋。</div></div>'},
    {id:"wk-4-4",name:"掺药的种类及临床应用",type:"apply",
content:'<p><strong>掺药</strong>是将药物研成极细粉末+直接撒布于疮面或膏药上的外用制剂。</p><div class=compare-table><div class=ct-left><h4>常用掺药分类</h4><p><strong>消散药：</strong>阳毒内消散+阴毒内消散+红灵丹<br>→撒膏药上贴患处<br>→阳证阴证各有专用</p><p><strong>提脓祛腐药：</strong>九一丹+八二丹+七三丹+五五丹<br>→含升丹（HgO）成分+提脓祛腐<br>→浓度越高+祛腐力越强（九一→五五）</p><p><strong>腐蚀药：</strong>白降丹+枯痔散<br>→腐蚀坏死组织+平胬肉</p></div><div class=ct-right><h4>其他掺药</h4><p><strong>生肌收口：</strong>生肌散+八宝丹<br>→促新肉生长+多用于溃疡后期</p><p><strong>止血药：</strong>桃花散+云南白药<br>→外伤出血时用<br>→注意不宜大面积撒布</p><p><strong>清热收涩：</strong>青黛散+三石散<br>→皮肤湿疹+滋水渗液时用</p><p><strong>酊剂：</strong>红灵酒+10%黄柏溶液<br>→涂擦患处+多用于皮肤病</p></div></div><div class=classic-quote>《外科证治全生集》："红升白降+外科家当。"<span class=src>——《外科证治全生集》</span></div><div class=plain>掺药就是撒的药粉。记住这条"九八七五"提脓腐药浓度递增链：九一丹(9:1)最温和→八二丹(8:2)→七三丹(7:3)→五五丹(5:5)最猛。数字前面是熟石膏比例+后面是升丹比例。升丹比例越高祛腐力越强。九一丹最常用+五五丹用于腐肉多的疮面。"红升白降"——红升丹提脓+白降丹腐蚀组织。</p><div class=mnem><strong>口诀：</strong>初溃提脓九一丹+腐蚀白降平胬肉；生肌收口生肌散+止血桃花散可敷。</div><div class=trap-box><strong>考点：</strong>1.升丹浓度九→八→七→五递增（祛腐力递增+刺激性递增）。2.九一丹最常用+腐肉去尽即停用（防汞中毒）。3.白降丹腐蚀力强+用于腐蚀坏死组织+平胬肉。4.生肌散用于溃疡后期（新肉将生时）。5.掺药不宜大面积撒布（防吸收中毒）。6."红升白降，外科家当"——外科两大丹。</div></div>'},
    {id:"wk-4-5",name:"砭镰法、挑治疗法、挂线法、结扎法的适应证及用法",type:"apply",
content:'<p><strong>砭镰法</strong>（放血疗法）+<strong>挑治疗法</strong>+<strong>挂线法</strong>+<strong>结扎法</strong>是外科特色外治法。</p><div class=compare-table><div class=ct-left><h4>砭镰法</h4><p><strong>适应证：</strong>丹毒+红丝疔<br><strong>用法：</strong>三棱针/砭石浅刺患处+放出少量血液</p><p><strong>挑治疗法</strong><br><strong>适应证：</strong>内痔出血+肛裂+麦粒肿等<br><strong>用法：</strong>在背部特定部位挑出白色纤维状物</p></div><div class=ct-right><h4>挂线法</h4><p><strong>适应证：</strong>肛漏（肛瘘）+乳漏<br><strong>用法：</strong>橡皮筋/药线贯穿漏管+逐渐收紧+慢性切开</p><p><strong>结扎法</strong><br><strong>适应证：</strong>内痔+息肉+赘生物<br><strong>用法：</strong>丝线结扎根部+阻断血供+坏死脱落</p></div></div><div class=classic-quote>《外科正宗》："砭镰之法，乃放血泄毒之法也。凡丹毒、疔疮走黄，砭之则毒散。"<span class=src>——《外科正宗》</span></div><div class=plain>这四个特色疗法各有用处：砭镰法（放血）→丹毒红丝疔+挑治疗法→痔疮肛裂（背部挑治）+挂线法→肛瘘（慢性切开防肛门失禁）+结扎法→内痔和赘生物（勒死它）。挂线法最精妙——它是利用橡皮筋的"慢性切割"作用+一边切一边愈合+防止肛门括约肌损伤导致大便失禁。这是中医肛肠科最伟大的发明之一！</p><div class=mnem><strong>口诀：</strong>砭镰丹毒放血疗+挑治内痔肛裂消；挂线肛漏慢切开+结扎内痔套扎好。</div><div class=trap-box><strong>高频考点：</strong>1.砭镰法→丹毒+红丝疔（必考）。2.挂线法→肛漏（肛瘘）+优势是不损伤括约肌防肛门失禁。3.结扎法→内痔+赘生物——使组织坏死脱落。4.挑治疗法→内痔出血+肛裂+麦粒肿+在背部选点挑治。5.挂线法的原理：慢性切割+边切边愈合+防止肛门失禁。</div></div>'},
    {id:"wk-4-6",name:"引流法、垫棉法、针灸法、熏法等外治法的适应证及用法",type:"apply",
content:'<p><strong>引流法</strong>+<strong>垫棉法</strong>+<strong>针灸法</strong>+<strong>熏法</strong>是外科常用的辅助外治法。</p><div class=compare-table><div class=ct-left><h4>引流法</h4><p><strong>适用：</strong>溃疡脓水不畅+窦道腐肉难出<br><strong>方法：</strong>药线/引流条插入疮口+引流脓液<br><strong>常用：</strong>纸捻+纱布条+橡皮管</p><p><strong>垫棉法</strong><br><strong>适用：</strong>溃疡脓出不畅+疮口有空腔<br><strong>方法：</strong>棉垫垫压疮口+加压包扎+促脓外出+消除空腔</p></div><div class=ct-right><h4>针灸法与熏法</h4><p><strong>针灸法：</strong><br>适用：瘰疬+乳痈初期+丹毒<br>方法：循经取穴+局部围刺+温针灸</p><p><strong>熏法：</strong><br>适用：皮肤病+肛门病+疮口不敛<br>方法：药物燃烧/煮沸+烟/蒸汽熏患处<br>常用：艾灸熏+中药熏洗（痔瘘常用）</p></div></div><div class=classic-quote>《外科正宗》："疮口引流之法，务令脓出通畅，则毒从外解。"<span class=src>——《外科正宗》</span></div><div class=plain>这四个辅助疗法：引流法（让脓水顺畅流出来）+垫棉法（用棉垫压住空腔不让它空着）+针灸法（针刺穴位治疗外科病）+熏法（用药液蒸汽熏洗患处）。垫棉法在臁疮（老烂脚）治疗中用得多+用弹力绷带加棉垫压住溃疡处+促进愈合。熏法在痔疮肛裂中用得最多——中药熏洗坐浴。</p><div class=mnem><strong>口诀：</strong>引流排出通畅脓+垫棉加压空腔空；针灸循经能散结+熏洗犹宜痔瘘用。</div><div class=trap-box><strong>考点：</strong>1.引流法——脓水不畅时用（药线/引流条）。2.垫棉法——疮口有空腔时用+加压消除空腔。3.针灸法——瘰疬+乳痈初期+循经取穴。4.熏法——皮肤病+痔瘘常用（五倍子汤+苦参汤熏洗）。5.注意：引流条使用适时更换+引流充分但不深入。</div></div>'}
  ]}
]},

'''

after = c[:idx4] + UNIT4 + c[idx5:]

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(after)

print(f"Done. Size: {len(after)} bytes (was {len(c)} bytes)")
