#!/usr/bin/env python3
"""
S2 中诊 · 批次D升级脚本
第二单元 问诊 (16 points) — 症状推导型 derive-box
"""

import re, sys

FILE = 's2-zhongzhen.js'
BAK  = 's2-zhongzhen.js.bak-D'

# ── 1. Read file ──
with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()
orig_content = content

# ── 2. Define new core content for each point ──
# Symptoms-deduction type: step1 (概念引出·蓝) → step2 (病机分析·红) → step3 (分型锁定·紫) → step4 (鉴别·橙) → step5 (场景变体·橙)
# Plus derive-flow linking nodes

new_content_map = {}

# ═══════════════════════════════════════════
# dx-2-1 恶寒发热的临床意义
# ═══════════════════════════════════════════
new_content_map['dx-2-1'] = '''<p><strong>恶寒发热并见是表证的标志性特征——分辨风寒与风热的关键在于寒热的轻重对比。</strong></p><div class="classic-quote">《素问·风论》："风气藏于皮肤之间，内不得通，外不得泄。"风邪袭表，腠理开阖失常，卫气与邪气相争则恶寒发热并见。<span class="src">——《黄帝内经》</span></div><div class="mnem">恶寒发热并见表，寒重热轻属风寒；热重寒轻属风热，发热恶风太阳中。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">恶寒发热<br>表证标志</span><span class="df-arrow">→</span><span class="df-node df-logic">卫气趋表抗邪<br>正邪交争于表<br>营卫失调</span><span class="df-arrow">→</span><span class="df-node df-organ">寒重→风寒<br>热重→风热<br>恶风→中风</span><span class="df-arrow">→</span><span class="df-node df-symptom">辛温vs辛凉<br>麻黄·桂枝·银翘</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">同一个"发烧怕冷"，背后可能有完全不同的故事</span><div class="ds-body">两个人同时说"我发烧又怕冷"，一个可能裹着被子还瑟瑟发抖（寒重热轻），另一个可能浑身发烫只想掀被子（热重寒轻）。同样是恶寒发热，一个来自寒邪（风寒表证），一个来自热邪（风热表证）。中医问诊的第一步就要辨清：你是怕冷重还是发热重？这个简单的比较直接决定了后面的用药方向——用热药还是凉药。所以问诊时不能只问"你发烧吗"，还要追问"你更怕冷还是更怕热"。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">恶寒发热的病机分析——卫气在"打仗"</span><div class="ds-body">恶寒发热同时出现的根本原因是"卫气趋表抗邪"——人体的防御力量（卫气）被调集到体表和外邪交战。当外邪刚刚侵犯皮毛，卫气立即奔赴体表"迎战"：卫气被风寒之邪郁遏在肌表不能正常散布→人感觉怕冷（恶寒）；同时人体自发地升高产热来"燃烧"外邪→所以发热。这就是为什么恶寒发热总是一起出现——它们是同一场"战斗"的两个侧面。风寒之邪较重，把卫气"封"得更紧→恶寒重（怕冷明显）；风热之邪偏散，产热反应更强→发热重（发烧更突出）。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——同是恶寒发热，寒热轻重不同指向不同的证</span><div class="ds-body">恶寒发热可细分为三种类型：<strong>风寒表证</strong>——恶寒重发热轻（怕冷明显超过发热），伴头身痛、无汗、口不渴、苔薄白、脉浮紧。病机为风寒束表、卫阳被郁。代表方荆防败毒散或麻黄汤。<strong>风热表证</strong>——发热重恶寒轻（发热明显，怕冷轻微），伴咽痛、口渴、汗出、苔薄黄、脉浮数。病机为风热犯表、肺卫失宣。代表方银翘散。<strong>太阳中风证</strong>——发热轻恶风自汗（微微发热同时怕风、出汗），伴鼻鸣干呕、脉浮缓。病机为营卫不和、腠理疏松。代表方桂枝汤。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——风寒与风热最容易误判的两种情况</span><div class="ds-body">风寒和风热看似一清二楚，实际临床中最容易误判的是以下两种情况：第一，"寒包火"——病人同时有怕冷（风寒）和咽痛口渴（风热）的表现。这时要看哪个更突出：若怕冷重、咽痛轻→风寒为主，银翘散加麻黄；若发热重、怕冷轻、咽痛明显→风热为主。第二，风寒化热——起病时是典型的怕冷重（风寒），三天后变成了发热重（已化热）。这不是判断错了，是病程进展了——初期用辛温、后期改用辛凉。鉴别要点：风寒口不渴、苔白、脉浮紧；风热口渴、苔黄、脉浮数。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是恶寒发热，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（青壮年 vs 老人）：一位25岁小伙子受凉后恶寒重、发热39度、身痛无汗——正气充足、正邪交争剧烈→典型风寒表实证，麻黄汤。一位70岁老人同样受凉后微恶寒、低热37.5度、乏力——正气已衰、反应能力下降→荆防败毒散轻剂，加黄芪扶正。<strong>场景二</strong>（夏季 vs 冬季）：夏季恶寒发热→多夹暑湿（身热不扬、头重如裹），新加香薷饮。冬季恶寒发热→多纯风寒，麻黄汤。<strong>场景三</strong>（小儿 vs 成人）：小儿恶寒发热易传变→很快从风寒转为风热→高热惊厥风险，银翘散加钩藤，密切观察。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-2-2 但寒不热的临床意义
# ═══════════════════════════════════════════
new_content_map['dx-2-2'] = '''<p><strong>但寒不热——只觉怕冷、没有发热，是里寒证的标志，需辨清新病实寒还是久病虚寒。</strong></p><div class="classic-quote">《素问·阴阳应象大论》："阴盛则阳病，阳盛则阴病。阳胜则热，阴胜则寒。"但寒不热为阴气偏盛或阳气不足所致。<span class="src">——《黄帝内经》</span></div><div class="mnem">但寒不热里寒证，新病实寒理中汤；久病虚寒肾气丸，新久虚实要辨清。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">但寒不热<br>里寒证标志</span><span class="df-arrow">→</span><span class="df-node df-logic">阴寒内盛<br>或阳虚失温</span><span class="df-arrow">→</span><span class="df-node df-organ">新病→实寒<br>久病→虚寒</span><span class="df-arrow">→</span><span class="df-node df-symptom">实寒→理中<br>虚寒→肾气丸</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">同样是"怕冷"——一个刚刚着凉，一个已经冷了很久</span><div class="ds-body">两个人走进诊室都说"怕冷"。一个说"昨天淋了雨就开始冷"，另一个说"这个冷已经好几年了，每年冬天都更重"。前者是新发的但寒不热——可能只是一场急性里寒；后者是长期的但寒不热——身体已经"冷"了很久，阳气不足了。问诊的关键是追问"什么时候开始的""多久了"——新病恶寒多为实寒（寒邪直接侵犯脏腑），久病恶寒多为虚寒（自身阳气不足、温煦失职）。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">但寒不热的病机分析——"体内暖气停了"</span><div class="ds-body">但寒不热的本质是阳气无法温煦全身——要么是外来的寒邪太重，"冻住"了脏腑功能（实寒），要么是自身的阳气不够、产热不足（虚寒）。实寒证：寒邪直中脏腑→局部阳气被寒邪"困住"→表现急性剧烈的怕冷+腹部冷痛。这就像大冬天突然往屋里灌了一股冷风——屋子本身是暖的，但冷风到来瞬间降温。虚寒证：阳气长期亏虚→全身温煦功能减退→慢性持续的怕冷+四肢不温。这就像炉子里煤不够了——不是冷风进来了，而是自身发热不足了。两者的鉴别要点除了病程之外，还要看舌脉——实寒舌苔白厚、脉沉实有力；虚寒舌淡胖齿痕、脉沉迟无力。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——新病恶寒与久病恶寒的鉴别要点</span><div class="ds-body"><strong>实寒证（新病恶寒）</strong>：起病急、病程短。怕冷明显但体温不一定低。伴脘腹冷痛、得温痛减、面色苍白、手足冷。大便溏薄或泄泻、小便清长。舌淡苔白厚、脉沉实或沉紧。病机为寒邪直中或过食生冷→阴寒内盛、阳气被遏。代表方理中汤（温中散寒）。<strong>虚寒证（久病恶寒）</strong>：起病缓慢、病程长。长期怕冷、四肢不温、腰膝酸冷。伴神疲乏力、少气懒言、大便稀溏、小便清长或夜尿多。舌淡胖有齿痕、苔白润、脉沉迟无力。病机为阳气虚衰、温煦失职。代表方金匮肾气丸（温补肾阳）。实寒以祛邪为主（散寒），虚寒以扶正为主（温阳）。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——但寒不热和恶寒发热中最容易混淆的情况</span><div class="ds-body">最容易误判的是"但寒不热"和"恶寒发热"中的寒重热轻：前者是里证（只寒不热），后者是表证（寒重但仍有发热）。区别的关键在于——测体温和问体感。恶寒发热（寒重热轻）→病人明明说"怕冷很重"但体温一量38.5度→表证。但寒不热→病人说"好冷"体温36度甚至偏低→里寒证。另外，但寒不热中的新病恶寒（实寒）和久病恶寒（虚寒）也可通过"喝热水的感觉"鉴别：实寒→喝热水后冷痛明显减轻（寒邪被温散）；虚寒→喝了热水感觉改善不明显（自身火力不足，需要持续温补）。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是但寒不热，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（急性vs慢性）：一位年轻人夏天狂吃冰西瓜后突然腹痛怕冷、大便水样→实寒证，理中汤加藿香。一位老年女性多年怕冷、夏天还要穿秋裤、夜尿3-4次→虚寒证，金匮肾气丸长期调理。<strong>场景二</strong>（女性经期）：经期但寒不热伴小腹冷痛、得热痛减→寒凝胞宫，温经汤。若经期后怕冷加头晕乏力→血虚寒凝，当归四逆汤。<strong>场景三</strong>（地域差异）：北方人冬季但寒不热多纯寒证；南方人但寒不热多夹湿（怕冷+身重+苔白腻）→胃苓汤加减。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-2-3 但热不寒的临床意义
# ═══════════════════════════════════════════
new_content_map['dx-2-3'] = '''<p><strong>但热不寒——只发热不怕冷，是里热证的标志，需分辨壮热、潮热的不同类型和临床意义。</strong></p><div class="classic-quote">《素问·阴阳应象大论》："阳盛则热。"但热不寒为阳热亢盛或阴虚阳亢所致。<span class="src">——《黄帝内经》</span></div><div class="mnem">壮热大汗白虎汤，日晡潮热承气汤；午后湿温三仁汤，夜间阴虚六味黄。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">但热不寒<br>里热证标志</span><span class="df-arrow">→</span><span class="df-node df-logic">阳热亢盛<br>或阴虚火旺</span><span class="df-arrow">→</span><span class="df-node df-organ">壮热·日晡<br>午后·夜间</span><span class="df-arrow">→</span><span class="df-node df-symptom">白虎·承气<br>三仁·六味</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">同样说"发烧"——体温曲线的"时间密码"藏着病根</span><div class="ds-body">两个病人都说"发烧"。一个24小时持续高热、满头大汗、想喝冰水；另一个每到下午三四点体温就准时升高、像潮水一样涨退。虽然都是发热，但前者是"壮热"——整个身体在"燃烧"，后者是"潮热"——发热像潮汐一样有节律。中医问诊中要仔细问清楚发热的时间规律：什么时间烧？一天几次？每次持续多久？这些信息直接指向不同的病机和治法。辨发热类型是但热不寒问诊的核心。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">但热不寒的病机分析——"体内的火失控了"</span><div class="ds-body">但热不寒的本质是体内产热过多或散热能力下降——阳热亢盛。没有恶寒说明病邪已经不在体表，而是深入了脏腑气血。壮热（高热持续不退、体温39度以上）→阳明气分热盛→正气不虚、邪正剧烈交争→全身都在"烧"→白虎汤。潮热（定时发热如潮汐）→有三种可能：日晡潮热（下午3-5点申时发热）→阳明腑实、热结胃肠→大承气汤；午后潮热（中午过后发热）→湿遏热伏、湿热交蒸→三仁汤；夜间潮热（入夜发热、晨起消退）→阴虚火旺、阴不制阳→六味地黄丸。壮热的特点是"量"（体温高、持续），潮热的特点是"时间"（有节律、定时发）。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——四种发热类型各有不同的信号</span><div class="ds-body"><strong>壮热（高热持续）</strong>——体温39度以上持续不退，伴大汗出、大烦渴（想喝冰水）、面红、脉洪大。病机为阳明气分热盛，热势弥漫全身。代表方白虎汤。若壮热伴腹满便秘、烦躁谵语→阳明腑实，用大承气汤（白虎清气、承气攻下，注意区别）。<strong>日晡潮热（申时发热）</strong>——每日下午3-5点发热明显，伴腹部硬满疼痛、便秘或热结旁流、烦躁、舌红苔黄燥起刺、脉沉实有力。病机为阳明腑实、燥屎内结→热从内发。代表方大承气汤。<strong>午后潮热（午后发热）</strong>——身热不扬（皮肤初摸不热、久摸才感觉烫）、午后热甚、伴头身困重、胸闷脘痞、苔黄腻。病机为湿遏热伏、湿热交蒸。代表方三仁汤。<strong>夜间潮热（入夜发热）</strong>——夜间发热、骨蒸潮热（骨头里往外透热）、五心烦热、盗汗、口干、舌红少苔、脉细数。病机为阴虚阳亢、虚火内扰。代表方六味地黄丸或清骨散。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——壮热与潮热、不同潮热之间最容易误判的情况</span><div class="ds-body">壮热和潮热的鉴别：壮热是体温一直高（持续性），潮热是体温有"起落"（规律性）。壮热病人会说"整天都烧"，潮热病人会说"每天下午/晚上才烧"。日晡潮热和午后潮热的鉴别：日晡潮热→便秘+腹满+苔黄燥→实热（大承气汤）；午后潮热→身重+脘痞+苔黄腻→湿热（三仁汤）。一为燥屎内结（干），一为湿热交蒸（黏）。夜间潮热和午后潮热的鉴别：夜间潮热→舌红少苔+盗汗→阴虚（虚热）；午后潮热→苔黄腻+脘痞→湿热（实热夹湿）。虚热和实热最核心的鉴别在舌象——虚热舌红少苔无苔，实热舌红苔黄腻。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是但热不寒，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（小儿 vs 成人）：小儿壮热极易惊厥（热极生风）→白虎汤加羚羊角、钩藤。成人壮热多伴脱水→白虎汤加人参（白虎加人参汤）。<strong>场景二</strong>（术后 vs 产后）：术后低热（午后或夜间）多瘀血发热→血府逐瘀汤；产后低热多血虚发热→当归补血汤。两者都是虚证为主，但病机不同。<strong>场景三</strong>（季节差异）：夏季但热不寒多夹暑湿（壮热+心烦+呕恶）→白虎加苍术汤。冬季但热不寒多纯热证。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-2-4 寒热往来的临床意义
# ═══════════════════════════════════════════
new_content_map['dx-2-4'] = '''<p><strong>寒热往来——恶寒与发热交替出现，是半表半里证的特征，需分辨发有定时与发无定时的不同。</strong></p><div class="classic-quote">《伤寒论》第96条："伤寒五六日，中风，往来寒热，胸胁苦满，默默不欲饮食，心烦喜呕……小柴胡汤主之。"<span class="src">——《伤寒论》</span></div><div class="mnem">寒热往来半表里，无定小柴有定疟；少阳和解小柴胡，疟疾达原或截疟。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">寒热往来<br>半表半里</span><span class="df-arrow">→</span><span class="df-node df-logic">邪正交争于<br>表里之间</span><span class="df-arrow">→</span><span class="df-node df-organ">无定时→少阳<br>有定时→疟疾</span><span class="df-arrow">→</span><span class="df-node df-symptom">小柴胡和解<br>达原饮化浊</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"一阵冷一阵热"——不是表证也不是里证，而是"夹在中间"</span><div class="ds-body">病人说"我一阵冷得要命、一阵又热得出汗，来回交替"。这和恶寒发热（同时出现）完全不同——寒热往来是交替出现：冷的时候不热、热的时候不冷。这说明病邪不在表（不在皮毛）、也不在里（不在脏腑），而是"卡"在了半表半里的位置——少阳经和膜原之间。张仲景在《伤寒论》中把这种情况归为少阳病，治法既不能用汗法（不在表）、也不能用下法（不在里），而是用"和法"——和解少阳。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">寒热往来的病机分析——"邪气在门缝里进进出出"</span><div class="ds-body">寒热往来的病机可以理解为"邪气在表里之间拉锯"：当邪气向表（靠近体表）→正邪交争→发热；当邪气向里（退回半表里）→正气不争→恶寒。形成"寒—热—寒—热"交替的周期性反应。如果寒热往来的时间没有规律（发无定时）→邪在少阳经。少阳位于太阳（表）和阳明（里）之间，是阳气出入的枢纽。用小柴胡汤和解少阳。如果寒热往来的时间固定（发有定时）→邪伏膜原。疟邪在膜原发作有节律，典型疟疾每隔一天或三天发作一次。用达原饮开达膜原。两者的共同点是邪气不在表也不在里，区别在于病位的深浅：少阳较浅（经络），膜原较深（半表半里深层）。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——发无定时的少阳病与发有定时的疟疾</span><div class="ds-body"><strong>少阳病（发无定时）</strong>——寒热往来没有固定时间规律，伴胸胁苦满（两胁胀闷不舒服）、默默不欲饮食、心烦喜呕、口苦咽干目眩。舌苔薄白或薄黄、脉弦。核心病机：邪犯少阳、枢机不利、正邪分争。代表方小柴胡汤（柴胡为君，疏透少阳半表之邪）。要记住少阳病四大主症：往来寒热、胸胁苦满、默默不欲饮食、心烦喜呕。<strong>疟疾（发有定时）</strong>——寒热往来有严格的周期性（一日一次、间日一次或三日一次），发作时先寒战（恶寒发抖）→后高热→大汗出→热退身凉。伴头痛、乏力。舌苔白腻、脉弦滑。核心病机：疟邪伏于膜原、与正气交争而作。代表方达原饮（开达膜原、辟秽化浊）。寒战明显用柴胡桂枝干姜汤，热重用白虎加桂枝汤。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——少阳病和疟疾最容易被误判的情况</span><div class="ds-body">少阳病和疟疾都以寒热往来为特征，但鉴别点是"时间的规律性"：少阳病→发无定时（今天上午冷热、明天下午冷热）→不具备严格的周期性→小柴胡汤。疟疾→发有定时（隔日一次、定时而发）→有严格的发作节律→达原饮。另外还要注意：有些疟疾早期可能节律不明显，但血涂片查疟原虫可确诊。另外还需注意寒热往来和恶寒发热（表证）的区分：恶寒发热→同时出现怕冷和发烧（现在又冷又热），寒热往来→交替出现（现在只冷或只热，过一会儿再变）。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是寒热往来，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（地域差异）：南方疟疾高发区患者出现定时寒热往来→首先考虑疟疾（达原饮）。北方非疟区患者寒热往来无定时→多考虑少阳病（小柴胡汤）。<strong>场景二</strong>（体质差异）：体壮者少阳病→小柴胡汤原方；体虚者少阳病→小柴胡汤加党参、黄芪（扶正祛邪）。<strong>场景三</strong>（兼夹证）：少阳病兼便秘→大柴胡汤（和解+通下）。少阳病兼小便不利→柴胡桂枝干姜汤。寒热往来伴剧烈头痛→注意是否为脑型疟疾，需紧急处理。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-3-1 特殊汗出的临床表现意义
# ═══════════════════════════════════════════
new_content_map['dx-3-1'] = '''<p><strong>自汗、盗汗、绝汗、战汗——四种特殊汗出对应完全不同的病机：气虚、阴虚、亡阳/亡阴、邪正交争的转折点。</strong></p><div class="classic-quote">《素问·阴阳别论》："阳加于阴谓之汗。"汗是阳气蒸化阴液从汗孔排出的产物——汗出异常反映了阴阳关系的失调。<span class="src">——《黄帝内经》</span></div><div class="mnem">自汗气虚白天漏，盗汗阴虚晚上偷；绝汗危重分阴阳，战汗转折细细究。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">四种特殊汗出</span><span class="df-arrow">→</span><span class="df-node df-logic">汗为心之液<br>阳加阴则为汗</span><span class="df-arrow">→</span><span class="df-node df-organ">自汗·盗汗<br>绝汗·战汗</span><span class="df-arrow">→</span><span class="df-node df-symptom">玉屏·归黄<br>参附·生脉</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"出汗"这件小事——漏汗、偷汗、绝汗、战汗，四种汗四种命</span><div class="ds-body">同样是出汗，有人白天坐着不动就冒汗（自汗）、有人晚上睡着了出一身汗（盗汗）、有人在危重时刻大汗淋漓（绝汗）、有人在高烧后突然出一身透汗（战汗）。中医把这些"特殊汗出"看作身体在发出不同的信号。问诊中要问清楚：什么时间出汗？出汗的部位？汗的温度和黏度？出完汗感觉更舒服还是更虚弱？每一个细节都指向不同的病机。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">四种汗出的病机分析——从"汗"看到体内的水火关系</span><div class="ds-body">汗是"阳气蒸化阴液"的产物——有足够的阴液作为原料，有足够的阳气作为热源，还要有正常的腠理（毛孔）开合功能，才能正常出汗。自汗（白天不动也出汗）→气虚不能固摄腠理→毛孔关不紧→漏汗。盗汗（入睡出汗、醒则汗止）→阴虚不能制阳→入睡后阳气入阴、虚火蒸腾阴液→偷汗。绝汗（危重时的大汗）→辨阴阳：冷汗清稀如水+肢厥→亡阳；热汗黏稠如油+身热→亡阴。战汗（发热后突然全身战栗出汗）→邪正交争的转折点：正胜邪退→汗出热退脉静身凉；邪胜正衰→汗出热不退。战汗是最"戏剧性"的汗——它意味着正邪正在决胜负。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——四种汗出各有不同的特征和治法</span><div class="ds-body"><strong>自汗</strong>——白天稍动或不动即出汗，伴神疲乏力、气短懒言、面色淡白、易感冒。舌淡苔白、脉虚弱。病机为气虚卫外不固。代表方玉屏风散（益气固表止汗）。气虚明显加四君子汤。<strong>盗汗</strong>——入睡即出汗、醒后汗止（"盗"意为偷偷地），伴五心烦热、口干咽燥、颧红、舌红少苔、脉细数。病机为阴虚火旺。代表方当归六黄汤（滋阴泻火固表）。阴虚为主用六味地黄丸。<strong>绝汗（脱汗）</strong>——危重时大汗淋漓。亡阳：冷汗清稀如水、四肢厥冷、脉微欲绝→参附汤回阳救逆。亡阴：汗热黏稠如油、身热烦躁、脉细数→生脉散益气救阴。临床常阴阳两脱，需参附+生脉同用。<strong>战汗</strong>——发热过程中突然全身战栗、随后大汗出。汗出热退脉静→正胜邪退（病愈向好转）；汗出热不退、烦躁→邪胜正衰（病情恶化）。治疗原则：战汗时不必用药，密切观察。汗出后注意补液和调护。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——自汗与盗汗、绝汗中亡阳与亡阴最容易误判的要点</span><div class="ds-body">自汗和盗汗的鉴别是基础考点：自汗→白天+不动也汗+气虚→玉屏风散。盗汗→睡着+醒来就停+阴虚→当归六黄汤。但临床最常见的混淆是"气虚自汗"和"气阴两虚自汗+盗汗并存"——很多病人白天也出汗、晚上也出汗，这是因为气阴两虚了，需要气阴双补（生脉散+玉屏风散）。亡阳和亡阴的鉴别是危重证的关键：核心看"汗"——亡阳→冷汗清稀如水（摸上去冷、不黏手）+四肢厥冷；亡阴→热汗黏腻如油（摸上去温热、黏手）+身热肢温。两组表现一字之差，治法却完全相反——参附汤（温热）vs 生脉散（甘凉）。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是出汗异常，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（更年期女性）：潮热+自汗+盗汗同时出现——肾阴虚、阴阳失调→二仙汤合六味地黄丸。<strong>场景二</strong>（大病初愈）：自汗乏力、稍动则喘→肺脾气虚→玉屏风散合四君子汤。<strong>场景三</strong>（肥胖体质）：白天汗多、动则尤甚、汗黏不爽→气虚夹湿→防己黄芪汤加减。<strong>场景四</strong>（手术后）：术后虚汗多→气血两虚→八珍汤加浮小麦、麻黄根。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-4-2 头痛胸痛胁痛胃脘痛腹痛的要点
# ═══════════════════════════════════════════
new_content_map['dx-4-2'] = '''<p><strong>不同部位的疼痛对应不同的脏腑经络——头痛分经、胸胁脘腹各有所属，问诊中要辨清疼痛部位和性质的组合。</strong></p><div class="classic-quote">《素问·举痛论》："经脉流行不止、环周不休，寒气入经而稽迟，涩而不行，客于脉外则血少，客于脉中则气不通，故卒然而痛。"<span class="src">——《黄帝内经》</span></div><div class="mnem">头痛太阳后阳明前，少阳两侧厥阴巅；胸闷痰饮刺痛瘀，胁胀肝郁刺痛瘀。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">疼痛部位辨证</span><span class="df-arrow">→</span><span class="df-node df-logic">不通则痛<br>不荣则痛</span><span class="df-arrow">→</span><span class="df-node df-organ">头痛分经<br>胸胁脘腹各有所属</span><span class="df-arrow">→</span><span class="df-node df-symptom">川芎茶调·血府逐瘀<br>柴胡疏肝·丹参饮</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"头痛"——同一个头，不同的位置指向不同的经脉和脏腑</span><div class="ds-body">同样是头痛，有人痛在后脑勺（太阳经）、有人痛在前额（阳明经）、有人在太阳穴两侧胀痛（少阳经）、有人在头顶痛（厥阴经）。中医的"头痛分经"理论来自于经络循行：每条经络都有自己的"管辖范围"，所以疼痛的部位就揭示了是哪条经络出了问题。除了分经，还要分性质：胀痛（气滞）、刺痛（瘀血）、重痛（湿邪）、灼痛（火热）、冷痛（寒邪/阳虚）。相同部位的疼痛+不同性质=不同的治法。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">疼痛的病机分析——"不通"和"不荣"两大总纲</span><div class="ds-body">疼痛的病机不外乎两种："不通则痛"和"不荣则痛"。不通则痛→实邪阻塞经络、气血运行不畅→痛势剧烈、拒按。气滞胀痛（柴胡疏肝散）、瘀血刺痛（血府逐瘀汤）、寒凝冷痛（良附丸）、湿热灼痛（龙胆泻肝汤）。不荣则痛→气血阴阳亏虚、脏腑经络失养→痛势绵绵、喜按。气虚隐痛（补中益气汤）、血虚隐痛（四物汤）、阳虚冷痛（理中汤）、阴虚灼痛（一贯煎）。问诊中区分疼痛性质的"拒按"与"喜按"是辨虚实的关键切入点。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——不同部位的疼痛各有辨证要点</span><div class="ds-body"><strong>头痛分经</strong>——太阳经（后脑勺）：风寒湿邪多见→川芎茶调散。阳明经（前额、眉棱骨）：阳明热盛→白虎汤或清胃散。少阳经（两侧太阳穴）：肝胆郁热→小柴胡汤或龙胆泻肝汤。厥阴经（巅顶）：寒凝厥阴→吴茱萸汤。<strong>胸痛</strong>——胸闷痛+痰多+苔腻→痰浊阻肺→瓜蒌薤白半夏汤。刺痛固定+夜间重→心血瘀阻→血府逐瘀汤。胸痛彻背+喘息→真心痛（心梗）→急服苏合香丸。<strong>胁痛</strong>——胀痛走窜+情绪波动→肝气郁结→柴胡疏肝散。刺痛固定+胁下痞块→瘀血阻络→血府逐瘀汤或旋覆花汤。<strong>胃脘痛</strong>——食后痛甚+胀满→食滞胃脘→保和丸。空腹痛甚+喜按→脾胃虚寒→黄芪建中汤。胃脘灼痛+反酸→肝胃郁热→左金丸。<strong>腹痛</strong>——绕脐痛+便秘→阳明腑实→大承气汤。少腹冷痛+得热减轻→寒凝肝脉→暖肝煎。腹痛泄泻+泻后痛减→肝郁脾虚→痛泻要方。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——头痛中最容易误判的经与经之间的"交界痛"</span><div class="ds-body">头痛分经最容易误判的是疼痛在两条经的交界处。例如，前额痛连眉棱骨→既可能是阳明经，也可能是厥阴经出前额。这时要看伴随症状：若伴鼻塞流涕、前额闷胀→阳明经；若伴巅顶跳痛、恶心→厥阴经。另一个难点是"全头痛"——整个头部都痛→可能是太阳经（太阳主一身之表，外感头痛多见全头痛）、也可能是气血亏虚（清窍失养）。鉴别点：外感全头痛→恶寒发热、脉浮紧；气血亏虚全头痛→劳累加重、脉细弱。胁痛中"肝气郁结"和"瘀血阻络"的鉴别：肝郁→胀痛窜走、情绪影响明显；瘀血→刺痛不移、夜间加重、舌有瘀斑。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是头痛，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（年轻人 vs 中老年）：25岁姑娘经期头痛（经前发作、胀痛、两侧）→肝郁血瘀→逍遥散合桃红四物汤。50岁男性高血压头痛（后脑勺胀痛、面红）→肝阳上亢→天麻钩藤饮。<strong>场景二</strong>（紧张型 vs 偏头痛）：工作压力大整日头痛（全头紧束感如戴帽）→气血郁滞→柴胡疏肝散合四物汤。偏头痛反复发作（一侧搏动性痛+恶心）→少阳经气不利→散偏汤。<strong>场景三</strong>（胸痛危急鉴别）：胸痛彻背+冷汗+气短→真心痛（心梗），需立即急救。胸痛位置固定+按压痛甚→肋间神经痛或软组织损伤，可用复元活血汤。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-4b-1 头晕
# ═══════════════════════════════════════════
new_content_map['dx-4b-1'] = '''<p><strong>头晕的四种常见证型——肝阳上亢、气血亏虚、痰湿内阻、肾精不足，需结合伴随症状和诱因进行鉴别。</strong></p><div class="classic-quote">《灵枢·口问》："上气不足，脑为之不满，耳为之苦鸣，头为之苦倾，目为之眩。"<span class="src">——《黄帝内经》</span></div><div class="mnem">晕胀肝阳天麻钩，晕白气血归脾收；晕重痰湿半夏术，晕鸣肾精左归求。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">头晕<br>四种病机</span><span class="df-arrow">→</span><span class="df-node df-logic">清窍失养<br>或邪扰清空</span><span class="df-arrow">→</span><span class="df-node df-organ">胀痛·面白·重裹·耳鸣</span><span class="df-arrow">→</span><span class="df-node df-symptom">天麻钩·归脾<br>半夏天麻·左归</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"头晕"——同样是天旋地转，病因可能完全不同</span><div class="ds-body">三个人都说"头晕"：一个说"头晕胀痛、血压高、面红耳赤"，一个说"蹲下站起来就眼前发黑"，还有一个说"头晕好像头上裹了块湿毛巾、身体沉重"。虽然都叫"头晕"，但中医透过"伴随症状"这个窗口看到了不同的病因——肝阳上亢是"气往上冲"导致头晕，气血亏虚是"头顶的血不够"导致头晕，痰湿内阻是"湿气蒙蔽了清窍"导致头晕。问诊中要问：除了头晕还有什么不舒服？什么情况下会加重？头晕的时候看东西转不转？</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">头晕的病机分析——"头是诸阳之会"出了问题</span><div class="ds-body">中医讲"头为诸阳之会、精明之府"——所有的阳气都汇聚到头部，大脑需要足够的气血和清阳之气来维持正常功能。头晕的病机归根结底有两类：一是"清窍失养"——气血亏虚或肾精不足→供不上足够的营养给头部（虚证）；二是"邪扰清空"——肝阳上亢（气火往上冲）或痰湿内阻（浊气蒙蔽）→干扰了头部的正常功能（实证/虚实夹杂）。肝阳上亢：肝肾阴虚→肝阳亢盛于上→气血随之上冲→头晕胀痛。气血亏虚：脾胃虚弱+失血→气血不能上荣于脑→头晕面白。痰湿内阻：脾失运化→痰湿内生→上蒙清窍→头晕重如裹。肾精不足：肾虚不能生髓→髓海空虚→头晕耳鸣。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——四种头晕各有不同的"标志性信号"</span><div class="ds-body"><strong>肝阳上亢</strong>——头晕胀痛+面红目赤+急躁易怒+失眠多梦+血压升高+舌红苔黄+脉弦有力。病机为肝肾阴亏、肝阳亢逆。代表方天麻钩藤饮（平肝潜阳）。注意与肝火上炎鉴别：肝阳上亢是本虚标实（下面肝肾阴虚、上面肝阳亢），肝火上炎是纯实热——前者用天麻钩藤饮（平肝+滋补），后者用龙胆泻肝汤（纯清）。<strong>气血亏虚</strong>——头晕+面色淡白或萎黄+神疲乏力+心悸失眠+蹲起发黑+劳累加重+舌淡+脉细弱。病机为气血不足、清窍失养。代表方归脾汤或八珍汤（益气养血）。<strong>痰湿内阻</strong>——头晕重如裹+头昏沉闷胀+胸闷呕恶+纳呆+肢体困重+苔白腻+脉滑。病机为痰湿中阻、清阳不升。代表方半夏白术天麻汤（燥湿化痰、息风止晕）。<strong>肾精不足</strong>——头晕耳鸣+腰膝酸软+健忘+精神萎靡+舌淡+脉沉细。偏阴虚者伴五心烦热（左归丸），偏阳虚者伴畏寒肢冷（右归丸）。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——头晕中最容易误判的肝阳上亢和痰湿内阻</span><div class="ds-body">肝阳上亢和痰湿内阻都可以引起头晕，但治法完全不同——前者要"降火平肝"，后者要"化痰祛湿"。鉴别要点：肝阳上亢→头晕胀痛（感觉血管在跳）+面红+易怒+血压高+苔黄脉弦→天麻钩藤饮。痰湿内阻→头晕重如裹（头被蒙住的感觉）+胸闷+呕恶+苔白腻+脉滑→半夏白术天麻汤。一"胀"一"重"，一"红"一"腻"——这是鉴别的关键词。另外，气血亏虚和肾精不足的鉴别：气血亏虚→蹲起加重+面白+心悸+月经少→补气血；肾精不足→伴腰酸+耳鸣+健忘+齿摇发脱→补肾填精。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是头晕，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（高血压患者）：头晕胀痛+面红+血压升高→肝阳上亢→天麻钩藤饮。若长期血压控制不佳、头晕伴耳鸣+腰酸→阴虚阳亢，加杞菊地黄丸。<strong>场景二</strong>（年轻女性）：经期头晕+面白+月经量少→血虚→四物汤加味。劳累后头晕+乏力+食欲差→脾虚气血不足→归脾汤。<strong>场景三</strong>（老年人）：慢性头晕+耳鸣+健忘+腰酸→肾精不足→左归丸。头晕+走路不稳+肢体麻木→注意中风气虚血瘀→补阳还五汤。<strong>场景四</strong>（颈椎病患者）：转头时头晕加重+颈项强痛→痰瘀阻络→半夏白术天麻汤合通窍活血汤。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-5b-1 耳鸣耳聋
# ═══════════════════════════════════════════
new_content_map['dx-5b-1'] = '''<p><strong>耳鸣耳聋——突发声大为实证（肝火上炎），渐发声细为虚证（肾精不足），辨虚实的关键在起病缓急和声音性质。</strong></p><div class="classic-quote">《灵枢·脉度》："肾气通于耳，肾和则耳能闻五音矣。"<span class="src">——《黄帝内经》</span></div><div class="mnem">突鸣声大肝火龙胆泻，渐鸣声细肾虚左慈丸；实按不减虚按可减，新病久病要细参。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">耳鸣耳聋<br>实虚两途</span><span class="df-arrow">→</span><span class="df-node df-logic">实→肝火上扰<br>虚→肾精亏虚</span><span class="df-arrow">→</span><span class="df-node df-organ">突发声大按不减<br>vs渐进声细按可减</span><span class="df-arrow">→</span><span class="df-node df-symptom">龙胆泻肝汤<br>vs耳聋左慈丸</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"耳朵嗡嗡响"——有人像潮水有人像蝉鸣，声音就是诊断信号</span><div class="ds-body">两个耳鸣病人走进诊室：一个说"耳朵突然嗡嗡响、声大得像潮水、按着还响"，另一个说"耳鸣好几年了、声音像蝉叫（吱——）、晚上安静时更明显、用手按着会好一点"。同样是耳鸣，一个是实证（肝火上炎——火气往上冲），一个是虚证（肾精不足——耳朵的营养不够了）。中医问诊治耳鸣的第一问就是：耳鸣是突然出现的还是慢慢加重的？声音是大还是小？用手按耳朵会好转还是没变化？</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">耳鸣耳聋的病机分析——"肾开窍于耳"和"肝胆绕耳"</span><div class="ds-body">耳与两个脏腑有密切关系：肾开窍于耳（耳朵的听力靠肾精滋养），肝胆的经络绕行于耳（肝胆之气可以"上冲"到耳朵）。所以耳鸣耳聋的病因分虚实两大类：实证→肝胆之火上扰→"火"顺着经络冲到耳朵→耳鸣声大如潮、突发→龙胆泻肝汤清肝胆实火。虚证→肾精不足→耳朵得不到足够的精血供养→听力逐渐下降、耳鸣声细如蝉→耳聋左慈丸滋肾填精。另外还有痰火上扰（耳鸣+胸闷+苔黄腻→温胆汤）和气血瘀阻（外伤后耳鸣+舌紫暗→通窍活血汤）等兼夹证。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——实火和肾虚的鉴别要点</span><div class="ds-body"><strong>肝火上炎（实证）</strong>——突发耳鸣耳聋、声大如潮或如雷、按之不减。伴头痛面红、目赤口苦、烦躁易怒、胁痛、大便秘结、小便黄。舌红苔黄、脉弦数有力。病机为肝气郁结化火、火性上炎、循经上扰耳窍。代表方龙胆泻肝汤（清泻肝胆实火）。<strong>肾精不足（虚证）</strong>——渐进耳鸣耳聋、声细如蝉鸣、按之可减轻。伴头晕目眩、腰膝酸软、健忘失眠、口干咽燥。偏阴虚加五心烦热、舌红少苔、脉细数（耳聋左慈丸：六味地黄丸加磁石、五味子）。偏阳虚加畏寒肢冷、舌淡、脉沉迟（右归丸）。<strong>痰火郁结（实证）</strong>——耳鸣声如机器轰鸣、时轻时重。伴胸闷痰多、口苦黏腻、二便不畅。舌红苔黄腻、脉滑数。代表方温胆汤加礞石、黄芩。（介于纯实和纯虚之间的兼夹证）</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——"按之"减轻还是不减轻——最简单的虚实鉴别法</span><div class="ds-body">耳鸣最简单实用的虚实鉴别方法就是"按耳朵"：用手掌按住耳廓轻轻按压→耳鸣减轻或消失→虚证（按的时候让气血暂时回流到耳朵，减轻了虚性耳鸣）。按了反而更响或没变化→实证（按了之后火气被堵、冲得更厉害）。这个"按耳鉴别法"在临床问诊中非常实用。另外还需要注意：老年人耳鸣大部分是肾虚（加减退的生理性衰退），但也有老年耳鸣伴高血压、面红→肝阳上亢→天麻钩藤饮加味。同一个病人可以虚实夹杂——既有肾精不足的基础、又因为生气导致肝火上冲、两者相加导致耳鸣加重→治法要标本兼顾（左归丸合龙胆泻肝汤加减）。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是耳鸣，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（年轻人 vs 老年人）：25岁因熬夜+暴怒后突发耳鸣、声大面红口苦→肝火上炎→龙胆泻肝汤。70岁渐进耳鸣多年、声细如蝉、伴腰酸健忘→肾精不足→耳聋左慈丸。<strong>场景二</strong>（感冒后）：感冒后耳闷耳鸣、伴鼻塞咳嗽→风热上扰耳窍→银翘散加辛夷、苍耳子。注意和肝火的区别：感冒后耳鸣多伴耳闷感（像有东西堵住），肝火耳鸣是"轰隆隆"的响。<strong>场景三</strong>（职业因素）：长期在噪音环境中工作→耳鸣声高、听力下降、伴头晕→实证为主、气火上逆→龙胆泻肝汤合通窍活血汤。长期用耳机→耳鸣如蝉、听力下降→多虚少实→六味地黄丸。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-5b-2 目眩
# ═══════════════════════════════════════════
new_content_map['dx-5b-2'] = '''<p><strong>目眩——视物旋转如坐舟车，多属肝阳上亢或肝风内动，也可见于气血亏虚和痰湿中阻。</strong></p><div class="classic-quote">《素问·至真要大论》："诸风掉眩，皆属于肝。"目眩以肝为根本，涉及虚、风、痰、火诸端。<span class="src">——《黄帝内经》</span></div><div class="mnem">目眩属肝风内动，面赤肝阳天麻钩；面白气血归脾用，呕恶痰湿半夏天。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">目眩<br>视物旋转</span><span class="df-arrow">→</span><span class="df-node df-logic">肝风内动<br>或清窍失养</span><span class="df-arrow">→</span><span class="df-node df-organ">面赤·面白<br>呕恶·腰酸</span><span class="df-arrow">→</span><span class="df-node df-symptom">天麻钩·归脾<br>半夏术·左归</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"天旋地转"——从伴随症状看目眩的真正原因</span><div class="ds-body">目眩（视物旋转、自身感觉晃动）和头晕不同——目眩是"感觉周围在转"（旋转感），头晕是"感觉头昏沉"（非旋转感）。一个目眩患者来说"我一躺下就天旋地转"，但有人目眩+面红耳赤（肝阳上亢）、有人目眩+面色苍白（气血亏虚）、有人目眩+恶心呕吐（痰湿中阻）。伴随症状就像"路标"，指示着不同的病机方向。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">目眩的病机分析——"诸风掉眩，皆属于肝"</span><div class="ds-body">《内经》提出"诸风掉眩，皆属于肝"——目眩的"晃动"、"旋转"感属于"风"的特性（风性主动）。所以目眩的核心病机是"肝风内动"——但肝风从哪里来呢？主要有三条途径：肝阳化风（肝肾阴虚→肝阳亢盛→亢到极致就生风）→目眩+面红+血压高→天麻钩藤饮。血虚生风（肝藏血、血虚不能养肝→虚风内生）→目眩+面色苍白+爪甲不荣→四物汤加味。热极生风（高烧至极→肝风妄动）→目眩+高热+抽搐→羚角钩藤汤。此外还有痰湿中阻→目眩+呕恶+苔腻→半夏白术天麻汤（"无痰不作眩"）。所以目眩的病机可以概括为"不离乎肝，不止乎肝"。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——目眩四型各有不同的"指向标"</span><div class="ds-body"><strong>肝阳上亢化风</strong>——目眩+头晕胀痛+面红目赤+急躁易怒+失眠多梦+舌红苔黄+脉弦有力。病机为肝肾阴虚、肝阳亢逆化风。代表方天麻钩藤饮（平肝潜阳息风）。<strong>气血亏虚</strong>——目眩+面色淡白+神疲乏力+心悸失眠+劳累加重+舌淡脉细。病机为气血不足、清窍失养。代表方归脾汤（益气养血）。<strong>痰湿中阻</strong>——目眩+头重如蒙+胸闷呕恶+纳呆+肢体困重+苔白腻+脉滑。病机为痰湿内停、上蒙清窍。代表方半夏白术天麻汤（化痰息风）。<strong>肾精不足</strong>——目眩+腰膝酸软+耳鸣+健忘+精神萎靡+舌淡脉沉。偏阴虚用左归丸，偏阳虚用右归丸。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——"目眩"和"头晕"的本质区别</span><div class="ds-body">目眩（眩晕）的核心特征是"旋转感"——感觉自身或周围物体在旋转、晃动（如坐舟车）。头晕的核心特征是"昏沉感"——头重脚轻、眼前发黑、头脑不清醒。两者虽然常常同时出现，但病机侧重点不同：目眩→多与"风"相关（肝风内动）→病在肝。头晕→多与"虚"和"湿"相关（气血亏虚/痰湿）→病在脾肾。目眩和"中风"的鉴别很重要：目眩本身不是中风，但肝阳上亢导致的严重目眩是中风的前兆信号——如果目眩+一过性肢体麻木+言语不利→必须警惕中风（脑卒中）的发生。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是目眩，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（位置性 vs 持续性）：躺下或翻身时突发目眩十几秒→耳石症（良性位置性眩晕）→手法复位为主，中药可配合天麻钩藤饮加减。持续目眩数小时甚至整天→中枢性或前庭性眩晕→辨证施治。<strong>场景二</strong>（颈椎病相关性）：目眩+转头加重+颈项僵痛→椎动脉型颈椎病→痰瘀阻络→半夏白术天麻汤合颈复康制剂。<strong>场景三</strong>（梅尼埃病）：发作性目眩+耳鸣耳闷+恶心呕吐→属"痰湿中阻"范畴→泽泻汤合半夏白术天麻汤（"无痰不作眩"的典型）。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-6b-1 失眠
# ═══════════════════════════════════════════
new_content_map['dx-6b-1'] = '''<p><strong>失眠的四证分型——入睡困难心肾不交、睡后易醒心脾两虚、多噩梦痰热扰心、彻夜不眠肝火扰心。</strong></p><div class="classic-quote">《灵枢·大惑论》："卫气不得入于阴，常留于阳。留于阳则阳气满，阳气满则阳跷盛，不得入于阴则阴气虚，故目不瞑矣。"<span class="src">——《黄帝内经》</span></div><div class="mnem">失眠入睡难交泰丸，易醒心脾归脾煎；多噩梦温胆汤，彻夜不眠龙胆篇。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">失眠<br>四种类型</span><span class="df-arrow">→</span><span class="df-node df-logic">阳不入阴<br>心神不宁</span><span class="df-arrow">→</span><span class="df-node df-organ">难入睡·易醒<br>噩梦·彻夜</span><span class="df-arrow">→</span><span class="df-node df-symptom">交泰·归脾<br>温胆·龙胆</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"睡不着"——同样是失眠，不同的"睡不着方式"指向不同的病因</span><div class="ds-body">四个人都说"我失眠"——第一个说"翻来覆去睡不着、心烦意乱"（入睡困难），第二个说"睡着了但一两个小时就醒、醒了再也睡不着"（睡后易醒），第三个说"整晚做噩梦、被吓醒"（多噩梦），第四个说"整夜眼睛睁着、根本睡不着"（彻夜不眠）。虽然都算失眠，但这些不同的"睡不着方式"指向不同的病机和证型。失眠的问诊要点：什么时间开始失眠？是睡不着还是容易醒？有没有做梦？白天精神状态怎么样？有没有心烦、心悸、胃口好坏？</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">失眠的病机分析——"阳不入阴"是总病机</span><div class="ds-body">《灵枢》说"卫气不得入于阴……故目不瞑"——人在白天阳气浮于外（清醒活动），到了晚上阳气应"入于阴"（进入体内休息）→人才能入睡。如果阳气不能顺利入阴→失眠。所以失眠的核心是"阴阳失调、阳不入阴"。心肾不交（入睡困难）→心火（阳）不能下降温肾水、肾水（阴）不能上济制心火→心火独亢于上→烦躁失眠。心脾两虚（睡后易醒）→脾不生血→心失血养→心神浮越→睡不踏实。痰热扰心（多噩梦）→痰热内蕴→扰乱心神→噩梦纷纭。肝火扰心（彻夜不眠）→肝郁化火→火性上炎→心神被扰→烦躁彻夜不睡。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——四种失眠类型各有特征</span><div class="ds-body"><strong>心肾不交（入睡困难）</strong>——难以入睡、心烦不寐、心悸多梦、伴腰膝酸软、五心烦热、口燥咽干。舌红少苔、脉细数。病机为肾阴不足、心火亢盛、水火不济。代表方交泰丸（黄连+肉桂，交通心肾）。黄连清心火、肉桂引火归原，一寒一热使心肾相交。<strong>心脾两虚（睡后易醒）</strong>——睡后易醒、醒后难再入睡、多梦、伴心悸健忘、神疲乏力、纳差腹胀、面色萎黄。舌淡苔薄白、脉细弱。病机为脾气虚弱、心血不足、心神失养。代表方归脾汤（益气健脾、养血安神）。<strong>痰热扰心（多噩梦）</strong>——心烦失眠、多噩梦纷纭、易被吓醒、伴胸闷脘痞、呕恶口苦、头重目眩。舌红苔黄腻、脉滑数。病机为痰热内蕴、扰乱心神。代表方温胆汤（清热化痰、安神定志）。<strong>肝火扰心（彻夜不眠）</strong>——彻夜不眠或入睡极难、烦躁易怒、伴头晕胀痛、目赤耳鸣、口干苦、大便秘结。舌红苔黄、脉弦数。病机为肝郁化火、火扰心神。代表方龙胆泻肝汤（清肝泻火、安神）加磁石、龙骨。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——失眠中"虚实"最关键的鉴别点</span><div class="ds-body">失眠的虚实证鉴别是处方用药的核心：实证失眠（心肾不交、痰热扰心、肝火扰心）→用清热安神法（黄连、栀子、龙胆草）；虚证失眠（心脾两虚）→用养心安神法（酸枣仁、远志、龙眼肉）。心肾不交和肝火扰心都表现为烦躁失眠，但心肾不交→伴"下面虚"（腰酸腿软、五心烦热），是虚实夹杂；肝火扰心→伴"上面实"（头晕胀痛、目赤口苦），是纯实证。心脾两虚和痰热扰心都表现为多梦，但心脾两虚→噩梦+醒后疲乏+面白+舌淡；痰热扰心→噩梦+醒后胸闷+口苦+苔黄腻。一句话：实证失眠看"烦"（烦躁不安），虚证失眠看"乏"（疲乏无力）。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是失眠，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（职场压力型）：工作压力大入睡困难+心烦焦虑→心肾不交→交泰丸合黄连阿胶汤。加班熬夜后彻夜失眠+烦躁口苦→肝火扰心→龙胆泻肝汤加磁石、龙骨。<strong>场景二</strong>（更年期女性）：失眠+潮热盗汗+心烦易怒→阴虚火旺、心肾不交→黄连阿胶汤合六味地黄丸。同时伴情绪低落→加逍遥散。<strong>场景三</strong>（老年人）：入睡困难+早醒+健忘+夜尿多→肾精亏虚、心肾不交→左归丸合交泰丸。睡后易醒+纳差腹胀→心脾两虚→归脾汤。<strong>场景四</strong>（学生/脑力劳动者）：多噩梦+睡醒不解乏+胸闷口苦→痰热扰心→温胆汤加远志、石菖蒲。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-6b-2 嗜睡
# ═══════════════════════════════════════════
new_content_map['dx-6b-2'] = '''<p><strong>嗜睡——时时欲睡、呼之即醒，是阳气不足或湿困清阳的表现，需辨痰湿、脾虚和阳虚三种类型。</strong></p><div class="classic-quote">《灵枢·寒热病》："阳气盛则瞋目，阴气盛则瞑目。"嗜睡的本质是阳气衰微、不能振奋精神。<span class="src">——《黄帝内经》</span></div><div class="mnem">困倦头昏痰湿困，饭后思睡脾虚证；极度嗜睡心阳虚，三型嗜睡各不同。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">嗜睡<br>阳气不足</span><span class="df-arrow">→</span><span class="df-node df-logic">阳不振奋<br>清阳不升</span><span class="df-arrow">→</span><span class="df-node df-organ">困倦·饭后<br>极度嗜睡</span><span class="df-arrow">→</span><span class="df-node df-symptom">平胃·六君<br>四逆加参</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"怎么都睡不够"——白天总打瞌睡也是病</span><div class="ds-body">失眠是睡不着，嗜睡是睡不够。病人说"白天上课开会总是打瞌睡""吃完饭就睁不开眼睛""躺下就能睡着、但醒来还是困"。嗜睡反映了阳气的不足——白天阳气应该浮于外（让精神清醒活跃），但阳气不够了、升不上来→精神萎靡、时时欲睡。嗜睡不是"能睡是福"——它是身体发出的警示信号，提示阳气不振、清阳不升。中医问诊中要问：什么时间最困？饭后还是全天？睡完精神好还是仍然疲倦？</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">嗜睡的病机分析——"阳气不能上荣于脑"</span><div class="ds-body">人清醒时，阳气"上荣于脑"——营养和精神都供应到头部→神清气爽。嗜睡时，阳气"不足"或"被阻滞"→头部得不到足够的阳气→昏昏欲睡。三种病机：痰湿困脾→脾主运化水湿→脾气虚弱→湿浊内生→湿气"蒙蔽"了清阳之气的上升通道→头重困倦嗜睡。平胃散燥湿运脾。脾气虚弱→脾为气血生化之源→脾虚→气血生成不足→饭后气血被调去消化食物、头部供血更少→饭后嗜睡明显。六君子汤健脾益气。心肾阳虚→阳气极度衰微→不能温养心神→极度嗜睡、昏昏沉沉、精神萎靡。四逆汤加人参回阳救逆。三者从浅到深——痰湿轻证→脾虚中证→阳虚重证。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——三种嗜睡类型的鉴别</span><div class="ds-body"><strong>痰湿困脾</strong>——困倦嗜睡+头昏头重如蒙+身体困重+胸闷脘痞+纳呆+大便黏滞+苔白腻+脉濡缓。病机为湿浊困阻脾阳、清阳不升。代表方平胃散合藿朴夏苓汤（燥湿健脾、醒神开窍）。<strong>脾气虚弱</strong>——饭后嗜睡明显+神疲乏力+面色萎黄+纳差腹胀+大便溏薄+舌淡有齿痕+脉虚弱。病机为脾胃虚弱、气血生化不足、食后气血更虚。代表方六君子汤或补中益气汤（健脾益气）。<strong>心肾阳虚</strong>——极度嗜睡（不分时间地点都想睡）+精神萎靡+畏寒肢冷+腰膝酸冷+面色苍白+舌淡胖苔白滑+脉沉微欲绝。病机为心肾阳衰、神失温养。代表方四逆汤加人参或右归丸（温补心肾）。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——"嗜睡"和"但欲寐"——一字之差，病机深浅完全不同</span><div class="ds-body">嗜睡和但欲寐（少阴病"但欲寐"）的区别在于"深度"：嗜睡→呼之即醒、醒了还能正常活动、只是过一会儿又想睡→病在脾（浅层）。但欲寐→精神极度萎靡、似睡非睡、呼之能应但随即又睡、反应迟钝→病在少阴心肾（深层）→危重证。另外，嗜睡和"昏迷"也要鉴别：嗜睡→能被叫醒、能回答问题、认知功能基本正常。昏迷→不能被唤醒、对刺激无反应→危重。还需注意：老年人轻度嗜睡（白天打盹）不一定是病态，但如果伴反应迟钝、健忘加重→注意老年痴呆早期信号。小儿嗜睡+发热→注意脑炎等急性病。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是嗜睡，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（肥胖者 vs 瘦弱者）：肥胖者嗜睡+头昏+身重+打鼾→痰湿困脾→平胃散合导痰汤。瘦弱者嗜睡+饭后加重+乏力→脾气虚弱→补中益气汤。<strong>场景二</strong>（春季 vs 长夏）：春困（春季嗜睡+乏力）→多属季节性脾虚湿困→藿朴夏苓汤。长夏（梅雨季节）嗜睡+头重如裹+胸闷+苔腻→湿困脾胃明显→平胃散合三仁汤。<strong>场景三</strong>（大病后）：久病或大病后嗜睡+乏力→气血两虚→十全大补汤。若大病后嗜睡+肢冷+脉微→阳气欲脱→四逆汤加人参。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-7b-1 口渴与饮水
# ═══════════════════════════════════════════
new_content_map['dx-7b-1'] = '''<p><strong>口渴与饮水是反映体内津液状态的重要窗口——渴喜冷饮为热盛伤津、渴不多饮为湿热或水逆、口干不欲咽为阴虚。</strong></p><div class="classic-quote">《伤寒论》第71条："太阳病，发汗后，大汗出，胃中干，烦躁不得眠，欲得饮水者，少少与饮之，令胃气和则愈。"<span class="src">——《伤寒论》</span></div><div class="mnem">渴喜冷饮热盛伤，渴不多饮湿或水；口干漱口不咽下，阴虚燥热津液亏。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">口渴与饮水<br>津液窗口</span><span class="df-arrow">→</span><span class="df-node df-logic">渴+冷饮→热<br>渴+不多→湿<br>漱口不咽→阴虚</span><span class="df-arrow">→</span><span class="df-node df-organ">白虎汤·三仁<br>五苓散·益胃</span><span class="df-arrow">→</span><span class="df-node df-symptom">清热生津<br>化湿利水·滋阴</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"口渴"——不只是"缺水"，关键是"怎么喝"</span><div class="ds-body">三个人都说"口渴"——一个说"渴得不行、想喝冰水、一大杯不够"（渴喜冷饮），一个说"口渴但不想喝、喝几口就不想喝了"（渴不多饮），还有一个说"口干、漱漱口就舒服了但不想咽下去"（口干漱口不咽）。这些不同的"喝法"暴露了不同的病机：渴喜冷饮→体内有实热（热盛伤津→白虎汤）；渴不多饮→湿热内蕴或水饮内停（水被堵住了→三仁汤/五苓散）；口干漱口不咽→阴虚津亏（不是水多了而是身体缺水了→益胃汤/六味地黄丸）。问口渴不只是问"渴不渴"，要追问"想喝热的还是冷的""喝多少""喝完之后舒服吗"。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">口渴与饮水的病机分析——"水"在体内的三种异常状态</span><div class="ds-body">口渴的核心是"津液"出了问题——但津液问题有三种不同的性质：津液被耗伤（热盛伤津）→热量太大把水分烤干了→身体急需补水→大渴、喜冷饮、想大口喝→白虎汤清热生津。津液分布异常（湿热/水饮）→身体总体不缺水、但水分布在了不该在的地方（湿困中焦或水蓄下焦）→导致嘴里"渴"但肚子里"不缺水"→渴不多饮、甚至水入即吐→三仁汤化湿或五苓散利水。津液化生不足（阴虚）→身体本身缺水（阴液亏虚）→但虚热不重→口干、但不想大口喝水、只想润一润→益胃汤/六味地黄丸滋阴生津。三种情况只有第一种需要"补水"——后两种需要"调水"和"生水"。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——三种口渴类型各有不同的"饮水模式"</span><div class="ds-body"><strong>热盛伤津（实热证）</strong>——大渴喜冷饮（大口喝冰水）、饮水量大、伴壮热面红、大汗出、烦躁、舌红苔黄燥、脉洪大。病机为阳明气分热盛、津液被耗。代表方白虎汤（清热生津止渴）。若渴饮不止+尿多→上消（糖尿病）→消渴方或白虎加人参汤。<strong>湿热内蕴/水饮内停</strong>——渴不多饮（口渴但不想喝水或喝几口就打住）、或水入即吐。伴胸闷脘痞、身重头昏、小便不利。苔黄腻（湿热）→三仁汤清热化湿。苔白滑+水入即吐（水逆）→五苓散化气利水。注意区别：湿热以"黏腻"为特征（苔黄腻、大便黏），水逆以"吐水"为特征（喝了就吐）。<strong>阴虚津亏（虚热证）</strong>——口干咽燥但不多饮、或只漱口不咽、或半夜口干明显。伴五心烦热、盗汗、舌红少苔或无苔、脉细数。病机为阴液亏虚、津不上承。代表方益胃汤（胃阴虚）或六味地黄丸（肾阴虚）。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——"渴不多饮"中最容易被混淆的湿热和水饮</span><div class="ds-body">渴不多饮是临床问诊中最容易问到但最容易被误解的体征。同样是"渴但不想多喝"，湿热和水饮的病机不同：湿热→水分布异常+热→苔黄腻、胸闷、身重、大便黏滞→三仁汤（清热化湿）。水饮→水蓄下焦、气化不利→苔白滑、水入即吐、小便不利→五苓散（化气利水）。区分要点：湿热有"热"的表现（苔黄、烦躁、口苦），水饮有"水"的表现（舌水滑、水声、浮肿）。另外还常遇到"渴喜热饮"——当病人说"口渴但想喝热水"→多属阳虚不能蒸化津液或痰饮内停→不是实热证！用温化法（苓桂术甘汤）而非清热法。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是口渴，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（糖尿病患者）：口渴多饮+多食+多尿+消瘦→上消（肺热津伤）→消渴方。伴乏力+气短→气阴两虚→生脉散合玉女煎。<strong>场景二</strong>（慢性咽炎）：咽干口燥、但不渴、总想清嗓子、刷牙恶心→阴虚痰气交阻→玄麦甘桔汤合半夏厚朴汤。<strong>场景三</strong>（放疗后/干燥综合征）：严重口干+眼干+需频频饮水→阴液大伤→增液汤合沙参麦冬汤长期调理。<strong>场景四</strong>（夏季暑热）：夏季口干渴+汗多+心烦+身热→暑热伤津→王氏清暑益气汤。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-7b-2 食欲与食量
# ═══════════════════════════════════════════
new_content_map['dx-7b-2'] = '''<p><strong>食欲与食量反映脾胃运化功能——纳呆为脾失健运、消谷善饥为胃火炽盛、饥不欲食为胃阴不足、厌食为食积或肝胆湿热。</strong></p><div class="classic-quote">《灵枢·大惑论》："胃热则消谷，谷消故善饥。"<span class="src">——《黄帝内经》</span></div><div class="mnem">纳呆脾虚参苓术，消谷善饥玉女煎；饥不欲食益胃汤，厌食食积保和丸。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">食欲异常<br>脾胃信号</span><span class="df-arrow">→</span><span class="df-node df-logic">脾主运化<br>胃主受纳</span><span class="df-arrow">→</span><span class="df-node df-organ">纳呆·消谷<br>饥不食·厌食</span><span class="df-arrow">→</span><span class="df-node df-symptom">参苓·玉女<br>益胃·保和</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"吃不下"和"吃不饱"——两个极端一个在脾一个在胃</span><div class="ds-body">两个病人：一个说"什么都不想吃、吃一点点就胀、没胃口"（纳呆），另一个说"刚吃完又饿了、吃得多但瘦"（消谷善饥）。"不想吃"和"吃不饱"看起来相反，但都说明脾胃出了毛病——纳呆是脾胃运化功能减退（推不动了），消谷善饥是胃火过旺（烧得太快）。还有第三种人，"饿但是吃不下，吃几口就饱了"（饥不欲食）——这不是胃火也不是脾虚，而是胃阴虚了（胃壁失去了滋润）。问食欲要问：想吃不想吃？吃得多还是少？吃完后肚子胀不胀？饿得快不快？</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">食欲异常的���机分析——脾和胃的"分工合作"出了问题</span><div class="ds-body">中医讲"脾主运化、胃主受纳"——胃负责装食物和初步腐熟（接受），脾负责把食物转化成气血并输送到全身（运化）。纳呆（不想吃+吃得少+食后腹胀）→脾失健运——脾的运化功能减退、吃进去的东西"堆积"在胃里不处理→人自然不想再吃了。参苓白术散健脾益气。消谷善饥（吃得多+饿得快+人瘦）→胃火炽盛——胃的腐熟功能过于亢进、食物被"烧"得太快→很快就又饿了。玉女煎清胃火。饥不欲食（饿但吃不下+口干）→胃阴不足——胃有"火"但没有"水"——空的火在烧所以感觉饿、但胃壁没有津液滋润所以吃不下。益胃汤滋养胃阴。厌食（对食物厌恶）→食积（伤食——吃了太多不消化）或肝胆湿热（肝的疏泄功能影响脾胃）。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——四种食欲异常的鉴别</span><div class="ds-body"><strong>纳呆（脾失健运）</strong>——食欲不振、食量减少、食后腹胀、伴神疲乏力、面色萎黄、大便溏薄、舌淡苔白、脉虚弱。病机为脾胃虚弱、运化无力。代表方参苓白术散（健脾益气）。兼湿困→加平胃散（燥湿运脾）。<strong>消谷善饥（胃火炽盛）</strong>——食欲亢进、食量增加、食后不久即饿、伴形体消瘦、口干口渴、大便干结、舌红苔黄、脉滑数。病机为胃火亢盛、腐熟太过。代表方玉女煎（清胃泻火）或白虎汤。若消谷善饥+多饮多尿→中消（糖尿病）→调胃承气汤或六味地黄丸。<strong>饥不欲食（胃阴不足）</strong>——有饥饿感但不想吃、或吃几口就停、伴胃脘嘈杂（胃里不舒服的感觉）、口干咽燥、干呕呃逆、舌红少苔或无苔、脉细数。病机为胃阴亏虚、受纳失职。代表方益胃汤（滋养胃阴）。<strong>厌食</strong>——厌恶食物、甚至闻到味道就恶心。伤食（食积）→嗳腐吞酸、脘腹胀满、苔厚腻→保和丸消食导滞。肝胆湿热→厌食油腻+胁痛口苦+苔黄腻→龙胆泻肝汤清热利湿。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——"纳呆"和"饥不欲食"——都不想吃但原因完全不同</span><div class="ds-body">纳呆和饥不欲食都表现为"不想吃"或"吃得少"，但病机不同：纳呆（脾失健运）→完全不饿、没有食欲→饭后腹胀加重→脾气虚+可能夹湿→参苓白术散。饥不欲食（胃阴不足）→有饥饿感（胃里有火）→但吃不下（胃没有津液来接受食物）→嘈杂（胃里不舒服的感觉）→益胃汤。一句话：纳呆是"不想吃"（脾胃推不动了），饥不欲食是"想吃但吃不下"（胃壁干了）。还有消谷善饥（胃火）和甲亢的鉴别：胃火消谷善饥→只涉及胃（伴口渴便秘）；甲亢→涉及全身代谢（伴心悸手抖、多汗、急躁、突眼、脉数），需要结合全身表现。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是食欲异常，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（儿童 vs 老人）：小儿厌食+腹胀+大便酸臭→食积→保和丸。老人纳呆+乏力+便溏→脾虚→参苓白术散。<strong>场景二</strong>（妊娠 vs 大病后）：妊娠早期恶心厌食→恶阻→橘皮竹茹汤。大病后食欲不振+乏力→脾胃虚弱→香砂六君子汤。<strong>场景三</strong>（压力型）：工作压力大→暴饮暴食（消谷善饥）→胃火，或压力大→毫无食欲（肝气犯胃）→逍遥散合左金丸。两种截然相反的表现都可能由情绪引起。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-7b-3 口味
# ═══════════════════════════════════════════
new_content_map['dx-7b-3'] = '''<p><strong>口味异常反映脏腑气机的失调——口淡脾虚、口甜湿热、口酸郁热、口苦火旺、口咸肾虚、口黏湿浊。</strong></p><div class="classic-quote">《灵枢·脉度》："脾气通于口，脾和则口能知五谷矣。"口气和味觉的变化是内脏功能的外在表现。<span class="src">——《黄帝内经》</span></div><div class="mnem">淡气虚甜湿热酸肝热，苦胆火咸肾虚黏湿浊。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">口味异常<br>脏腑气机</span><span class="df-arrow">→</span><span class="df-node df-logic">五脏化液<br>上出于口</span><span class="df-arrow">→</span><span class="df-node df-organ">淡·甜·酸<br>苦·咸·黏</span><span class="df-arrow">→</span><span class="df-node df-symptom">各有所属<br>辨证施治</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"嘴里的味道"——中医望闻问切中的"问"出大文章</span><div class="ds-body">病人说"我嘴里发苦"或者"感觉口里甜甜的"——这些"口味"的变化看起来微小，但在中医诊断中是非常有价值的信号。因为"五脏之气通于口"——肝气通于口则口酸、心气通于口则口苦、脾气通于口则口甜……口腔中的味觉变化直接反映了脏腑的气机状态。问口中味道是中医问诊中非常独特的一个项目——不问体温不问血压，但一定要问"你嘴里有什么味道"。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">口味异常的病机分析——"五脏之气上溢于口"</span><div class="ds-body">中医认为，五脏各有其"味"——肝味酸、心味苦、脾味甘、肺味辛、肾味咸。正常情况下，这些味道不会出现在口腔中。但当某个脏腑功能失调，"气机逆乱"时，相应的味道就会"上泛"到口腔中。口淡→脾气虚（脾在味为甘→但气虚不能将精微上输→口中无味、淡泊如水）。口甜→脾胃湿热（脾味甘+湿热熏蒸→甘味上泛于口）。口酸→肝胃郁热（肝味酸+郁而化热→酸水上泛）。口苦→肝胆火旺（心味苦+胆火上炎→胆汁味苦上蒸）。口咸→肾虚（肾味咸+虚火上浮→咸味上泛）。口黏腻→湿浊内停（湿气阻滞→口中黏腻不爽）。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——五种口味各有所属</span><div class="ds-body"><strong>口淡</strong>——口中淡而无味、吃东西没滋味、伴纳呆腹胀、神疲乏力、面色萎黄、舌淡苔白、脉虚弱。病机为脾胃气虚、运化无权。治法健脾益气→香砂六君子汤或参苓白术散。<strong>口甜</strong>——口中甜腻不爽、伴脘腹痞闷、纳呆呕恶、身重困倦、舌红苔黄腻、脉濡数。病机为脾胃湿热、浊气上泛。治法清热化湿→藿朴夏苓汤或甘露消毒丹。<strong>口酸</strong>——口中酸腐或酸水、伴胃脘灼痛、嗳气反酸、胸胁胀满、舌红苔黄、脉弦数。病机为肝胃郁热、胃气上逆。治法清肝和胃→左金丸（黄连+吴茱萸）合海螵蛸。<strong>口苦</strong>——口中苦涩、伴胁痛目赤、烦躁易怒、头晕头痛、大便秘结、舌红苔黄、脉弦数。病机为肝胆火旺、胆汁上溢。治法清泻肝胆→龙胆泻肝汤。若口苦+咽干+目眩+寒热往来→少阳病→小柴胡汤。<strong>口咸</strong>——口中咸味、伴腰膝酸软、头晕耳鸣、咽干口燥。偏阴虚：五心烦热、舌红少苔→左归丸或六味地黄丸。偏阳虚：畏寒肢冷、舌淡胖→右归丸或金匮肾气丸。<strong>口黏腻</strong>——口中黏滞不爽、如含浆糊、伴纳呆脘痞、头身困重、大便不爽、苔白腻或黄腻。病机为湿浊内停。代表方平胃散或三仁汤。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——同一口味可能对应虚实证的不同</span><div class="ds-body">最具迷惑性的口味鉴别是"口咸"——咸味对应肾，但肾虚有阴阳之别。肾阴虚口咸→伴五心烦热、盗汗、舌红少苔→左归丸（滋阴）。肾阳虚口咸→伴畏寒肢冷、夜尿多、舌淡胖→右归丸（温阳）。同样口咸一寒一热。口苦也需鉴别：胆火口苦（龙胆泻肝汤）→苦+胁痛+目赤+便干+脉弦数。少阳病口苦（小柴胡汤）→苦+寒热往来+胸胁苦满+脉弦。两者的区别是胆火是"纯热"（一派热象），少阳病是"半表半里"（有寒热交替）。口黏腻也要分寒湿（苔白腻→平胃散）和湿热（苔黄腻→三仁汤）。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是口苦，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（熬夜 vs 早起）：熬夜后晨起口苦+口臭+咽干→胆火上扰→龙胆泻肝汤或小柴胡汤。单纯早起口苦、白天消失→正常生理现象（胆汁夜间分泌）、无需治疗。<strong>场景二</strong>（药物相关性）：服用某些药物后口苦（如抗生素、抗抑郁药）→药源性味觉异常→停药后多可恢复。化疗后口淡或口苦→伤及脾胃气阴→香砂六君子汤或益胃汤调理。<strong>场景三</strong>（消化疾病相关性）：口酸+反酸+胃痛→反流性食管炎→左金丸合乌贝散。口苦+胁痛+B超提示胆囊炎→肝胆湿热→龙胆泻肝汤合茵陈蒿汤。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-8b-1 大便异常
# ═══════════════════════════════════════════
new_content_map['dx-8b-1'] = '''<p><strong>大便异常——便秘有热秘、冷秘、虚秘之分，泄泻有湿盛、肾阳虚之别，辨大便的性状和伴随症状是关键。</strong></p><div class="classic-quote">《素问·灵兰秘典论》："大肠者，传道之官，变化出焉。"<span class="src">——《黄帝内经》</span></div><div class="mnem">热秘麻仁冷秘脾，虚秘黄芪补中气；湿盛参苓肾泻四神，湿热痢疾白头翁。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">大便异常<br>传导失常</span><span class="df-arrow">→</span><span class="df-node df-logic">大肠传导失职<br>脾肾运化失调</span><span class="df-arrow">→</span><span class="df-node df-organ">便秘三型<br>泄泻两型</span><span class="df-arrow">→</span><span class="df-node df-symptom">麻仁·温脾<br>黄芪·参苓·四神</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"拉不出来"和"拉得太快"——大便的"节奏"反映了肠道的"气"</span><div class="ds-body">大便问题无非两种：便秘（拉不出来）和泄泻（拉得太快）。便秘有三型——有人大便干硬如羊粪（热秘→麻子仁丸），有人虽然大便不干但就是拉不干净（冷秘→温脾汤），有人大便不干但觉得没力气排出（虚秘→黄芪汤）。泄泻也有两种——有人大便稀溏、一天好几次（湿盛→参苓白术散），有人天没亮就肚子痛、拉完才舒服（五更泻/肾阳虚→四神丸）。问大便要问：几天一次还是一天几次？干还是稀？好拉还是费劲？肚子痛不痛？拉完舒服不舒服？</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">大便异常的病机分析——"大肠者传导之官"</span><div class="ds-body">大肠的职责是"传导"——把食物残渣（粪便）从体内排出。便秘→大肠传导慢了（津亏、气虚、寒凝）。泄泻→大肠传导快了/水分没被吸收（脾虚、湿盛、肾阳虚）。热秘→胃肠积热、灼伤津液→大便干硬如羊粪。冷秘→阴寒内盛、大肠传导无力→大便不干但排出困难。虚秘→气虚推动无力→大便不干但有便意但排不出。湿盛泄泻→脾虚不能运化水湿→水湿夹杂粪便一起排出→大便稀溏。肾阳虚泄泻（五更泻）→黎明时分阳气最弱→肾火不足不能温煦脾土→肠道蠕动过快→五更腹痛腹泻。湿热痢疾→湿热之邪壅滞肠道→气血阻滞→腹痛里急后重+脓血便。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——便秘三型与泄泻三型的鉴别</span><div class="ds-body"><strong>便秘</strong>——<strong>热秘</strong>：大便干结如羊粪、数日一行、伴腹满胀痛、面红身热、口干口臭、小便短赤、舌红苔黄燥、脉滑数。病机为胃肠积热。代表方麻子仁丸（润肠泻热）。<strong>冷秘</strong>：大便艰涩排出困难（便质不干）、伴腹中冷痛、得热减轻、手足不温、畏寒肢冷、舌淡苔白滑、脉沉迟。病机为阴寒凝滞、大肠传导失常。代表方温脾汤（温阳通便）或大黄附子细辛汤。<strong>虚秘</strong>：大便不干但有便意但无力排出、努挣汗出、便后乏力、伴神疲气短、面色淡白、舌淡嫩苔薄白、脉虚弱。病机为气虚推动无力。代表方黄芪汤（益气润肠）。——<strong>泄泻</strong>——<strong>湿盛泄泻</strong>：大便稀溏或水样、一日数次、伴脘腹胀闷、纳呆、身重困倦、苔白腻、脉濡缓。病机为脾虚湿盛。代表方参苓白术散（健脾渗湿）。<strong>肾阳虚泄泻</strong>：黎明前腹痛泄泻（五更泻）、泻后痛减、伴腰膝酸冷、畏寒肢冷、舌淡胖苔白、脉沉迟无力。病机为肾阳虚衰、火不暖土。代表方四神丸（温肾暖脾止泻）。<strong>湿热痢疾</strong>：腹痛里急后重、下痢脓血（赤白相兼）、肛门灼热、小便短赤、舌红苔黄腻、脉滑数。病机为湿热壅滞肠道。代表方白头翁汤（清热解毒、凉血止痢）。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——"便秘"干结和不干结的鉴别决定了泻下药的用法</span><div class="ds-body">便秘的鉴别最核心的一点就是"大便干不干"：大便干硬如羊粪→热秘（实热）→用大黄、芒硝等攻下药（麻子仁丸）。大便不干但排出困难→冷秘（寒凝）或虚秘（气虚）→绝对不能用大黄！冷秘用温脾汤（温阳散寒），虚秘用黄芪汤（益气润肠）——用错了攻下药会损伤阳气、加重病情。泄泻中"湿盛"和"肾阳虚"的鉴别是"时间"：湿盛泄泻→大便稀溏、一天多次、不定时、饮食不节会加重→参苓白术散。肾阳虚泄泻→五更泻（黎明前后）、定时而作、伴腰膝冷痛→四神丸。另外还需注意"热结旁流"（阳明腑实的一种特殊表现）——虽然大便稀水样但属于实证（腹满痛拒按+舌红苔黄燥），用大承气汤"通因通用"。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是便秘或泄泻，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（老人 vs 年轻人）：老人便秘→多虚秘（气虚推动无力+津亏肠燥）→黄芪汤合增液汤。年轻人便秘→多热秘（熬夜+辛辣+压力）→麻子仁丸或防风通圣散。<strong>场景二</strong>（产后 vs 术后）：产后大便难→血虚津亏→四物汤合增液汤加肉苁蓉。术后便秘→气虚+瘀血→黄芪汤合桃红四物汤。<strong>场景三</strong>（慢性腹泻）：反复发作的大便溏薄+食后即泻→脾虚→参苓白术散长期调理。遇冷加重的腹泻+腰酸→脾肾阳虚→四神丸合附子理中汤。<strong>场景四</strong>（肠易激综合征）：腹痛腹泻与便秘交替+情绪诱发→肝郁脾虚→痛泻要方合逍遥散。</div></div></div>'''

# ═══════════════════════════════════════════
# dx-8b-2 小便异常
# ═══════════════════════════════════════════
new_content_map['dx-8b-2'] = '''<p><strong>小便异常——尿频辨虚实（湿热下注 vs 肾阳虚），涩痛为淋证，余沥不尽为肾气虚，失禁为肾气不固。</strong></p><div class="classic-quote">《素问·灵兰秘典论》："膀胱者，州都之官，津液藏焉，气化则能出矣。"<span class="src">——《黄帝内经》</span></div><div class="mnem">尿频湿热八正散，夜尿肾阳肾气丸；涩痛淋证分清饮，余沥肾虚缩泉丸。</div><div class="derive-box"><div class="derive-flow"><span class="df-node df-concept">小便异常<br>气化失常</span><span class="df-arrow">→</span><span class="df-node df-logic">膀胱气化不利<br>肾司二便失常</span><span class="df-arrow">→</span><span class="df-node df-organ">尿频·涩痛<br>余沥·失禁</span><span class="df-arrow">→</span><span class="df-node df-symptom">八正·分清<br>缩泉·肾气丸</span></div><div class="derive-step ds-blue"><span class="ds-num">1</span><span class="ds-title">"小便的问题"——排尿的频率、感觉、控制力都是诊断信号</span><div class="ds-body">两个病人都说"小便多"——一个说"小便次数多、尿的时候尿道灼痛、尿黄"（小便频数涩痛→湿热下注），另一个说"晚上要起来三四次、尿清长、每次量不少"（夜尿多清长→肾阳虚）。虽然都叫"尿频"，但一个湿热一个虚寒，治法完全相反。问小便要问：一天几次（白天和晚上分别）？尿的时候痛不痛？尿的颜色是黄还是清？有没有尿不干净的感觉？能不能控制住？这些细节决定了是清热还是温补。</div></div><div class="derive-step ds-red"><span class="ds-num">2</span><span class="ds-title">小便异常的病机分析——"膀胱者州都之官，气化则能出矣"</span><div class="ds-body">《内经》说膀胱的功能是"气化则能出"——小便的排出依赖于"气化"功能（肾阳的蒸腾和膀胱的气化）。如果气化功能正常→小便通畅、次数适中。如果气化失常→小便异常。湿热下注→湿热之邪蕴结膀胱→"热"刺激膀胱壁→尿频急迫（想尿但忍不住）+涩痛（尿的时候像刀割/灼热）→八正散清热利湿。肾阳虚→肾阳不足→膀胱气化功能减退→夜尿增多（夜间阳气更弱）→金匮肾气丸温阳。肾气虚→肾的固摄功能减退→小便余沥不尽（尿完还想尿）→缩泉丸或金匮肾气丸。肾气不固→严重的话就小便失禁（控不住了）。热淋（急性尿路感染）→湿热下注为主→八正散；劳淋（慢性反复发作）→虚实夹杂→八正散合知柏地黄丸。</div></div><div class="derive-step ds-purple"><span class="ds-num">3</span><span class="ds-title">分型锁定——小便异常的几种常见类型</span><div class="ds-body"><strong>尿频</strong>——<strong>湿热下注</strong>：小便频数+尿急+尿道灼痛+尿色黄赤+伴小腹拘急、口渴、舌红苔黄腻、脉滑数。病机为湿热蕴结膀胱→气化不利。代表方八正散（清热利湿通淋）。<strong>肾阳虚</strong>：夜尿增多（夜尿3次以上）+小便清长+伴畏寒肢冷、腰膝酸冷、神疲乏力、舌淡胖苔白滑、脉沉迟无力。病机为肾阳不足、膀胱气化失司。代表方金匮肾气丸（温补肾阳、化气利水）。<strong>涩痛（淋证）</strong>——小便涩滞不畅、尿道疼痛。热淋→灼热刺痛+尿黄+苔黄腻→八正散。血淋→尿血+涩痛→小蓟饮子或导赤散。石淋→尿中夹砂石+涩痛→石韦散。气淋→少腹胀满+小便涩滞→沉香散。膏淋→小便如米泔水→萆薢分清饮。<strong>余沥不尽</strong>——小便后仍有尿液点滴排出（尿不干净），伴腰膝酸软、神疲乏力。病机为肾气虚、膀胱固摄无权。代表方缩泉丸或金匮肾气丸（补肾缩尿）。<strong>失禁</strong>——小便不能控制、随时自行流出。病机为肾气不固、膀胱失约。代表方桑螵蛸散或固脬汤。</div></div><div class="derive-step ds-orange"><span class="ds-num">4</span><span class="ds-title">鉴别对比——"尿频"中湿热和下虚寒最容易被混淆的要点</span><div class="ds-body">尿频的虚实鉴别是临床最常用的考点：湿热尿频→尿频+痛（涩痛、灼痛）+尿黄赤+苔黄腻+脉数→实热证→八正散清热。肾虚尿频→夜尿多+尿清长+无涩痛+腰酸+舌淡+脉沉迟→虚寒证→金匮肾气丸温补。但还有一种情况最容易误判——老年人前列腺增生：既有夜尿多（肾虚）又有排尿涩痛（湿热/瘀血），这是虚实夹杂。治法要"攻补兼施"——先清利湿热（八正散）后温补肾阳（肾气丸）或两者同用。另外，余沥不尽（尿不干净）在小便结束后仍有尿意——这是肾气虚的典型表现，不是湿热。注意和"尿后白浊"鉴别：余沥→尿后仍有尿液（清）；白浊→尿后有白色黏液滴出→湿浊下注。</div></div><div class="derive-step ds-orange"><span class="ds-num">5</span><span class="ds-title">同是小便异常，不同的人不同的病根</span><div class="ds-body"><strong>场景一</strong>（男性 vs 女性）：男性夜尿多+排尿费力+尿线细→前列腺增生（肾虚+瘀血）→桂枝茯苓丸合金匮肾气丸。女性尿频+尿急+尿痛→急性尿路感染（湿热下注）→八正散。<strong>场景二</strong>（小儿 vs 老人）：小儿遗尿（5岁以上仍尿床）→肾气未充+脾肺气虚→缩泉丸合补中益气汤。老人小便失禁→肾气不固、膀胱失约→桑螵蛸散。<strong>场景三</strong>（糖尿病）：多尿+多饮+多食+消瘦→消渴病→上消（肺热）白虎加人参汤、中消（胃火）玉女煎、下消（肾虚）六味地黄丸。<strong>场景四</strong>（妊娠后期）：小便频数+小腹坠胀→胎气下迫膀胱→补中益气汤（提升气机），一般产后恢复。</div></div></div>'''

# ── 3. Build replacement map ──
# For each point, we need to find the old content and replace it with new content
# The new content = new_core_content (with summary, classic-quote, mnem, derive-box) + original trailing elements

# First, extract original trailing elements from each point
trailing_map = {}

# Find each point and extract its trailing elements
for pid in new_content_map:
    # Find the point
    pattern = f"id:'{pid}'"
    pos = content.find(pattern)
    if pos < 0:
        print(f"ERROR: Cannot find {pid}")
        continue
    
    # Find the content field
    c_pos = content.find("content:'", pos)
    if c_pos < 0:
        print(f"ERROR: Cannot find content for {pid}")
        continue
    
    c_start = c_pos + 9  # skip 'content:''
    
    # Find the end of content (the ' that's followed by } or ,})
    # Scan from c_start and look for ' followed by , or }
    end = -1
    i = c_start
    while i < len(content):
        if content[i] == "'":
            # Check next char
            next_i = i + 1
            while next_i < len(content) and content[next_i] in ' \t\n':
                next_i += 1
            if next_i < len(content) and content[next_i] in ',}':
                end = i
                break
        i += 1
    
    if end < 0:
        print(f"ERROR: Cannot find content end for {pid}")
        continue
    
    old_content = content[c_start:end]
    
    # Extract the original trailing elements
    # The old content starts with <p>...</p> and then has trailing elements
    # We need to keep compare-table, trap-box, clinical-case, mini-quiz (but NOT clq, plain, or mnem since we replace them)
    # Actually from the design doc: keep compare-table, trap-box, clinical-case
    
    # Find all trailing elements after the initial <p> and any plain/clq/mnem that we'll replace
    trailing = ''
    
    # Strategy: keep compare-table, trap-box, clinical-case, mini-quiz
    # Remove: clq, plain (we replace with proper classic-quote and integrate into derive-box)
    # We already have classic-quote and mnem in new content
    
    # Find all elements to keep by scanning for them
    keep_tags = ['compare-table', 'trap-box', 'clinical-case', 'mini-quiz']
    keep_elements = []
    
    for tag in keep_tags:
        tag_pos = 0
        while True:
            tag_start = old_content.find(f'<div class={tag}', tag_pos)
            if tag_start == -1:
                tag_start = old_content.find(f'<div class="{tag}"', tag_pos)
            if tag_start == -1:
                break
            
            # Find the closing </div> for this element
            # Count depth
            depth = 1
            scan_pos = tag_start + len(f'<div class={tag}>') if f'<div class={tag}>' in old_content[tag_start:tag_start+100] else tag_start
            # Actually let's find the actual > that closes the opening div
            gt_pos = old_content.find('>', tag_start)
            if gt_pos == -1:
                break
            scan_pos = gt_pos + 1
            
            while depth > 0 and scan_pos < len(old_content):
                if old_content[scan_pos:scan_pos+4] == '<div':
                    depth += 1
                    scan_pos += 4
                elif old_content[scan_pos:scan_pos+5] == '</div':
                    depth -= 1
                    scan_pos += 5
                else:
                    scan_pos += 1
            
            element_text = old_content[tag_start:scan_pos]
            keep_elements.append(element_text)
            tag_pos = scan_pos
    
    # Join trailing elements (they might be in wrong order, but that's OK for compare-tables etc.)
    # Reorder by original position
    if keep_elements:
        # Sort by original position
        keep_elements.sort(key=lambda e: old_content.find(e[:30]))
        trailing = ''.join(keep_elements)
    
    trailing_map[pid] = trailing
    print(f"{pid}: old content = {len(old_content)}B, trailing = {len(trailing)}B")

# ── 4. Perform replacement ──
for pid in new_content_map:
    new_full = new_content_map[pid] + trailing_map[pid]
    
    # Find old content
    pattern = f"id:'{pid}'"
    pos = content.find(pattern)
    c_pos = content.find("content:'", pos)
    c_start = c_pos + 9
    
    # Find end
    end = -1
    i = c_start
    while i < len(content):
        if content[i] == "'":
            next_i = i + 1
            while next_i < len(content) and content[next_i] in ' \t\n':
                next_i += 1
            if next_i < len(content) and content[next_i] in ',}':
                end = i
                break
        i += 1
    
    if end < 0:
        print(f"ERROR: Cannot find content end for {pid}")
        continue
    
    old_full = content[c_start:end]
    
    # Replace
    before = content[:c_start]
    after = content[end:]
    content = before + new_full + after
    
    print(f"{pid}: replaced {len(old_full)}B → {len(new_full)}B (+{len(new_full)-len(old_full)}B)")

# ── 5. Fix comma between units ──
content = content.replace("]}]}{unit:'", "]}]},{unit:'")

# ── 6. Write result ──
with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n=== DONE ===")
print(f"Original size: {len(orig_content)} bytes")
print(f"New size: {len(content)} bytes")
print(f"Delta: +{len(content) - len(orig_content)} bytes")
